
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Verification
 * 
 */
export type Verification = Prisma.VerificationModel
/**
 * Model Organization
 * 
 */
export type Organization = Prisma.OrganizationModel
/**
 * Model OrgMembership
 * 
 */
export type OrgMembership = Prisma.OrgMembershipModel
/**
 * Model Manufacturer
 * 
 */
export type Manufacturer = Prisma.ManufacturerModel
/**
 * Model Product
 * 
 */
export type Product = Prisma.ProductModel
/**
 * Model Location
 * 
 */
export type Location = Prisma.LocationModel
/**
 * Model Asset
 * 
 */
export type Asset = Prisma.AssetModel
/**
 * Model AssetBundle
 * 
 */
export type AssetBundle = Prisma.AssetBundleModel
/**
 * Model Production
 * 
 */
export type Production = Prisma.ProductionModel
/**
 * Model ProductionItem
 * 
 */
export type ProductionItem = Prisma.ProductionItemModel
/**
 * Model ProductionCrew
 * 
 */
export type ProductionCrew = Prisma.ProductionCrewModel
/**
 * Model AssetTransaction
 * 
 */
export type AssetTransaction = Prisma.AssetTransactionModel
