
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `OfferItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model OfferItem
 * 
 */
export type OfferItemModel = runtime.Types.Result.DefaultSelection<Prisma.$OfferItemPayload>

export type AggregateOfferItem = {
  _count: OfferItemCountAggregateOutputType | null
  _avg: OfferItemAvgAggregateOutputType | null
  _sum: OfferItemSumAggregateOutputType | null
  _min: OfferItemMinAggregateOutputType | null
  _max: OfferItemMaxAggregateOutputType | null
}

export type OfferItemAvgAggregateOutputType = {
  netPurchasePrice: runtime.Decimal | null
  ratePercent: runtime.Decimal | null
  dailyRate: runtime.Decimal | null
  lineTotal: runtime.Decimal | null
}

export type OfferItemSumAggregateOutputType = {
  netPurchasePrice: runtime.Decimal | null
  ratePercent: runtime.Decimal | null
  dailyRate: runtime.Decimal | null
  lineTotal: runtime.Decimal | null
}

export type OfferItemMinAggregateOutputType = {
  id: string | null
  offerId: string | null
  assetId: string | null
  bundleId: string | null
  categoryId: string | null
  categoryName: string | null
  categoryColor: string | null
  description: string | null
  netPurchasePrice: runtime.Decimal | null
  ratePercent: runtime.Decimal | null
  dailyRate: runtime.Decimal | null
  lineTotal: runtime.Decimal | null
  createdAt: Date | null
}

export type OfferItemMaxAggregateOutputType = {
  id: string | null
  offerId: string | null
  assetId: string | null
  bundleId: string | null
  categoryId: string | null
  categoryName: string | null
  categoryColor: string | null
  description: string | null
  netPurchasePrice: runtime.Decimal | null
  ratePercent: runtime.Decimal | null
  dailyRate: runtime.Decimal | null
  lineTotal: runtime.Decimal | null
  createdAt: Date | null
}

export type OfferItemCountAggregateOutputType = {
  id: number
  offerId: number
  assetId: number
  bundleId: number
  categoryId: number
  categoryName: number
  categoryColor: number
  description: number
  netPurchasePrice: number
  ratePercent: number
  dailyRate: number
  lineTotal: number
  createdAt: number
  _all: number
}


export type OfferItemAvgAggregateInputType = {
  netPurchasePrice?: true
  ratePercent?: true
  dailyRate?: true
  lineTotal?: true
}

export type OfferItemSumAggregateInputType = {
  netPurchasePrice?: true
  ratePercent?: true
  dailyRate?: true
  lineTotal?: true
}

export type OfferItemMinAggregateInputType = {
  id?: true
  offerId?: true
  assetId?: true
  bundleId?: true
  categoryId?: true
  categoryName?: true
  categoryColor?: true
  description?: true
  netPurchasePrice?: true
  ratePercent?: true
  dailyRate?: true
  lineTotal?: true
  createdAt?: true
}

export type OfferItemMaxAggregateInputType = {
  id?: true
  offerId?: true
  assetId?: true
  bundleId?: true
  categoryId?: true
  categoryName?: true
  categoryColor?: true
  description?: true
  netPurchasePrice?: true
  ratePercent?: true
  dailyRate?: true
  lineTotal?: true
  createdAt?: true
}

export type OfferItemCountAggregateInputType = {
  id?: true
  offerId?: true
  assetId?: true
  bundleId?: true
  categoryId?: true
  categoryName?: true
  categoryColor?: true
  description?: true
  netPurchasePrice?: true
  ratePercent?: true
  dailyRate?: true
  lineTotal?: true
  createdAt?: true
  _all?: true
}

export type OfferItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OfferItem to aggregate.
   */
  where?: Prisma.OfferItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OfferItems to fetch.
   */
  orderBy?: Prisma.OfferItemOrderByWithRelationInput | Prisma.OfferItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.OfferItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OfferItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OfferItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned OfferItems
  **/
  _count?: true | OfferItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: OfferItemAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: OfferItemSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OfferItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OfferItemMaxAggregateInputType
}

export type GetOfferItemAggregateType<T extends OfferItemAggregateArgs> = {
      [P in keyof T & keyof AggregateOfferItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOfferItem[P]>
    : Prisma.GetScalarType<T[P], AggregateOfferItem[P]>
}




export type OfferItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OfferItemWhereInput
  orderBy?: Prisma.OfferItemOrderByWithAggregationInput | Prisma.OfferItemOrderByWithAggregationInput[]
  by: Prisma.OfferItemScalarFieldEnum[] | Prisma.OfferItemScalarFieldEnum
  having?: Prisma.OfferItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OfferItemCountAggregateInputType | true
  _avg?: OfferItemAvgAggregateInputType
  _sum?: OfferItemSumAggregateInputType
  _min?: OfferItemMinAggregateInputType
  _max?: OfferItemMaxAggregateInputType
}

export type OfferItemGroupByOutputType = {
  id: string
  offerId: string
  assetId: string | null
  bundleId: string | null
  categoryId: string | null
  categoryName: string | null
  categoryColor: string | null
  description: string
  netPurchasePrice: runtime.Decimal
  ratePercent: runtime.Decimal
  dailyRate: runtime.Decimal
  lineTotal: runtime.Decimal
  createdAt: Date
  _count: OfferItemCountAggregateOutputType | null
  _avg: OfferItemAvgAggregateOutputType | null
  _sum: OfferItemSumAggregateOutputType | null
  _min: OfferItemMinAggregateOutputType | null
  _max: OfferItemMaxAggregateOutputType | null
}

export type GetOfferItemGroupByPayload<T extends OfferItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OfferItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OfferItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OfferItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OfferItemGroupByOutputType[P]>
      }
    >
  >



export type OfferItemWhereInput = {
  AND?: Prisma.OfferItemWhereInput | Prisma.OfferItemWhereInput[]
  OR?: Prisma.OfferItemWhereInput[]
  NOT?: Prisma.OfferItemWhereInput | Prisma.OfferItemWhereInput[]
  id?: Prisma.StringFilter<"OfferItem"> | string
  offerId?: Prisma.StringFilter<"OfferItem"> | string
  assetId?: Prisma.StringNullableFilter<"OfferItem"> | string | null
  bundleId?: Prisma.StringNullableFilter<"OfferItem"> | string | null
  categoryId?: Prisma.StringNullableFilter<"OfferItem"> | string | null
  categoryName?: Prisma.StringNullableFilter<"OfferItem"> | string | null
  categoryColor?: Prisma.StringNullableFilter<"OfferItem"> | string | null
  description?: Prisma.StringFilter<"OfferItem"> | string
  netPurchasePrice?: Prisma.DecimalFilter<"OfferItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  ratePercent?: Prisma.DecimalFilter<"OfferItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  dailyRate?: Prisma.DecimalFilter<"OfferItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  lineTotal?: Prisma.DecimalFilter<"OfferItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"OfferItem"> | Date | string
  offer?: Prisma.XOR<Prisma.OfferScalarRelationFilter, Prisma.OfferWhereInput>
}

export type OfferItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  offerId?: Prisma.SortOrder
  assetId?: Prisma.SortOrderInput | Prisma.SortOrder
  bundleId?: Prisma.SortOrderInput | Prisma.SortOrder
  categoryId?: Prisma.SortOrderInput | Prisma.SortOrder
  categoryName?: Prisma.SortOrderInput | Prisma.SortOrder
  categoryColor?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrder
  netPurchasePrice?: Prisma.SortOrder
  ratePercent?: Prisma.SortOrder
  dailyRate?: Prisma.SortOrder
  lineTotal?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  offer?: Prisma.OfferOrderByWithRelationInput
}

export type OfferItemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.OfferItemWhereInput | Prisma.OfferItemWhereInput[]
  OR?: Prisma.OfferItemWhereInput[]
  NOT?: Prisma.OfferItemWhereInput | Prisma.OfferItemWhereInput[]
  offerId?: Prisma.StringFilter<"OfferItem"> | string
  assetId?: Prisma.StringNullableFilter<"OfferItem"> | string | null
  bundleId?: Prisma.StringNullableFilter<"OfferItem"> | string | null
  categoryId?: Prisma.StringNullableFilter<"OfferItem"> | string | null
  categoryName?: Prisma.StringNullableFilter<"OfferItem"> | string | null
  categoryColor?: Prisma.StringNullableFilter<"OfferItem"> | string | null
  description?: Prisma.StringFilter<"OfferItem"> | string
  netPurchasePrice?: Prisma.DecimalFilter<"OfferItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  ratePercent?: Prisma.DecimalFilter<"OfferItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  dailyRate?: Prisma.DecimalFilter<"OfferItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  lineTotal?: Prisma.DecimalFilter<"OfferItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"OfferItem"> | Date | string
  offer?: Prisma.XOR<Prisma.OfferScalarRelationFilter, Prisma.OfferWhereInput>
}, "id">

export type OfferItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  offerId?: Prisma.SortOrder
  assetId?: Prisma.SortOrderInput | Prisma.SortOrder
  bundleId?: Prisma.SortOrderInput | Prisma.SortOrder
  categoryId?: Prisma.SortOrderInput | Prisma.SortOrder
  categoryName?: Prisma.SortOrderInput | Prisma.SortOrder
  categoryColor?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrder
  netPurchasePrice?: Prisma.SortOrder
  ratePercent?: Prisma.SortOrder
  dailyRate?: Prisma.SortOrder
  lineTotal?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.OfferItemCountOrderByAggregateInput
  _avg?: Prisma.OfferItemAvgOrderByAggregateInput
  _max?: Prisma.OfferItemMaxOrderByAggregateInput
  _min?: Prisma.OfferItemMinOrderByAggregateInput
  _sum?: Prisma.OfferItemSumOrderByAggregateInput
}

export type OfferItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.OfferItemScalarWhereWithAggregatesInput | Prisma.OfferItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.OfferItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OfferItemScalarWhereWithAggregatesInput | Prisma.OfferItemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"OfferItem"> | string
  offerId?: Prisma.StringWithAggregatesFilter<"OfferItem"> | string
  assetId?: Prisma.StringNullableWithAggregatesFilter<"OfferItem"> | string | null
  bundleId?: Prisma.StringNullableWithAggregatesFilter<"OfferItem"> | string | null
  categoryId?: Prisma.StringNullableWithAggregatesFilter<"OfferItem"> | string | null
  categoryName?: Prisma.StringNullableWithAggregatesFilter<"OfferItem"> | string | null
  categoryColor?: Prisma.StringNullableWithAggregatesFilter<"OfferItem"> | string | null
  description?: Prisma.StringWithAggregatesFilter<"OfferItem"> | string
  netPurchasePrice?: Prisma.DecimalWithAggregatesFilter<"OfferItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  ratePercent?: Prisma.DecimalWithAggregatesFilter<"OfferItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  dailyRate?: Prisma.DecimalWithAggregatesFilter<"OfferItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  lineTotal?: Prisma.DecimalWithAggregatesFilter<"OfferItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"OfferItem"> | Date | string
}

export type OfferItemCreateInput = {
  id?: string
  assetId?: string | null
  bundleId?: string | null
  categoryId?: string | null
  categoryName?: string | null
  categoryColor?: string | null
  description: string
  netPurchasePrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  ratePercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  dailyRate: runtime.Decimal | runtime.DecimalJsLike | number | string
  lineTotal: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  offer: Prisma.OfferCreateNestedOneWithoutItemsInput
}

export type OfferItemUncheckedCreateInput = {
  id?: string
  offerId: string
  assetId?: string | null
  bundleId?: string | null
  categoryId?: string | null
  categoryName?: string | null
  categoryColor?: string | null
  description: string
  netPurchasePrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  ratePercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  dailyRate: runtime.Decimal | runtime.DecimalJsLike | number | string
  lineTotal: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
}

export type OfferItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bundleId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  netPurchasePrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ratePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dailyRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  lineTotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  offer?: Prisma.OfferUpdateOneRequiredWithoutItemsNestedInput
}

export type OfferItemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  offerId?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bundleId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  netPurchasePrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ratePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dailyRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  lineTotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OfferItemCreateManyInput = {
  id?: string
  offerId: string
  assetId?: string | null
  bundleId?: string | null
  categoryId?: string | null
  categoryName?: string | null
  categoryColor?: string | null
  description: string
  netPurchasePrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  ratePercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  dailyRate: runtime.Decimal | runtime.DecimalJsLike | number | string
  lineTotal: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
}

export type OfferItemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bundleId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  netPurchasePrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ratePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dailyRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  lineTotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OfferItemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  offerId?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bundleId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  netPurchasePrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ratePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dailyRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  lineTotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OfferItemListRelationFilter = {
  every?: Prisma.OfferItemWhereInput
  some?: Prisma.OfferItemWhereInput
  none?: Prisma.OfferItemWhereInput
}

export type OfferItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type OfferItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  offerId?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  bundleId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  categoryName?: Prisma.SortOrder
  categoryColor?: Prisma.SortOrder
  description?: Prisma.SortOrder
  netPurchasePrice?: Prisma.SortOrder
  ratePercent?: Prisma.SortOrder
  dailyRate?: Prisma.SortOrder
  lineTotal?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type OfferItemAvgOrderByAggregateInput = {
  netPurchasePrice?: Prisma.SortOrder
  ratePercent?: Prisma.SortOrder
  dailyRate?: Prisma.SortOrder
  lineTotal?: Prisma.SortOrder
}

export type OfferItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  offerId?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  bundleId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  categoryName?: Prisma.SortOrder
  categoryColor?: Prisma.SortOrder
  description?: Prisma.SortOrder
  netPurchasePrice?: Prisma.SortOrder
  ratePercent?: Prisma.SortOrder
  dailyRate?: Prisma.SortOrder
  lineTotal?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type OfferItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  offerId?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  bundleId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  categoryName?: Prisma.SortOrder
  categoryColor?: Prisma.SortOrder
  description?: Prisma.SortOrder
  netPurchasePrice?: Prisma.SortOrder
  ratePercent?: Prisma.SortOrder
  dailyRate?: Prisma.SortOrder
  lineTotal?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type OfferItemSumOrderByAggregateInput = {
  netPurchasePrice?: Prisma.SortOrder
  ratePercent?: Prisma.SortOrder
  dailyRate?: Prisma.SortOrder
  lineTotal?: Prisma.SortOrder
}

export type OfferItemCreateNestedManyWithoutOfferInput = {
  create?: Prisma.XOR<Prisma.OfferItemCreateWithoutOfferInput, Prisma.OfferItemUncheckedCreateWithoutOfferInput> | Prisma.OfferItemCreateWithoutOfferInput[] | Prisma.OfferItemUncheckedCreateWithoutOfferInput[]
  connectOrCreate?: Prisma.OfferItemCreateOrConnectWithoutOfferInput | Prisma.OfferItemCreateOrConnectWithoutOfferInput[]
  createMany?: Prisma.OfferItemCreateManyOfferInputEnvelope
  connect?: Prisma.OfferItemWhereUniqueInput | Prisma.OfferItemWhereUniqueInput[]
}

export type OfferItemUncheckedCreateNestedManyWithoutOfferInput = {
  create?: Prisma.XOR<Prisma.OfferItemCreateWithoutOfferInput, Prisma.OfferItemUncheckedCreateWithoutOfferInput> | Prisma.OfferItemCreateWithoutOfferInput[] | Prisma.OfferItemUncheckedCreateWithoutOfferInput[]
  connectOrCreate?: Prisma.OfferItemCreateOrConnectWithoutOfferInput | Prisma.OfferItemCreateOrConnectWithoutOfferInput[]
  createMany?: Prisma.OfferItemCreateManyOfferInputEnvelope
  connect?: Prisma.OfferItemWhereUniqueInput | Prisma.OfferItemWhereUniqueInput[]
}

export type OfferItemUpdateManyWithoutOfferNestedInput = {
  create?: Prisma.XOR<Prisma.OfferItemCreateWithoutOfferInput, Prisma.OfferItemUncheckedCreateWithoutOfferInput> | Prisma.OfferItemCreateWithoutOfferInput[] | Prisma.OfferItemUncheckedCreateWithoutOfferInput[]
  connectOrCreate?: Prisma.OfferItemCreateOrConnectWithoutOfferInput | Prisma.OfferItemCreateOrConnectWithoutOfferInput[]
  upsert?: Prisma.OfferItemUpsertWithWhereUniqueWithoutOfferInput | Prisma.OfferItemUpsertWithWhereUniqueWithoutOfferInput[]
  createMany?: Prisma.OfferItemCreateManyOfferInputEnvelope
  set?: Prisma.OfferItemWhereUniqueInput | Prisma.OfferItemWhereUniqueInput[]
  disconnect?: Prisma.OfferItemWhereUniqueInput | Prisma.OfferItemWhereUniqueInput[]
  delete?: Prisma.OfferItemWhereUniqueInput | Prisma.OfferItemWhereUniqueInput[]
  connect?: Prisma.OfferItemWhereUniqueInput | Prisma.OfferItemWhereUniqueInput[]
  update?: Prisma.OfferItemUpdateWithWhereUniqueWithoutOfferInput | Prisma.OfferItemUpdateWithWhereUniqueWithoutOfferInput[]
  updateMany?: Prisma.OfferItemUpdateManyWithWhereWithoutOfferInput | Prisma.OfferItemUpdateManyWithWhereWithoutOfferInput[]
  deleteMany?: Prisma.OfferItemScalarWhereInput | Prisma.OfferItemScalarWhereInput[]
}

export type OfferItemUncheckedUpdateManyWithoutOfferNestedInput = {
  create?: Prisma.XOR<Prisma.OfferItemCreateWithoutOfferInput, Prisma.OfferItemUncheckedCreateWithoutOfferInput> | Prisma.OfferItemCreateWithoutOfferInput[] | Prisma.OfferItemUncheckedCreateWithoutOfferInput[]
  connectOrCreate?: Prisma.OfferItemCreateOrConnectWithoutOfferInput | Prisma.OfferItemCreateOrConnectWithoutOfferInput[]
  upsert?: Prisma.OfferItemUpsertWithWhereUniqueWithoutOfferInput | Prisma.OfferItemUpsertWithWhereUniqueWithoutOfferInput[]
  createMany?: Prisma.OfferItemCreateManyOfferInputEnvelope
  set?: Prisma.OfferItemWhereUniqueInput | Prisma.OfferItemWhereUniqueInput[]
  disconnect?: Prisma.OfferItemWhereUniqueInput | Prisma.OfferItemWhereUniqueInput[]
  delete?: Prisma.OfferItemWhereUniqueInput | Prisma.OfferItemWhereUniqueInput[]
  connect?: Prisma.OfferItemWhereUniqueInput | Prisma.OfferItemWhereUniqueInput[]
  update?: Prisma.OfferItemUpdateWithWhereUniqueWithoutOfferInput | Prisma.OfferItemUpdateWithWhereUniqueWithoutOfferInput[]
  updateMany?: Prisma.OfferItemUpdateManyWithWhereWithoutOfferInput | Prisma.OfferItemUpdateManyWithWhereWithoutOfferInput[]
  deleteMany?: Prisma.OfferItemScalarWhereInput | Prisma.OfferItemScalarWhereInput[]
}

export type OfferItemCreateWithoutOfferInput = {
  id?: string
  assetId?: string | null
  bundleId?: string | null
  categoryId?: string | null
  categoryName?: string | null
  categoryColor?: string | null
  description: string
  netPurchasePrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  ratePercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  dailyRate: runtime.Decimal | runtime.DecimalJsLike | number | string
  lineTotal: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
}

export type OfferItemUncheckedCreateWithoutOfferInput = {
  id?: string
  assetId?: string | null
  bundleId?: string | null
  categoryId?: string | null
  categoryName?: string | null
  categoryColor?: string | null
  description: string
  netPurchasePrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  ratePercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  dailyRate: runtime.Decimal | runtime.DecimalJsLike | number | string
  lineTotal: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
}

export type OfferItemCreateOrConnectWithoutOfferInput = {
  where: Prisma.OfferItemWhereUniqueInput
  create: Prisma.XOR<Prisma.OfferItemCreateWithoutOfferInput, Prisma.OfferItemUncheckedCreateWithoutOfferInput>
}

export type OfferItemCreateManyOfferInputEnvelope = {
  data: Prisma.OfferItemCreateManyOfferInput | Prisma.OfferItemCreateManyOfferInput[]
  skipDuplicates?: boolean
}

export type OfferItemUpsertWithWhereUniqueWithoutOfferInput = {
  where: Prisma.OfferItemWhereUniqueInput
  update: Prisma.XOR<Prisma.OfferItemUpdateWithoutOfferInput, Prisma.OfferItemUncheckedUpdateWithoutOfferInput>
  create: Prisma.XOR<Prisma.OfferItemCreateWithoutOfferInput, Prisma.OfferItemUncheckedCreateWithoutOfferInput>
}

export type OfferItemUpdateWithWhereUniqueWithoutOfferInput = {
  where: Prisma.OfferItemWhereUniqueInput
  data: Prisma.XOR<Prisma.OfferItemUpdateWithoutOfferInput, Prisma.OfferItemUncheckedUpdateWithoutOfferInput>
}

export type OfferItemUpdateManyWithWhereWithoutOfferInput = {
  where: Prisma.OfferItemScalarWhereInput
  data: Prisma.XOR<Prisma.OfferItemUpdateManyMutationInput, Prisma.OfferItemUncheckedUpdateManyWithoutOfferInput>
}

export type OfferItemScalarWhereInput = {
  AND?: Prisma.OfferItemScalarWhereInput | Prisma.OfferItemScalarWhereInput[]
  OR?: Prisma.OfferItemScalarWhereInput[]
  NOT?: Prisma.OfferItemScalarWhereInput | Prisma.OfferItemScalarWhereInput[]
  id?: Prisma.StringFilter<"OfferItem"> | string
  offerId?: Prisma.StringFilter<"OfferItem"> | string
  assetId?: Prisma.StringNullableFilter<"OfferItem"> | string | null
  bundleId?: Prisma.StringNullableFilter<"OfferItem"> | string | null
  categoryId?: Prisma.StringNullableFilter<"OfferItem"> | string | null
  categoryName?: Prisma.StringNullableFilter<"OfferItem"> | string | null
  categoryColor?: Prisma.StringNullableFilter<"OfferItem"> | string | null
  description?: Prisma.StringFilter<"OfferItem"> | string
  netPurchasePrice?: Prisma.DecimalFilter<"OfferItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  ratePercent?: Prisma.DecimalFilter<"OfferItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  dailyRate?: Prisma.DecimalFilter<"OfferItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  lineTotal?: Prisma.DecimalFilter<"OfferItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"OfferItem"> | Date | string
}

export type OfferItemCreateManyOfferInput = {
  id?: string
  assetId?: string | null
  bundleId?: string | null
  categoryId?: string | null
  categoryName?: string | null
  categoryColor?: string | null
  description: string
  netPurchasePrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  ratePercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  dailyRate: runtime.Decimal | runtime.DecimalJsLike | number | string
  lineTotal: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
}

export type OfferItemUpdateWithoutOfferInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bundleId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  netPurchasePrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ratePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dailyRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  lineTotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OfferItemUncheckedUpdateWithoutOfferInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bundleId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  netPurchasePrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ratePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dailyRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  lineTotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OfferItemUncheckedUpdateManyWithoutOfferInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bundleId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  netPurchasePrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ratePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dailyRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  lineTotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type OfferItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  offerId?: boolean
  assetId?: boolean
  bundleId?: boolean
  categoryId?: boolean
  categoryName?: boolean
  categoryColor?: boolean
  description?: boolean
  netPurchasePrice?: boolean
  ratePercent?: boolean
  dailyRate?: boolean
  lineTotal?: boolean
  createdAt?: boolean
  offer?: boolean | Prisma.OfferDefaultArgs<ExtArgs>
}, ExtArgs["result"]["offerItem"]>

export type OfferItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  offerId?: boolean
  assetId?: boolean
  bundleId?: boolean
  categoryId?: boolean
  categoryName?: boolean
  categoryColor?: boolean
  description?: boolean
  netPurchasePrice?: boolean
  ratePercent?: boolean
  dailyRate?: boolean
  lineTotal?: boolean
  createdAt?: boolean
  offer?: boolean | Prisma.OfferDefaultArgs<ExtArgs>
}, ExtArgs["result"]["offerItem"]>

export type OfferItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  offerId?: boolean
  assetId?: boolean
  bundleId?: boolean
  categoryId?: boolean
  categoryName?: boolean
  categoryColor?: boolean
  description?: boolean
  netPurchasePrice?: boolean
  ratePercent?: boolean
  dailyRate?: boolean
  lineTotal?: boolean
  createdAt?: boolean
  offer?: boolean | Prisma.OfferDefaultArgs<ExtArgs>
}, ExtArgs["result"]["offerItem"]>

export type OfferItemSelectScalar = {
  id?: boolean
  offerId?: boolean
  assetId?: boolean
  bundleId?: boolean
  categoryId?: boolean
  categoryName?: boolean
  categoryColor?: boolean
  description?: boolean
  netPurchasePrice?: boolean
  ratePercent?: boolean
  dailyRate?: boolean
  lineTotal?: boolean
  createdAt?: boolean
}

export type OfferItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "offerId" | "assetId" | "bundleId" | "categoryId" | "categoryName" | "categoryColor" | "description" | "netPurchasePrice" | "ratePercent" | "dailyRate" | "lineTotal" | "createdAt", ExtArgs["result"]["offerItem"]>
export type OfferItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  offer?: boolean | Prisma.OfferDefaultArgs<ExtArgs>
}
export type OfferItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  offer?: boolean | Prisma.OfferDefaultArgs<ExtArgs>
}
export type OfferItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  offer?: boolean | Prisma.OfferDefaultArgs<ExtArgs>
}

export type $OfferItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OfferItem"
  objects: {
    offer: Prisma.$OfferPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    offerId: string
    assetId: string | null
    bundleId: string | null
    categoryId: string | null
    categoryName: string | null
    categoryColor: string | null
    description: string
    netPurchasePrice: runtime.Decimal
    ratePercent: runtime.Decimal
    dailyRate: runtime.Decimal
    lineTotal: runtime.Decimal
    createdAt: Date
  }, ExtArgs["result"]["offerItem"]>
  composites: {}
}

export type OfferItemGetPayload<S extends boolean | null | undefined | OfferItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OfferItemPayload, S>

export type OfferItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OfferItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OfferItemCountAggregateInputType | true
  }

export interface OfferItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OfferItem'], meta: { name: 'OfferItem' } }
  /**
   * Find zero or one OfferItem that matches the filter.
   * @param {OfferItemFindUniqueArgs} args - Arguments to find a OfferItem
   * @example
   * // Get one OfferItem
   * const offerItem = await prisma.offerItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OfferItemFindUniqueArgs>(args: Prisma.SelectSubset<T, OfferItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OfferItemClient<runtime.Types.Result.GetResult<Prisma.$OfferItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OfferItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OfferItemFindUniqueOrThrowArgs} args - Arguments to find a OfferItem
   * @example
   * // Get one OfferItem
   * const offerItem = await prisma.offerItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OfferItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OfferItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OfferItemClient<runtime.Types.Result.GetResult<Prisma.$OfferItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OfferItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfferItemFindFirstArgs} args - Arguments to find a OfferItem
   * @example
   * // Get one OfferItem
   * const offerItem = await prisma.offerItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OfferItemFindFirstArgs>(args?: Prisma.SelectSubset<T, OfferItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__OfferItemClient<runtime.Types.Result.GetResult<Prisma.$OfferItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OfferItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfferItemFindFirstOrThrowArgs} args - Arguments to find a OfferItem
   * @example
   * // Get one OfferItem
   * const offerItem = await prisma.offerItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OfferItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OfferItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OfferItemClient<runtime.Types.Result.GetResult<Prisma.$OfferItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OfferItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfferItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OfferItems
   * const offerItems = await prisma.offerItem.findMany()
   * 
   * // Get first 10 OfferItems
   * const offerItems = await prisma.offerItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const offerItemWithIdOnly = await prisma.offerItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends OfferItemFindManyArgs>(args?: Prisma.SelectSubset<T, OfferItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfferItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OfferItem.
   * @param {OfferItemCreateArgs} args - Arguments to create a OfferItem.
   * @example
   * // Create one OfferItem
   * const OfferItem = await prisma.offerItem.create({
   *   data: {
   *     // ... data to create a OfferItem
   *   }
   * })
   * 
   */
  create<T extends OfferItemCreateArgs>(args: Prisma.SelectSubset<T, OfferItemCreateArgs<ExtArgs>>): Prisma.Prisma__OfferItemClient<runtime.Types.Result.GetResult<Prisma.$OfferItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OfferItems.
   * @param {OfferItemCreateManyArgs} args - Arguments to create many OfferItems.
   * @example
   * // Create many OfferItems
   * const offerItem = await prisma.offerItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends OfferItemCreateManyArgs>(args?: Prisma.SelectSubset<T, OfferItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many OfferItems and returns the data saved in the database.
   * @param {OfferItemCreateManyAndReturnArgs} args - Arguments to create many OfferItems.
   * @example
   * // Create many OfferItems
   * const offerItem = await prisma.offerItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many OfferItems and only return the `id`
   * const offerItemWithIdOnly = await prisma.offerItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends OfferItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, OfferItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfferItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a OfferItem.
   * @param {OfferItemDeleteArgs} args - Arguments to delete one OfferItem.
   * @example
   * // Delete one OfferItem
   * const OfferItem = await prisma.offerItem.delete({
   *   where: {
   *     // ... filter to delete one OfferItem
   *   }
   * })
   * 
   */
  delete<T extends OfferItemDeleteArgs>(args: Prisma.SelectSubset<T, OfferItemDeleteArgs<ExtArgs>>): Prisma.Prisma__OfferItemClient<runtime.Types.Result.GetResult<Prisma.$OfferItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OfferItem.
   * @param {OfferItemUpdateArgs} args - Arguments to update one OfferItem.
   * @example
   * // Update one OfferItem
   * const offerItem = await prisma.offerItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends OfferItemUpdateArgs>(args: Prisma.SelectSubset<T, OfferItemUpdateArgs<ExtArgs>>): Prisma.Prisma__OfferItemClient<runtime.Types.Result.GetResult<Prisma.$OfferItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OfferItems.
   * @param {OfferItemDeleteManyArgs} args - Arguments to filter OfferItems to delete.
   * @example
   * // Delete a few OfferItems
   * const { count } = await prisma.offerItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends OfferItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, OfferItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OfferItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfferItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OfferItems
   * const offerItem = await prisma.offerItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends OfferItemUpdateManyArgs>(args: Prisma.SelectSubset<T, OfferItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OfferItems and returns the data updated in the database.
   * @param {OfferItemUpdateManyAndReturnArgs} args - Arguments to update many OfferItems.
   * @example
   * // Update many OfferItems
   * const offerItem = await prisma.offerItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more OfferItems and only return the `id`
   * const offerItemWithIdOnly = await prisma.offerItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends OfferItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, OfferItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfferItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one OfferItem.
   * @param {OfferItemUpsertArgs} args - Arguments to update or create a OfferItem.
   * @example
   * // Update or create a OfferItem
   * const offerItem = await prisma.offerItem.upsert({
   *   create: {
   *     // ... data to create a OfferItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OfferItem we want to update
   *   }
   * })
   */
  upsert<T extends OfferItemUpsertArgs>(args: Prisma.SelectSubset<T, OfferItemUpsertArgs<ExtArgs>>): Prisma.Prisma__OfferItemClient<runtime.Types.Result.GetResult<Prisma.$OfferItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OfferItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfferItemCountArgs} args - Arguments to filter OfferItems to count.
   * @example
   * // Count the number of OfferItems
   * const count = await prisma.offerItem.count({
   *   where: {
   *     // ... the filter for the OfferItems we want to count
   *   }
   * })
  **/
  count<T extends OfferItemCountArgs>(
    args?: Prisma.Subset<T, OfferItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OfferItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OfferItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfferItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OfferItemAggregateArgs>(args: Prisma.Subset<T, OfferItemAggregateArgs>): Prisma.PrismaPromise<GetOfferItemAggregateType<T>>

  /**
   * Group by OfferItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfferItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends OfferItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OfferItemGroupByArgs['orderBy'] }
      : { orderBy?: OfferItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OfferItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOfferItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OfferItem model
 */
readonly fields: OfferItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OfferItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OfferItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  offer<T extends Prisma.OfferDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OfferDefaultArgs<ExtArgs>>): Prisma.Prisma__OfferClient<runtime.Types.Result.GetResult<Prisma.$OfferPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OfferItem model
 */
export interface OfferItemFieldRefs {
  readonly id: Prisma.FieldRef<"OfferItem", 'String'>
  readonly offerId: Prisma.FieldRef<"OfferItem", 'String'>
  readonly assetId: Prisma.FieldRef<"OfferItem", 'String'>
  readonly bundleId: Prisma.FieldRef<"OfferItem", 'String'>
  readonly categoryId: Prisma.FieldRef<"OfferItem", 'String'>
  readonly categoryName: Prisma.FieldRef<"OfferItem", 'String'>
  readonly categoryColor: Prisma.FieldRef<"OfferItem", 'String'>
  readonly description: Prisma.FieldRef<"OfferItem", 'String'>
  readonly netPurchasePrice: Prisma.FieldRef<"OfferItem", 'Decimal'>
  readonly ratePercent: Prisma.FieldRef<"OfferItem", 'Decimal'>
  readonly dailyRate: Prisma.FieldRef<"OfferItem", 'Decimal'>
  readonly lineTotal: Prisma.FieldRef<"OfferItem", 'Decimal'>
  readonly createdAt: Prisma.FieldRef<"OfferItem", 'DateTime'>
}
    

// Custom InputTypes
/**
 * OfferItem findUnique
 */
export type OfferItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfferItem
   */
  select?: Prisma.OfferItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfferItem
   */
  omit?: Prisma.OfferItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfferItemInclude<ExtArgs> | null
  /**
   * Filter, which OfferItem to fetch.
   */
  where: Prisma.OfferItemWhereUniqueInput
}

/**
 * OfferItem findUniqueOrThrow
 */
export type OfferItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfferItem
   */
  select?: Prisma.OfferItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfferItem
   */
  omit?: Prisma.OfferItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfferItemInclude<ExtArgs> | null
  /**
   * Filter, which OfferItem to fetch.
   */
  where: Prisma.OfferItemWhereUniqueInput
}

/**
 * OfferItem findFirst
 */
export type OfferItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfferItem
   */
  select?: Prisma.OfferItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfferItem
   */
  omit?: Prisma.OfferItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfferItemInclude<ExtArgs> | null
  /**
   * Filter, which OfferItem to fetch.
   */
  where?: Prisma.OfferItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OfferItems to fetch.
   */
  orderBy?: Prisma.OfferItemOrderByWithRelationInput | Prisma.OfferItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OfferItems.
   */
  cursor?: Prisma.OfferItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OfferItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OfferItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OfferItems.
   */
  distinct?: Prisma.OfferItemScalarFieldEnum | Prisma.OfferItemScalarFieldEnum[]
}

/**
 * OfferItem findFirstOrThrow
 */
export type OfferItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfferItem
   */
  select?: Prisma.OfferItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfferItem
   */
  omit?: Prisma.OfferItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfferItemInclude<ExtArgs> | null
  /**
   * Filter, which OfferItem to fetch.
   */
  where?: Prisma.OfferItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OfferItems to fetch.
   */
  orderBy?: Prisma.OfferItemOrderByWithRelationInput | Prisma.OfferItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OfferItems.
   */
  cursor?: Prisma.OfferItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OfferItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OfferItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OfferItems.
   */
  distinct?: Prisma.OfferItemScalarFieldEnum | Prisma.OfferItemScalarFieldEnum[]
}

/**
 * OfferItem findMany
 */
export type OfferItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfferItem
   */
  select?: Prisma.OfferItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfferItem
   */
  omit?: Prisma.OfferItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfferItemInclude<ExtArgs> | null
  /**
   * Filter, which OfferItems to fetch.
   */
  where?: Prisma.OfferItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OfferItems to fetch.
   */
  orderBy?: Prisma.OfferItemOrderByWithRelationInput | Prisma.OfferItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing OfferItems.
   */
  cursor?: Prisma.OfferItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OfferItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OfferItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OfferItems.
   */
  distinct?: Prisma.OfferItemScalarFieldEnum | Prisma.OfferItemScalarFieldEnum[]
}

/**
 * OfferItem create
 */
export type OfferItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfferItem
   */
  select?: Prisma.OfferItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfferItem
   */
  omit?: Prisma.OfferItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfferItemInclude<ExtArgs> | null
  /**
   * The data needed to create a OfferItem.
   */
  data: Prisma.XOR<Prisma.OfferItemCreateInput, Prisma.OfferItemUncheckedCreateInput>
}

/**
 * OfferItem createMany
 */
export type OfferItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OfferItems.
   */
  data: Prisma.OfferItemCreateManyInput | Prisma.OfferItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OfferItem createManyAndReturn
 */
export type OfferItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfferItem
   */
  select?: Prisma.OfferItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OfferItem
   */
  omit?: Prisma.OfferItemOmit<ExtArgs> | null
  /**
   * The data used to create many OfferItems.
   */
  data: Prisma.OfferItemCreateManyInput | Prisma.OfferItemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfferItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * OfferItem update
 */
export type OfferItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfferItem
   */
  select?: Prisma.OfferItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfferItem
   */
  omit?: Prisma.OfferItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfferItemInclude<ExtArgs> | null
  /**
   * The data needed to update a OfferItem.
   */
  data: Prisma.XOR<Prisma.OfferItemUpdateInput, Prisma.OfferItemUncheckedUpdateInput>
  /**
   * Choose, which OfferItem to update.
   */
  where: Prisma.OfferItemWhereUniqueInput
}

/**
 * OfferItem updateMany
 */
export type OfferItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OfferItems.
   */
  data: Prisma.XOR<Prisma.OfferItemUpdateManyMutationInput, Prisma.OfferItemUncheckedUpdateManyInput>
  /**
   * Filter which OfferItems to update
   */
  where?: Prisma.OfferItemWhereInput
  /**
   * Limit how many OfferItems to update.
   */
  limit?: number
}

/**
 * OfferItem updateManyAndReturn
 */
export type OfferItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfferItem
   */
  select?: Prisma.OfferItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OfferItem
   */
  omit?: Prisma.OfferItemOmit<ExtArgs> | null
  /**
   * The data used to update OfferItems.
   */
  data: Prisma.XOR<Prisma.OfferItemUpdateManyMutationInput, Prisma.OfferItemUncheckedUpdateManyInput>
  /**
   * Filter which OfferItems to update
   */
  where?: Prisma.OfferItemWhereInput
  /**
   * Limit how many OfferItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfferItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * OfferItem upsert
 */
export type OfferItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfferItem
   */
  select?: Prisma.OfferItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfferItem
   */
  omit?: Prisma.OfferItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfferItemInclude<ExtArgs> | null
  /**
   * The filter to search for the OfferItem to update in case it exists.
   */
  where: Prisma.OfferItemWhereUniqueInput
  /**
   * In case the OfferItem found by the `where` argument doesn't exist, create a new OfferItem with this data.
   */
  create: Prisma.XOR<Prisma.OfferItemCreateInput, Prisma.OfferItemUncheckedCreateInput>
  /**
   * In case the OfferItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OfferItemUpdateInput, Prisma.OfferItemUncheckedUpdateInput>
}

/**
 * OfferItem delete
 */
export type OfferItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfferItem
   */
  select?: Prisma.OfferItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfferItem
   */
  omit?: Prisma.OfferItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfferItemInclude<ExtArgs> | null
  /**
   * Filter which OfferItem to delete.
   */
  where: Prisma.OfferItemWhereUniqueInput
}

/**
 * OfferItem deleteMany
 */
export type OfferItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OfferItems to delete
   */
  where?: Prisma.OfferItemWhereInput
  /**
   * Limit how many OfferItems to delete.
   */
  limit?: number
}

/**
 * OfferItem without action
 */
export type OfferItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfferItem
   */
  select?: Prisma.OfferItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfferItem
   */
  omit?: Prisma.OfferItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfferItemInclude<ExtArgs> | null
}
