
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `OrgProductPrice` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model OrgProductPrice
 * 
 */
export type OrgProductPriceModel = runtime.Types.Result.DefaultSelection<Prisma.$OrgProductPricePayload>

export type AggregateOrgProductPrice = {
  _count: OrgProductPriceCountAggregateOutputType | null
  _avg: OrgProductPriceAvgAggregateOutputType | null
  _sum: OrgProductPriceSumAggregateOutputType | null
  _min: OrgProductPriceMinAggregateOutputType | null
  _max: OrgProductPriceMaxAggregateOutputType | null
}

export type OrgProductPriceAvgAggregateOutputType = {
  netPurchasePrice: runtime.Decimal | null
}

export type OrgProductPriceSumAggregateOutputType = {
  netPurchasePrice: runtime.Decimal | null
}

export type OrgProductPriceMinAggregateOutputType = {
  id: string | null
  organizationId: string | null
  productId: string | null
  netPurchasePrice: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OrgProductPriceMaxAggregateOutputType = {
  id: string | null
  organizationId: string | null
  productId: string | null
  netPurchasePrice: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OrgProductPriceCountAggregateOutputType = {
  id: number
  organizationId: number
  productId: number
  netPurchasePrice: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type OrgProductPriceAvgAggregateInputType = {
  netPurchasePrice?: true
}

export type OrgProductPriceSumAggregateInputType = {
  netPurchasePrice?: true
}

export type OrgProductPriceMinAggregateInputType = {
  id?: true
  organizationId?: true
  productId?: true
  netPurchasePrice?: true
  createdAt?: true
  updatedAt?: true
}

export type OrgProductPriceMaxAggregateInputType = {
  id?: true
  organizationId?: true
  productId?: true
  netPurchasePrice?: true
  createdAt?: true
  updatedAt?: true
}

export type OrgProductPriceCountAggregateInputType = {
  id?: true
  organizationId?: true
  productId?: true
  netPurchasePrice?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type OrgProductPriceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OrgProductPrice to aggregate.
   */
  where?: Prisma.OrgProductPriceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrgProductPrices to fetch.
   */
  orderBy?: Prisma.OrgProductPriceOrderByWithRelationInput | Prisma.OrgProductPriceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.OrgProductPriceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrgProductPrices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrgProductPrices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned OrgProductPrices
  **/
  _count?: true | OrgProductPriceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: OrgProductPriceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: OrgProductPriceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OrgProductPriceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OrgProductPriceMaxAggregateInputType
}

export type GetOrgProductPriceAggregateType<T extends OrgProductPriceAggregateArgs> = {
      [P in keyof T & keyof AggregateOrgProductPrice]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrgProductPrice[P]>
    : Prisma.GetScalarType<T[P], AggregateOrgProductPrice[P]>
}




export type OrgProductPriceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrgProductPriceWhereInput
  orderBy?: Prisma.OrgProductPriceOrderByWithAggregationInput | Prisma.OrgProductPriceOrderByWithAggregationInput[]
  by: Prisma.OrgProductPriceScalarFieldEnum[] | Prisma.OrgProductPriceScalarFieldEnum
  having?: Prisma.OrgProductPriceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OrgProductPriceCountAggregateInputType | true
  _avg?: OrgProductPriceAvgAggregateInputType
  _sum?: OrgProductPriceSumAggregateInputType
  _min?: OrgProductPriceMinAggregateInputType
  _max?: OrgProductPriceMaxAggregateInputType
}

export type OrgProductPriceGroupByOutputType = {
  id: string
  organizationId: string
  productId: string
  netPurchasePrice: runtime.Decimal
  createdAt: Date
  updatedAt: Date
  _count: OrgProductPriceCountAggregateOutputType | null
  _avg: OrgProductPriceAvgAggregateOutputType | null
  _sum: OrgProductPriceSumAggregateOutputType | null
  _min: OrgProductPriceMinAggregateOutputType | null
  _max: OrgProductPriceMaxAggregateOutputType | null
}

export type GetOrgProductPriceGroupByPayload<T extends OrgProductPriceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OrgProductPriceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OrgProductPriceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OrgProductPriceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OrgProductPriceGroupByOutputType[P]>
      }
    >
  >



export type OrgProductPriceWhereInput = {
  AND?: Prisma.OrgProductPriceWhereInput | Prisma.OrgProductPriceWhereInput[]
  OR?: Prisma.OrgProductPriceWhereInput[]
  NOT?: Prisma.OrgProductPriceWhereInput | Prisma.OrgProductPriceWhereInput[]
  id?: Prisma.StringFilter<"OrgProductPrice"> | string
  organizationId?: Prisma.StringFilter<"OrgProductPrice"> | string
  productId?: Prisma.StringFilter<"OrgProductPrice"> | string
  netPurchasePrice?: Prisma.DecimalFilter<"OrgProductPrice"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"OrgProductPrice"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OrgProductPrice"> | Date | string
  organization?: Prisma.XOR<Prisma.OrganizationScalarRelationFilter, Prisma.OrganizationWhereInput>
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type OrgProductPriceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  netPurchasePrice?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  organization?: Prisma.OrganizationOrderByWithRelationInput
  product?: Prisma.ProductOrderByWithRelationInput
}

export type OrgProductPriceWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  organizationId_productId?: Prisma.OrgProductPriceOrganizationIdProductIdCompoundUniqueInput
  AND?: Prisma.OrgProductPriceWhereInput | Prisma.OrgProductPriceWhereInput[]
  OR?: Prisma.OrgProductPriceWhereInput[]
  NOT?: Prisma.OrgProductPriceWhereInput | Prisma.OrgProductPriceWhereInput[]
  organizationId?: Prisma.StringFilter<"OrgProductPrice"> | string
  productId?: Prisma.StringFilter<"OrgProductPrice"> | string
  netPurchasePrice?: Prisma.DecimalFilter<"OrgProductPrice"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"OrgProductPrice"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OrgProductPrice"> | Date | string
  organization?: Prisma.XOR<Prisma.OrganizationScalarRelationFilter, Prisma.OrganizationWhereInput>
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "id" | "organizationId_productId">

export type OrgProductPriceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  netPurchasePrice?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.OrgProductPriceCountOrderByAggregateInput
  _avg?: Prisma.OrgProductPriceAvgOrderByAggregateInput
  _max?: Prisma.OrgProductPriceMaxOrderByAggregateInput
  _min?: Prisma.OrgProductPriceMinOrderByAggregateInput
  _sum?: Prisma.OrgProductPriceSumOrderByAggregateInput
}

export type OrgProductPriceScalarWhereWithAggregatesInput = {
  AND?: Prisma.OrgProductPriceScalarWhereWithAggregatesInput | Prisma.OrgProductPriceScalarWhereWithAggregatesInput[]
  OR?: Prisma.OrgProductPriceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OrgProductPriceScalarWhereWithAggregatesInput | Prisma.OrgProductPriceScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"OrgProductPrice"> | string
  organizationId?: Prisma.StringWithAggregatesFilter<"OrgProductPrice"> | string
  productId?: Prisma.StringWithAggregatesFilter<"OrgProductPrice"> | string
  netPurchasePrice?: Prisma.DecimalWithAggregatesFilter<"OrgProductPrice"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"OrgProductPrice"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"OrgProductPrice"> | Date | string
}

export type OrgProductPriceCreateInput = {
  id?: string
  netPurchasePrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutProductPricesInput
  product: Prisma.ProductCreateNestedOneWithoutOrgPricesInput
}

export type OrgProductPriceUncheckedCreateInput = {
  id?: string
  organizationId: string
  productId: string
  netPurchasePrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrgProductPriceUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  netPurchasePrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutProductPricesNestedInput
  product?: Prisma.ProductUpdateOneRequiredWithoutOrgPricesNestedInput
}

export type OrgProductPriceUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  netPurchasePrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrgProductPriceCreateManyInput = {
  id?: string
  organizationId: string
  productId: string
  netPurchasePrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrgProductPriceUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  netPurchasePrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrgProductPriceUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  netPurchasePrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrgProductPriceListRelationFilter = {
  every?: Prisma.OrgProductPriceWhereInput
  some?: Prisma.OrgProductPriceWhereInput
  none?: Prisma.OrgProductPriceWhereInput
}

export type OrgProductPriceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type OrgProductPriceOrganizationIdProductIdCompoundUniqueInput = {
  organizationId: string
  productId: string
}

export type OrgProductPriceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  netPurchasePrice?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OrgProductPriceAvgOrderByAggregateInput = {
  netPurchasePrice?: Prisma.SortOrder
}

export type OrgProductPriceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  netPurchasePrice?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OrgProductPriceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  netPurchasePrice?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OrgProductPriceSumOrderByAggregateInput = {
  netPurchasePrice?: Prisma.SortOrder
}

export type OrgProductPriceCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.OrgProductPriceCreateWithoutOrganizationInput, Prisma.OrgProductPriceUncheckedCreateWithoutOrganizationInput> | Prisma.OrgProductPriceCreateWithoutOrganizationInput[] | Prisma.OrgProductPriceUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.OrgProductPriceCreateOrConnectWithoutOrganizationInput | Prisma.OrgProductPriceCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.OrgProductPriceCreateManyOrganizationInputEnvelope
  connect?: Prisma.OrgProductPriceWhereUniqueInput | Prisma.OrgProductPriceWhereUniqueInput[]
}

export type OrgProductPriceUncheckedCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.OrgProductPriceCreateWithoutOrganizationInput, Prisma.OrgProductPriceUncheckedCreateWithoutOrganizationInput> | Prisma.OrgProductPriceCreateWithoutOrganizationInput[] | Prisma.OrgProductPriceUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.OrgProductPriceCreateOrConnectWithoutOrganizationInput | Prisma.OrgProductPriceCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.OrgProductPriceCreateManyOrganizationInputEnvelope
  connect?: Prisma.OrgProductPriceWhereUniqueInput | Prisma.OrgProductPriceWhereUniqueInput[]
}

export type OrgProductPriceUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.OrgProductPriceCreateWithoutOrganizationInput, Prisma.OrgProductPriceUncheckedCreateWithoutOrganizationInput> | Prisma.OrgProductPriceCreateWithoutOrganizationInput[] | Prisma.OrgProductPriceUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.OrgProductPriceCreateOrConnectWithoutOrganizationInput | Prisma.OrgProductPriceCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.OrgProductPriceUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.OrgProductPriceUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.OrgProductPriceCreateManyOrganizationInputEnvelope
  set?: Prisma.OrgProductPriceWhereUniqueInput | Prisma.OrgProductPriceWhereUniqueInput[]
  disconnect?: Prisma.OrgProductPriceWhereUniqueInput | Prisma.OrgProductPriceWhereUniqueInput[]
  delete?: Prisma.OrgProductPriceWhereUniqueInput | Prisma.OrgProductPriceWhereUniqueInput[]
  connect?: Prisma.OrgProductPriceWhereUniqueInput | Prisma.OrgProductPriceWhereUniqueInput[]
  update?: Prisma.OrgProductPriceUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.OrgProductPriceUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.OrgProductPriceUpdateManyWithWhereWithoutOrganizationInput | Prisma.OrgProductPriceUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.OrgProductPriceScalarWhereInput | Prisma.OrgProductPriceScalarWhereInput[]
}

export type OrgProductPriceUncheckedUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.OrgProductPriceCreateWithoutOrganizationInput, Prisma.OrgProductPriceUncheckedCreateWithoutOrganizationInput> | Prisma.OrgProductPriceCreateWithoutOrganizationInput[] | Prisma.OrgProductPriceUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.OrgProductPriceCreateOrConnectWithoutOrganizationInput | Prisma.OrgProductPriceCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.OrgProductPriceUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.OrgProductPriceUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.OrgProductPriceCreateManyOrganizationInputEnvelope
  set?: Prisma.OrgProductPriceWhereUniqueInput | Prisma.OrgProductPriceWhereUniqueInput[]
  disconnect?: Prisma.OrgProductPriceWhereUniqueInput | Prisma.OrgProductPriceWhereUniqueInput[]
  delete?: Prisma.OrgProductPriceWhereUniqueInput | Prisma.OrgProductPriceWhereUniqueInput[]
  connect?: Prisma.OrgProductPriceWhereUniqueInput | Prisma.OrgProductPriceWhereUniqueInput[]
  update?: Prisma.OrgProductPriceUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.OrgProductPriceUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.OrgProductPriceUpdateManyWithWhereWithoutOrganizationInput | Prisma.OrgProductPriceUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.OrgProductPriceScalarWhereInput | Prisma.OrgProductPriceScalarWhereInput[]
}

export type OrgProductPriceCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.OrgProductPriceCreateWithoutProductInput, Prisma.OrgProductPriceUncheckedCreateWithoutProductInput> | Prisma.OrgProductPriceCreateWithoutProductInput[] | Prisma.OrgProductPriceUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.OrgProductPriceCreateOrConnectWithoutProductInput | Prisma.OrgProductPriceCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.OrgProductPriceCreateManyProductInputEnvelope
  connect?: Prisma.OrgProductPriceWhereUniqueInput | Prisma.OrgProductPriceWhereUniqueInput[]
}

export type OrgProductPriceUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.OrgProductPriceCreateWithoutProductInput, Prisma.OrgProductPriceUncheckedCreateWithoutProductInput> | Prisma.OrgProductPriceCreateWithoutProductInput[] | Prisma.OrgProductPriceUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.OrgProductPriceCreateOrConnectWithoutProductInput | Prisma.OrgProductPriceCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.OrgProductPriceCreateManyProductInputEnvelope
  connect?: Prisma.OrgProductPriceWhereUniqueInput | Prisma.OrgProductPriceWhereUniqueInput[]
}

export type OrgProductPriceUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.OrgProductPriceCreateWithoutProductInput, Prisma.OrgProductPriceUncheckedCreateWithoutProductInput> | Prisma.OrgProductPriceCreateWithoutProductInput[] | Prisma.OrgProductPriceUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.OrgProductPriceCreateOrConnectWithoutProductInput | Prisma.OrgProductPriceCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.OrgProductPriceUpsertWithWhereUniqueWithoutProductInput | Prisma.OrgProductPriceUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.OrgProductPriceCreateManyProductInputEnvelope
  set?: Prisma.OrgProductPriceWhereUniqueInput | Prisma.OrgProductPriceWhereUniqueInput[]
  disconnect?: Prisma.OrgProductPriceWhereUniqueInput | Prisma.OrgProductPriceWhereUniqueInput[]
  delete?: Prisma.OrgProductPriceWhereUniqueInput | Prisma.OrgProductPriceWhereUniqueInput[]
  connect?: Prisma.OrgProductPriceWhereUniqueInput | Prisma.OrgProductPriceWhereUniqueInput[]
  update?: Prisma.OrgProductPriceUpdateWithWhereUniqueWithoutProductInput | Prisma.OrgProductPriceUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.OrgProductPriceUpdateManyWithWhereWithoutProductInput | Prisma.OrgProductPriceUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.OrgProductPriceScalarWhereInput | Prisma.OrgProductPriceScalarWhereInput[]
}

export type OrgProductPriceUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.OrgProductPriceCreateWithoutProductInput, Prisma.OrgProductPriceUncheckedCreateWithoutProductInput> | Prisma.OrgProductPriceCreateWithoutProductInput[] | Prisma.OrgProductPriceUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.OrgProductPriceCreateOrConnectWithoutProductInput | Prisma.OrgProductPriceCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.OrgProductPriceUpsertWithWhereUniqueWithoutProductInput | Prisma.OrgProductPriceUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.OrgProductPriceCreateManyProductInputEnvelope
  set?: Prisma.OrgProductPriceWhereUniqueInput | Prisma.OrgProductPriceWhereUniqueInput[]
  disconnect?: Prisma.OrgProductPriceWhereUniqueInput | Prisma.OrgProductPriceWhereUniqueInput[]
  delete?: Prisma.OrgProductPriceWhereUniqueInput | Prisma.OrgProductPriceWhereUniqueInput[]
  connect?: Prisma.OrgProductPriceWhereUniqueInput | Prisma.OrgProductPriceWhereUniqueInput[]
  update?: Prisma.OrgProductPriceUpdateWithWhereUniqueWithoutProductInput | Prisma.OrgProductPriceUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.OrgProductPriceUpdateManyWithWhereWithoutProductInput | Prisma.OrgProductPriceUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.OrgProductPriceScalarWhereInput | Prisma.OrgProductPriceScalarWhereInput[]
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type OrgProductPriceCreateWithoutOrganizationInput = {
  id?: string
  netPurchasePrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  product: Prisma.ProductCreateNestedOneWithoutOrgPricesInput
}

export type OrgProductPriceUncheckedCreateWithoutOrganizationInput = {
  id?: string
  productId: string
  netPurchasePrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrgProductPriceCreateOrConnectWithoutOrganizationInput = {
  where: Prisma.OrgProductPriceWhereUniqueInput
  create: Prisma.XOR<Prisma.OrgProductPriceCreateWithoutOrganizationInput, Prisma.OrgProductPriceUncheckedCreateWithoutOrganizationInput>
}

export type OrgProductPriceCreateManyOrganizationInputEnvelope = {
  data: Prisma.OrgProductPriceCreateManyOrganizationInput | Prisma.OrgProductPriceCreateManyOrganizationInput[]
  skipDuplicates?: boolean
}

export type OrgProductPriceUpsertWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.OrgProductPriceWhereUniqueInput
  update: Prisma.XOR<Prisma.OrgProductPriceUpdateWithoutOrganizationInput, Prisma.OrgProductPriceUncheckedUpdateWithoutOrganizationInput>
  create: Prisma.XOR<Prisma.OrgProductPriceCreateWithoutOrganizationInput, Prisma.OrgProductPriceUncheckedCreateWithoutOrganizationInput>
}

export type OrgProductPriceUpdateWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.OrgProductPriceWhereUniqueInput
  data: Prisma.XOR<Prisma.OrgProductPriceUpdateWithoutOrganizationInput, Prisma.OrgProductPriceUncheckedUpdateWithoutOrganizationInput>
}

export type OrgProductPriceUpdateManyWithWhereWithoutOrganizationInput = {
  where: Prisma.OrgProductPriceScalarWhereInput
  data: Prisma.XOR<Prisma.OrgProductPriceUpdateManyMutationInput, Prisma.OrgProductPriceUncheckedUpdateManyWithoutOrganizationInput>
}

export type OrgProductPriceScalarWhereInput = {
  AND?: Prisma.OrgProductPriceScalarWhereInput | Prisma.OrgProductPriceScalarWhereInput[]
  OR?: Prisma.OrgProductPriceScalarWhereInput[]
  NOT?: Prisma.OrgProductPriceScalarWhereInput | Prisma.OrgProductPriceScalarWhereInput[]
  id?: Prisma.StringFilter<"OrgProductPrice"> | string
  organizationId?: Prisma.StringFilter<"OrgProductPrice"> | string
  productId?: Prisma.StringFilter<"OrgProductPrice"> | string
  netPurchasePrice?: Prisma.DecimalFilter<"OrgProductPrice"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"OrgProductPrice"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OrgProductPrice"> | Date | string
}

export type OrgProductPriceCreateWithoutProductInput = {
  id?: string
  netPurchasePrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutProductPricesInput
}

export type OrgProductPriceUncheckedCreateWithoutProductInput = {
  id?: string
  organizationId: string
  netPurchasePrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrgProductPriceCreateOrConnectWithoutProductInput = {
  where: Prisma.OrgProductPriceWhereUniqueInput
  create: Prisma.XOR<Prisma.OrgProductPriceCreateWithoutProductInput, Prisma.OrgProductPriceUncheckedCreateWithoutProductInput>
}

export type OrgProductPriceCreateManyProductInputEnvelope = {
  data: Prisma.OrgProductPriceCreateManyProductInput | Prisma.OrgProductPriceCreateManyProductInput[]
  skipDuplicates?: boolean
}

export type OrgProductPriceUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.OrgProductPriceWhereUniqueInput
  update: Prisma.XOR<Prisma.OrgProductPriceUpdateWithoutProductInput, Prisma.OrgProductPriceUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.OrgProductPriceCreateWithoutProductInput, Prisma.OrgProductPriceUncheckedCreateWithoutProductInput>
}

export type OrgProductPriceUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.OrgProductPriceWhereUniqueInput
  data: Prisma.XOR<Prisma.OrgProductPriceUpdateWithoutProductInput, Prisma.OrgProductPriceUncheckedUpdateWithoutProductInput>
}

export type OrgProductPriceUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.OrgProductPriceScalarWhereInput
  data: Prisma.XOR<Prisma.OrgProductPriceUpdateManyMutationInput, Prisma.OrgProductPriceUncheckedUpdateManyWithoutProductInput>
}

export type OrgProductPriceCreateManyOrganizationInput = {
  id?: string
  productId: string
  netPurchasePrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrgProductPriceUpdateWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  netPurchasePrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneRequiredWithoutOrgPricesNestedInput
}

export type OrgProductPriceUncheckedUpdateWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  netPurchasePrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrgProductPriceUncheckedUpdateManyWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  netPurchasePrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrgProductPriceCreateManyProductInput = {
  id?: string
  organizationId: string
  netPurchasePrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrgProductPriceUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  netPurchasePrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutProductPricesNestedInput
}

export type OrgProductPriceUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  netPurchasePrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrgProductPriceUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  netPurchasePrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type OrgProductPriceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  organizationId?: boolean
  productId?: boolean
  netPurchasePrice?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["orgProductPrice"]>

export type OrgProductPriceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  organizationId?: boolean
  productId?: boolean
  netPurchasePrice?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["orgProductPrice"]>

export type OrgProductPriceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  organizationId?: boolean
  productId?: boolean
  netPurchasePrice?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["orgProductPrice"]>

export type OrgProductPriceSelectScalar = {
  id?: boolean
  organizationId?: boolean
  productId?: boolean
  netPurchasePrice?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type OrgProductPriceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "organizationId" | "productId" | "netPurchasePrice" | "createdAt" | "updatedAt", ExtArgs["result"]["orgProductPrice"]>
export type OrgProductPriceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type OrgProductPriceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type OrgProductPriceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $OrgProductPricePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OrgProductPrice"
  objects: {
    organization: Prisma.$OrganizationPayload<ExtArgs>
    product: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    organizationId: string
    productId: string
    netPurchasePrice: runtime.Decimal
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["orgProductPrice"]>
  composites: {}
}

export type OrgProductPriceGetPayload<S extends boolean | null | undefined | OrgProductPriceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OrgProductPricePayload, S>

export type OrgProductPriceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OrgProductPriceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OrgProductPriceCountAggregateInputType | true
  }

export interface OrgProductPriceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OrgProductPrice'], meta: { name: 'OrgProductPrice' } }
  /**
   * Find zero or one OrgProductPrice that matches the filter.
   * @param {OrgProductPriceFindUniqueArgs} args - Arguments to find a OrgProductPrice
   * @example
   * // Get one OrgProductPrice
   * const orgProductPrice = await prisma.orgProductPrice.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OrgProductPriceFindUniqueArgs>(args: Prisma.SelectSubset<T, OrgProductPriceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OrgProductPriceClient<runtime.Types.Result.GetResult<Prisma.$OrgProductPricePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OrgProductPrice that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OrgProductPriceFindUniqueOrThrowArgs} args - Arguments to find a OrgProductPrice
   * @example
   * // Get one OrgProductPrice
   * const orgProductPrice = await prisma.orgProductPrice.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OrgProductPriceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OrgProductPriceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrgProductPriceClient<runtime.Types.Result.GetResult<Prisma.$OrgProductPricePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrgProductPrice that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgProductPriceFindFirstArgs} args - Arguments to find a OrgProductPrice
   * @example
   * // Get one OrgProductPrice
   * const orgProductPrice = await prisma.orgProductPrice.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OrgProductPriceFindFirstArgs>(args?: Prisma.SelectSubset<T, OrgProductPriceFindFirstArgs<ExtArgs>>): Prisma.Prisma__OrgProductPriceClient<runtime.Types.Result.GetResult<Prisma.$OrgProductPricePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrgProductPrice that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgProductPriceFindFirstOrThrowArgs} args - Arguments to find a OrgProductPrice
   * @example
   * // Get one OrgProductPrice
   * const orgProductPrice = await prisma.orgProductPrice.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OrgProductPriceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OrgProductPriceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrgProductPriceClient<runtime.Types.Result.GetResult<Prisma.$OrgProductPricePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OrgProductPrices that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgProductPriceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OrgProductPrices
   * const orgProductPrices = await prisma.orgProductPrice.findMany()
   * 
   * // Get first 10 OrgProductPrices
   * const orgProductPrices = await prisma.orgProductPrice.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const orgProductPriceWithIdOnly = await prisma.orgProductPrice.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends OrgProductPriceFindManyArgs>(args?: Prisma.SelectSubset<T, OrgProductPriceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrgProductPricePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OrgProductPrice.
   * @param {OrgProductPriceCreateArgs} args - Arguments to create a OrgProductPrice.
   * @example
   * // Create one OrgProductPrice
   * const OrgProductPrice = await prisma.orgProductPrice.create({
   *   data: {
   *     // ... data to create a OrgProductPrice
   *   }
   * })
   * 
   */
  create<T extends OrgProductPriceCreateArgs>(args: Prisma.SelectSubset<T, OrgProductPriceCreateArgs<ExtArgs>>): Prisma.Prisma__OrgProductPriceClient<runtime.Types.Result.GetResult<Prisma.$OrgProductPricePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OrgProductPrices.
   * @param {OrgProductPriceCreateManyArgs} args - Arguments to create many OrgProductPrices.
   * @example
   * // Create many OrgProductPrices
   * const orgProductPrice = await prisma.orgProductPrice.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends OrgProductPriceCreateManyArgs>(args?: Prisma.SelectSubset<T, OrgProductPriceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many OrgProductPrices and returns the data saved in the database.
   * @param {OrgProductPriceCreateManyAndReturnArgs} args - Arguments to create many OrgProductPrices.
   * @example
   * // Create many OrgProductPrices
   * const orgProductPrice = await prisma.orgProductPrice.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many OrgProductPrices and only return the `id`
   * const orgProductPriceWithIdOnly = await prisma.orgProductPrice.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends OrgProductPriceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, OrgProductPriceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrgProductPricePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a OrgProductPrice.
   * @param {OrgProductPriceDeleteArgs} args - Arguments to delete one OrgProductPrice.
   * @example
   * // Delete one OrgProductPrice
   * const OrgProductPrice = await prisma.orgProductPrice.delete({
   *   where: {
   *     // ... filter to delete one OrgProductPrice
   *   }
   * })
   * 
   */
  delete<T extends OrgProductPriceDeleteArgs>(args: Prisma.SelectSubset<T, OrgProductPriceDeleteArgs<ExtArgs>>): Prisma.Prisma__OrgProductPriceClient<runtime.Types.Result.GetResult<Prisma.$OrgProductPricePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OrgProductPrice.
   * @param {OrgProductPriceUpdateArgs} args - Arguments to update one OrgProductPrice.
   * @example
   * // Update one OrgProductPrice
   * const orgProductPrice = await prisma.orgProductPrice.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends OrgProductPriceUpdateArgs>(args: Prisma.SelectSubset<T, OrgProductPriceUpdateArgs<ExtArgs>>): Prisma.Prisma__OrgProductPriceClient<runtime.Types.Result.GetResult<Prisma.$OrgProductPricePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OrgProductPrices.
   * @param {OrgProductPriceDeleteManyArgs} args - Arguments to filter OrgProductPrices to delete.
   * @example
   * // Delete a few OrgProductPrices
   * const { count } = await prisma.orgProductPrice.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends OrgProductPriceDeleteManyArgs>(args?: Prisma.SelectSubset<T, OrgProductPriceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OrgProductPrices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgProductPriceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OrgProductPrices
   * const orgProductPrice = await prisma.orgProductPrice.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends OrgProductPriceUpdateManyArgs>(args: Prisma.SelectSubset<T, OrgProductPriceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OrgProductPrices and returns the data updated in the database.
   * @param {OrgProductPriceUpdateManyAndReturnArgs} args - Arguments to update many OrgProductPrices.
   * @example
   * // Update many OrgProductPrices
   * const orgProductPrice = await prisma.orgProductPrice.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more OrgProductPrices and only return the `id`
   * const orgProductPriceWithIdOnly = await prisma.orgProductPrice.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends OrgProductPriceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, OrgProductPriceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrgProductPricePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one OrgProductPrice.
   * @param {OrgProductPriceUpsertArgs} args - Arguments to update or create a OrgProductPrice.
   * @example
   * // Update or create a OrgProductPrice
   * const orgProductPrice = await prisma.orgProductPrice.upsert({
   *   create: {
   *     // ... data to create a OrgProductPrice
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OrgProductPrice we want to update
   *   }
   * })
   */
  upsert<T extends OrgProductPriceUpsertArgs>(args: Prisma.SelectSubset<T, OrgProductPriceUpsertArgs<ExtArgs>>): Prisma.Prisma__OrgProductPriceClient<runtime.Types.Result.GetResult<Prisma.$OrgProductPricePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OrgProductPrices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgProductPriceCountArgs} args - Arguments to filter OrgProductPrices to count.
   * @example
   * // Count the number of OrgProductPrices
   * const count = await prisma.orgProductPrice.count({
   *   where: {
   *     // ... the filter for the OrgProductPrices we want to count
   *   }
   * })
  **/
  count<T extends OrgProductPriceCountArgs>(
    args?: Prisma.Subset<T, OrgProductPriceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OrgProductPriceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OrgProductPrice.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgProductPriceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OrgProductPriceAggregateArgs>(args: Prisma.Subset<T, OrgProductPriceAggregateArgs>): Prisma.PrismaPromise<GetOrgProductPriceAggregateType<T>>

  /**
   * Group by OrgProductPrice.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgProductPriceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends OrgProductPriceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OrgProductPriceGroupByArgs['orderBy'] }
      : { orderBy?: OrgProductPriceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OrgProductPriceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrgProductPriceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OrgProductPrice model
 */
readonly fields: OrgProductPriceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OrgProductPrice.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OrgProductPriceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  organization<T extends Prisma.OrganizationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrganizationDefaultArgs<ExtArgs>>): Prisma.Prisma__OrganizationClient<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OrgProductPrice model
 */
export interface OrgProductPriceFieldRefs {
  readonly id: Prisma.FieldRef<"OrgProductPrice", 'String'>
  readonly organizationId: Prisma.FieldRef<"OrgProductPrice", 'String'>
  readonly productId: Prisma.FieldRef<"OrgProductPrice", 'String'>
  readonly netPurchasePrice: Prisma.FieldRef<"OrgProductPrice", 'Decimal'>
  readonly createdAt: Prisma.FieldRef<"OrgProductPrice", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"OrgProductPrice", 'DateTime'>
}
    

// Custom InputTypes
/**
 * OrgProductPrice findUnique
 */
export type OrgProductPriceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProductPrice
   */
  select?: Prisma.OrgProductPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProductPrice
   */
  omit?: Prisma.OrgProductPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProductPriceInclude<ExtArgs> | null
  /**
   * Filter, which OrgProductPrice to fetch.
   */
  where: Prisma.OrgProductPriceWhereUniqueInput
}

/**
 * OrgProductPrice findUniqueOrThrow
 */
export type OrgProductPriceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProductPrice
   */
  select?: Prisma.OrgProductPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProductPrice
   */
  omit?: Prisma.OrgProductPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProductPriceInclude<ExtArgs> | null
  /**
   * Filter, which OrgProductPrice to fetch.
   */
  where: Prisma.OrgProductPriceWhereUniqueInput
}

/**
 * OrgProductPrice findFirst
 */
export type OrgProductPriceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProductPrice
   */
  select?: Prisma.OrgProductPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProductPrice
   */
  omit?: Prisma.OrgProductPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProductPriceInclude<ExtArgs> | null
  /**
   * Filter, which OrgProductPrice to fetch.
   */
  where?: Prisma.OrgProductPriceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrgProductPrices to fetch.
   */
  orderBy?: Prisma.OrgProductPriceOrderByWithRelationInput | Prisma.OrgProductPriceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OrgProductPrices.
   */
  cursor?: Prisma.OrgProductPriceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrgProductPrices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrgProductPrices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrgProductPrices.
   */
  distinct?: Prisma.OrgProductPriceScalarFieldEnum | Prisma.OrgProductPriceScalarFieldEnum[]
}

/**
 * OrgProductPrice findFirstOrThrow
 */
export type OrgProductPriceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProductPrice
   */
  select?: Prisma.OrgProductPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProductPrice
   */
  omit?: Prisma.OrgProductPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProductPriceInclude<ExtArgs> | null
  /**
   * Filter, which OrgProductPrice to fetch.
   */
  where?: Prisma.OrgProductPriceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrgProductPrices to fetch.
   */
  orderBy?: Prisma.OrgProductPriceOrderByWithRelationInput | Prisma.OrgProductPriceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OrgProductPrices.
   */
  cursor?: Prisma.OrgProductPriceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrgProductPrices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrgProductPrices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrgProductPrices.
   */
  distinct?: Prisma.OrgProductPriceScalarFieldEnum | Prisma.OrgProductPriceScalarFieldEnum[]
}

/**
 * OrgProductPrice findMany
 */
export type OrgProductPriceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProductPrice
   */
  select?: Prisma.OrgProductPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProductPrice
   */
  omit?: Prisma.OrgProductPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProductPriceInclude<ExtArgs> | null
  /**
   * Filter, which OrgProductPrices to fetch.
   */
  where?: Prisma.OrgProductPriceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrgProductPrices to fetch.
   */
  orderBy?: Prisma.OrgProductPriceOrderByWithRelationInput | Prisma.OrgProductPriceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing OrgProductPrices.
   */
  cursor?: Prisma.OrgProductPriceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrgProductPrices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrgProductPrices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrgProductPrices.
   */
  distinct?: Prisma.OrgProductPriceScalarFieldEnum | Prisma.OrgProductPriceScalarFieldEnum[]
}

/**
 * OrgProductPrice create
 */
export type OrgProductPriceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProductPrice
   */
  select?: Prisma.OrgProductPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProductPrice
   */
  omit?: Prisma.OrgProductPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProductPriceInclude<ExtArgs> | null
  /**
   * The data needed to create a OrgProductPrice.
   */
  data: Prisma.XOR<Prisma.OrgProductPriceCreateInput, Prisma.OrgProductPriceUncheckedCreateInput>
}

/**
 * OrgProductPrice createMany
 */
export type OrgProductPriceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OrgProductPrices.
   */
  data: Prisma.OrgProductPriceCreateManyInput | Prisma.OrgProductPriceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OrgProductPrice createManyAndReturn
 */
export type OrgProductPriceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProductPrice
   */
  select?: Prisma.OrgProductPriceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProductPrice
   */
  omit?: Prisma.OrgProductPriceOmit<ExtArgs> | null
  /**
   * The data used to create many OrgProductPrices.
   */
  data: Prisma.OrgProductPriceCreateManyInput | Prisma.OrgProductPriceCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProductPriceIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * OrgProductPrice update
 */
export type OrgProductPriceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProductPrice
   */
  select?: Prisma.OrgProductPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProductPrice
   */
  omit?: Prisma.OrgProductPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProductPriceInclude<ExtArgs> | null
  /**
   * The data needed to update a OrgProductPrice.
   */
  data: Prisma.XOR<Prisma.OrgProductPriceUpdateInput, Prisma.OrgProductPriceUncheckedUpdateInput>
  /**
   * Choose, which OrgProductPrice to update.
   */
  where: Prisma.OrgProductPriceWhereUniqueInput
}

/**
 * OrgProductPrice updateMany
 */
export type OrgProductPriceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OrgProductPrices.
   */
  data: Prisma.XOR<Prisma.OrgProductPriceUpdateManyMutationInput, Prisma.OrgProductPriceUncheckedUpdateManyInput>
  /**
   * Filter which OrgProductPrices to update
   */
  where?: Prisma.OrgProductPriceWhereInput
  /**
   * Limit how many OrgProductPrices to update.
   */
  limit?: number
}

/**
 * OrgProductPrice updateManyAndReturn
 */
export type OrgProductPriceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProductPrice
   */
  select?: Prisma.OrgProductPriceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProductPrice
   */
  omit?: Prisma.OrgProductPriceOmit<ExtArgs> | null
  /**
   * The data used to update OrgProductPrices.
   */
  data: Prisma.XOR<Prisma.OrgProductPriceUpdateManyMutationInput, Prisma.OrgProductPriceUncheckedUpdateManyInput>
  /**
   * Filter which OrgProductPrices to update
   */
  where?: Prisma.OrgProductPriceWhereInput
  /**
   * Limit how many OrgProductPrices to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProductPriceIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * OrgProductPrice upsert
 */
export type OrgProductPriceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProductPrice
   */
  select?: Prisma.OrgProductPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProductPrice
   */
  omit?: Prisma.OrgProductPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProductPriceInclude<ExtArgs> | null
  /**
   * The filter to search for the OrgProductPrice to update in case it exists.
   */
  where: Prisma.OrgProductPriceWhereUniqueInput
  /**
   * In case the OrgProductPrice found by the `where` argument doesn't exist, create a new OrgProductPrice with this data.
   */
  create: Prisma.XOR<Prisma.OrgProductPriceCreateInput, Prisma.OrgProductPriceUncheckedCreateInput>
  /**
   * In case the OrgProductPrice was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OrgProductPriceUpdateInput, Prisma.OrgProductPriceUncheckedUpdateInput>
}

/**
 * OrgProductPrice delete
 */
export type OrgProductPriceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProductPrice
   */
  select?: Prisma.OrgProductPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProductPrice
   */
  omit?: Prisma.OrgProductPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProductPriceInclude<ExtArgs> | null
  /**
   * Filter which OrgProductPrice to delete.
   */
  where: Prisma.OrgProductPriceWhereUniqueInput
}

/**
 * OrgProductPrice deleteMany
 */
export type OrgProductPriceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OrgProductPrices to delete
   */
  where?: Prisma.OrgProductPriceWhereInput
  /**
   * Limit how many OrgProductPrices to delete.
   */
  limit?: number
}

/**
 * OrgProductPrice without action
 */
export type OrgProductPriceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProductPrice
   */
  select?: Prisma.OrgProductPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProductPrice
   */
  omit?: Prisma.OrgProductPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProductPriceInclude<ExtArgs> | null
}
