
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProductionCheckTick` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model ProductionCheckTick
 * 
 */
export type ProductionCheckTickModel = runtime.Types.Result.DefaultSelection<Prisma.$ProductionCheckTickPayload>

export type AggregateProductionCheckTick = {
  _count: ProductionCheckTickCountAggregateOutputType | null
  _min: ProductionCheckTickMinAggregateOutputType | null
  _max: ProductionCheckTickMaxAggregateOutputType | null
}

export type ProductionCheckTickMinAggregateOutputType = {
  id: string | null
  checkId: string | null
  assetId: string | null
  userId: string | null
  via: string | null
  unexpected: boolean | null
  createdAt: Date | null
}

export type ProductionCheckTickMaxAggregateOutputType = {
  id: string | null
  checkId: string | null
  assetId: string | null
  userId: string | null
  via: string | null
  unexpected: boolean | null
  createdAt: Date | null
}

export type ProductionCheckTickCountAggregateOutputType = {
  id: number
  checkId: number
  assetId: number
  userId: number
  via: number
  unexpected: number
  createdAt: number
  _all: number
}


export type ProductionCheckTickMinAggregateInputType = {
  id?: true
  checkId?: true
  assetId?: true
  userId?: true
  via?: true
  unexpected?: true
  createdAt?: true
}

export type ProductionCheckTickMaxAggregateInputType = {
  id?: true
  checkId?: true
  assetId?: true
  userId?: true
  via?: true
  unexpected?: true
  createdAt?: true
}

export type ProductionCheckTickCountAggregateInputType = {
  id?: true
  checkId?: true
  assetId?: true
  userId?: true
  via?: true
  unexpected?: true
  createdAt?: true
  _all?: true
}

export type ProductionCheckTickAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductionCheckTick to aggregate.
   */
  where?: Prisma.ProductionCheckTickWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductionCheckTicks to fetch.
   */
  orderBy?: Prisma.ProductionCheckTickOrderByWithRelationInput | Prisma.ProductionCheckTickOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProductionCheckTickWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductionCheckTicks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductionCheckTicks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProductionCheckTicks
  **/
  _count?: true | ProductionCheckTickCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProductionCheckTickMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProductionCheckTickMaxAggregateInputType
}

export type GetProductionCheckTickAggregateType<T extends ProductionCheckTickAggregateArgs> = {
      [P in keyof T & keyof AggregateProductionCheckTick]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProductionCheckTick[P]>
    : Prisma.GetScalarType<T[P], AggregateProductionCheckTick[P]>
}




export type ProductionCheckTickGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductionCheckTickWhereInput
  orderBy?: Prisma.ProductionCheckTickOrderByWithAggregationInput | Prisma.ProductionCheckTickOrderByWithAggregationInput[]
  by: Prisma.ProductionCheckTickScalarFieldEnum[] | Prisma.ProductionCheckTickScalarFieldEnum
  having?: Prisma.ProductionCheckTickScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProductionCheckTickCountAggregateInputType | true
  _min?: ProductionCheckTickMinAggregateInputType
  _max?: ProductionCheckTickMaxAggregateInputType
}

export type ProductionCheckTickGroupByOutputType = {
  id: string
  checkId: string
  assetId: string
  userId: string | null
  via: string
  unexpected: boolean
  createdAt: Date
  _count: ProductionCheckTickCountAggregateOutputType | null
  _min: ProductionCheckTickMinAggregateOutputType | null
  _max: ProductionCheckTickMaxAggregateOutputType | null
}

export type GetProductionCheckTickGroupByPayload<T extends ProductionCheckTickGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProductionCheckTickGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProductionCheckTickGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProductionCheckTickGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProductionCheckTickGroupByOutputType[P]>
      }
    >
  >



export type ProductionCheckTickWhereInput = {
  AND?: Prisma.ProductionCheckTickWhereInput | Prisma.ProductionCheckTickWhereInput[]
  OR?: Prisma.ProductionCheckTickWhereInput[]
  NOT?: Prisma.ProductionCheckTickWhereInput | Prisma.ProductionCheckTickWhereInput[]
  id?: Prisma.StringFilter<"ProductionCheckTick"> | string
  checkId?: Prisma.StringFilter<"ProductionCheckTick"> | string
  assetId?: Prisma.StringFilter<"ProductionCheckTick"> | string
  userId?: Prisma.StringNullableFilter<"ProductionCheckTick"> | string | null
  via?: Prisma.StringFilter<"ProductionCheckTick"> | string
  unexpected?: Prisma.BoolFilter<"ProductionCheckTick"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ProductionCheckTick"> | Date | string
  check?: Prisma.XOR<Prisma.ProductionCheckScalarRelationFilter, Prisma.ProductionCheckWhereInput>
  asset?: Prisma.XOR<Prisma.AssetScalarRelationFilter, Prisma.AssetWhereInput>
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type ProductionCheckTickOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  checkId?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  via?: Prisma.SortOrder
  unexpected?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  check?: Prisma.ProductionCheckOrderByWithRelationInput
  asset?: Prisma.AssetOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type ProductionCheckTickWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  checkId_assetId?: Prisma.ProductionCheckTickCheckIdAssetIdCompoundUniqueInput
  AND?: Prisma.ProductionCheckTickWhereInput | Prisma.ProductionCheckTickWhereInput[]
  OR?: Prisma.ProductionCheckTickWhereInput[]
  NOT?: Prisma.ProductionCheckTickWhereInput | Prisma.ProductionCheckTickWhereInput[]
  checkId?: Prisma.StringFilter<"ProductionCheckTick"> | string
  assetId?: Prisma.StringFilter<"ProductionCheckTick"> | string
  userId?: Prisma.StringNullableFilter<"ProductionCheckTick"> | string | null
  via?: Prisma.StringFilter<"ProductionCheckTick"> | string
  unexpected?: Prisma.BoolFilter<"ProductionCheckTick"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ProductionCheckTick"> | Date | string
  check?: Prisma.XOR<Prisma.ProductionCheckScalarRelationFilter, Prisma.ProductionCheckWhereInput>
  asset?: Prisma.XOR<Prisma.AssetScalarRelationFilter, Prisma.AssetWhereInput>
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id" | "checkId_assetId">

export type ProductionCheckTickOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  checkId?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  via?: Prisma.SortOrder
  unexpected?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ProductionCheckTickCountOrderByAggregateInput
  _max?: Prisma.ProductionCheckTickMaxOrderByAggregateInput
  _min?: Prisma.ProductionCheckTickMinOrderByAggregateInput
}

export type ProductionCheckTickScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProductionCheckTickScalarWhereWithAggregatesInput | Prisma.ProductionCheckTickScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProductionCheckTickScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProductionCheckTickScalarWhereWithAggregatesInput | Prisma.ProductionCheckTickScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ProductionCheckTick"> | string
  checkId?: Prisma.StringWithAggregatesFilter<"ProductionCheckTick"> | string
  assetId?: Prisma.StringWithAggregatesFilter<"ProductionCheckTick"> | string
  userId?: Prisma.StringNullableWithAggregatesFilter<"ProductionCheckTick"> | string | null
  via?: Prisma.StringWithAggregatesFilter<"ProductionCheckTick"> | string
  unexpected?: Prisma.BoolWithAggregatesFilter<"ProductionCheckTick"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ProductionCheckTick"> | Date | string
}

export type ProductionCheckTickCreateInput = {
  id?: string
  via: string
  unexpected?: boolean
  createdAt?: Date | string
  check: Prisma.ProductionCheckCreateNestedOneWithoutTicksInput
  asset: Prisma.AssetCreateNestedOneWithoutCheckTicksInput
  user?: Prisma.UserCreateNestedOneWithoutCheckTicksInput
}

export type ProductionCheckTickUncheckedCreateInput = {
  id?: string
  checkId: string
  assetId: string
  userId?: string | null
  via: string
  unexpected?: boolean
  createdAt?: Date | string
}

export type ProductionCheckTickUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  via?: Prisma.StringFieldUpdateOperationsInput | string
  unexpected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  check?: Prisma.ProductionCheckUpdateOneRequiredWithoutTicksNestedInput
  asset?: Prisma.AssetUpdateOneRequiredWithoutCheckTicksNestedInput
  user?: Prisma.UserUpdateOneWithoutCheckTicksNestedInput
}

export type ProductionCheckTickUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  checkId?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  via?: Prisma.StringFieldUpdateOperationsInput | string
  unexpected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductionCheckTickCreateManyInput = {
  id?: string
  checkId: string
  assetId: string
  userId?: string | null
  via: string
  unexpected?: boolean
  createdAt?: Date | string
}

export type ProductionCheckTickUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  via?: Prisma.StringFieldUpdateOperationsInput | string
  unexpected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductionCheckTickUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  checkId?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  via?: Prisma.StringFieldUpdateOperationsInput | string
  unexpected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductionCheckTickListRelationFilter = {
  every?: Prisma.ProductionCheckTickWhereInput
  some?: Prisma.ProductionCheckTickWhereInput
  none?: Prisma.ProductionCheckTickWhereInput
}

export type ProductionCheckTickOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProductionCheckTickCheckIdAssetIdCompoundUniqueInput = {
  checkId: string
  assetId: string
}

export type ProductionCheckTickCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  checkId?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  via?: Prisma.SortOrder
  unexpected?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ProductionCheckTickMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  checkId?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  via?: Prisma.SortOrder
  unexpected?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ProductionCheckTickMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  checkId?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  via?: Prisma.SortOrder
  unexpected?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ProductionCheckTickCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckTickCreateWithoutUserInput, Prisma.ProductionCheckTickUncheckedCreateWithoutUserInput> | Prisma.ProductionCheckTickCreateWithoutUserInput[] | Prisma.ProductionCheckTickUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ProductionCheckTickCreateOrConnectWithoutUserInput | Prisma.ProductionCheckTickCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ProductionCheckTickCreateManyUserInputEnvelope
  connect?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
}

export type ProductionCheckTickUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckTickCreateWithoutUserInput, Prisma.ProductionCheckTickUncheckedCreateWithoutUserInput> | Prisma.ProductionCheckTickCreateWithoutUserInput[] | Prisma.ProductionCheckTickUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ProductionCheckTickCreateOrConnectWithoutUserInput | Prisma.ProductionCheckTickCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ProductionCheckTickCreateManyUserInputEnvelope
  connect?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
}

export type ProductionCheckTickUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckTickCreateWithoutUserInput, Prisma.ProductionCheckTickUncheckedCreateWithoutUserInput> | Prisma.ProductionCheckTickCreateWithoutUserInput[] | Prisma.ProductionCheckTickUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ProductionCheckTickCreateOrConnectWithoutUserInput | Prisma.ProductionCheckTickCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ProductionCheckTickUpsertWithWhereUniqueWithoutUserInput | Prisma.ProductionCheckTickUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ProductionCheckTickCreateManyUserInputEnvelope
  set?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  disconnect?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  delete?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  connect?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  update?: Prisma.ProductionCheckTickUpdateWithWhereUniqueWithoutUserInput | Prisma.ProductionCheckTickUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ProductionCheckTickUpdateManyWithWhereWithoutUserInput | Prisma.ProductionCheckTickUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ProductionCheckTickScalarWhereInput | Prisma.ProductionCheckTickScalarWhereInput[]
}

export type ProductionCheckTickUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckTickCreateWithoutUserInput, Prisma.ProductionCheckTickUncheckedCreateWithoutUserInput> | Prisma.ProductionCheckTickCreateWithoutUserInput[] | Prisma.ProductionCheckTickUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ProductionCheckTickCreateOrConnectWithoutUserInput | Prisma.ProductionCheckTickCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ProductionCheckTickUpsertWithWhereUniqueWithoutUserInput | Prisma.ProductionCheckTickUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ProductionCheckTickCreateManyUserInputEnvelope
  set?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  disconnect?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  delete?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  connect?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  update?: Prisma.ProductionCheckTickUpdateWithWhereUniqueWithoutUserInput | Prisma.ProductionCheckTickUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ProductionCheckTickUpdateManyWithWhereWithoutUserInput | Prisma.ProductionCheckTickUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ProductionCheckTickScalarWhereInput | Prisma.ProductionCheckTickScalarWhereInput[]
}

export type ProductionCheckTickCreateNestedManyWithoutAssetInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckTickCreateWithoutAssetInput, Prisma.ProductionCheckTickUncheckedCreateWithoutAssetInput> | Prisma.ProductionCheckTickCreateWithoutAssetInput[] | Prisma.ProductionCheckTickUncheckedCreateWithoutAssetInput[]
  connectOrCreate?: Prisma.ProductionCheckTickCreateOrConnectWithoutAssetInput | Prisma.ProductionCheckTickCreateOrConnectWithoutAssetInput[]
  createMany?: Prisma.ProductionCheckTickCreateManyAssetInputEnvelope
  connect?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
}

export type ProductionCheckTickUncheckedCreateNestedManyWithoutAssetInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckTickCreateWithoutAssetInput, Prisma.ProductionCheckTickUncheckedCreateWithoutAssetInput> | Prisma.ProductionCheckTickCreateWithoutAssetInput[] | Prisma.ProductionCheckTickUncheckedCreateWithoutAssetInput[]
  connectOrCreate?: Prisma.ProductionCheckTickCreateOrConnectWithoutAssetInput | Prisma.ProductionCheckTickCreateOrConnectWithoutAssetInput[]
  createMany?: Prisma.ProductionCheckTickCreateManyAssetInputEnvelope
  connect?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
}

export type ProductionCheckTickUpdateManyWithoutAssetNestedInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckTickCreateWithoutAssetInput, Prisma.ProductionCheckTickUncheckedCreateWithoutAssetInput> | Prisma.ProductionCheckTickCreateWithoutAssetInput[] | Prisma.ProductionCheckTickUncheckedCreateWithoutAssetInput[]
  connectOrCreate?: Prisma.ProductionCheckTickCreateOrConnectWithoutAssetInput | Prisma.ProductionCheckTickCreateOrConnectWithoutAssetInput[]
  upsert?: Prisma.ProductionCheckTickUpsertWithWhereUniqueWithoutAssetInput | Prisma.ProductionCheckTickUpsertWithWhereUniqueWithoutAssetInput[]
  createMany?: Prisma.ProductionCheckTickCreateManyAssetInputEnvelope
  set?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  disconnect?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  delete?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  connect?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  update?: Prisma.ProductionCheckTickUpdateWithWhereUniqueWithoutAssetInput | Prisma.ProductionCheckTickUpdateWithWhereUniqueWithoutAssetInput[]
  updateMany?: Prisma.ProductionCheckTickUpdateManyWithWhereWithoutAssetInput | Prisma.ProductionCheckTickUpdateManyWithWhereWithoutAssetInput[]
  deleteMany?: Prisma.ProductionCheckTickScalarWhereInput | Prisma.ProductionCheckTickScalarWhereInput[]
}

export type ProductionCheckTickUncheckedUpdateManyWithoutAssetNestedInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckTickCreateWithoutAssetInput, Prisma.ProductionCheckTickUncheckedCreateWithoutAssetInput> | Prisma.ProductionCheckTickCreateWithoutAssetInput[] | Prisma.ProductionCheckTickUncheckedCreateWithoutAssetInput[]
  connectOrCreate?: Prisma.ProductionCheckTickCreateOrConnectWithoutAssetInput | Prisma.ProductionCheckTickCreateOrConnectWithoutAssetInput[]
  upsert?: Prisma.ProductionCheckTickUpsertWithWhereUniqueWithoutAssetInput | Prisma.ProductionCheckTickUpsertWithWhereUniqueWithoutAssetInput[]
  createMany?: Prisma.ProductionCheckTickCreateManyAssetInputEnvelope
  set?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  disconnect?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  delete?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  connect?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  update?: Prisma.ProductionCheckTickUpdateWithWhereUniqueWithoutAssetInput | Prisma.ProductionCheckTickUpdateWithWhereUniqueWithoutAssetInput[]
  updateMany?: Prisma.ProductionCheckTickUpdateManyWithWhereWithoutAssetInput | Prisma.ProductionCheckTickUpdateManyWithWhereWithoutAssetInput[]
  deleteMany?: Prisma.ProductionCheckTickScalarWhereInput | Prisma.ProductionCheckTickScalarWhereInput[]
}

export type ProductionCheckTickCreateNestedManyWithoutCheckInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckTickCreateWithoutCheckInput, Prisma.ProductionCheckTickUncheckedCreateWithoutCheckInput> | Prisma.ProductionCheckTickCreateWithoutCheckInput[] | Prisma.ProductionCheckTickUncheckedCreateWithoutCheckInput[]
  connectOrCreate?: Prisma.ProductionCheckTickCreateOrConnectWithoutCheckInput | Prisma.ProductionCheckTickCreateOrConnectWithoutCheckInput[]
  createMany?: Prisma.ProductionCheckTickCreateManyCheckInputEnvelope
  connect?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
}

export type ProductionCheckTickUncheckedCreateNestedManyWithoutCheckInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckTickCreateWithoutCheckInput, Prisma.ProductionCheckTickUncheckedCreateWithoutCheckInput> | Prisma.ProductionCheckTickCreateWithoutCheckInput[] | Prisma.ProductionCheckTickUncheckedCreateWithoutCheckInput[]
  connectOrCreate?: Prisma.ProductionCheckTickCreateOrConnectWithoutCheckInput | Prisma.ProductionCheckTickCreateOrConnectWithoutCheckInput[]
  createMany?: Prisma.ProductionCheckTickCreateManyCheckInputEnvelope
  connect?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
}

export type ProductionCheckTickUpdateManyWithoutCheckNestedInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckTickCreateWithoutCheckInput, Prisma.ProductionCheckTickUncheckedCreateWithoutCheckInput> | Prisma.ProductionCheckTickCreateWithoutCheckInput[] | Prisma.ProductionCheckTickUncheckedCreateWithoutCheckInput[]
  connectOrCreate?: Prisma.ProductionCheckTickCreateOrConnectWithoutCheckInput | Prisma.ProductionCheckTickCreateOrConnectWithoutCheckInput[]
  upsert?: Prisma.ProductionCheckTickUpsertWithWhereUniqueWithoutCheckInput | Prisma.ProductionCheckTickUpsertWithWhereUniqueWithoutCheckInput[]
  createMany?: Prisma.ProductionCheckTickCreateManyCheckInputEnvelope
  set?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  disconnect?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  delete?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  connect?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  update?: Prisma.ProductionCheckTickUpdateWithWhereUniqueWithoutCheckInput | Prisma.ProductionCheckTickUpdateWithWhereUniqueWithoutCheckInput[]
  updateMany?: Prisma.ProductionCheckTickUpdateManyWithWhereWithoutCheckInput | Prisma.ProductionCheckTickUpdateManyWithWhereWithoutCheckInput[]
  deleteMany?: Prisma.ProductionCheckTickScalarWhereInput | Prisma.ProductionCheckTickScalarWhereInput[]
}

export type ProductionCheckTickUncheckedUpdateManyWithoutCheckNestedInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckTickCreateWithoutCheckInput, Prisma.ProductionCheckTickUncheckedCreateWithoutCheckInput> | Prisma.ProductionCheckTickCreateWithoutCheckInput[] | Prisma.ProductionCheckTickUncheckedCreateWithoutCheckInput[]
  connectOrCreate?: Prisma.ProductionCheckTickCreateOrConnectWithoutCheckInput | Prisma.ProductionCheckTickCreateOrConnectWithoutCheckInput[]
  upsert?: Prisma.ProductionCheckTickUpsertWithWhereUniqueWithoutCheckInput | Prisma.ProductionCheckTickUpsertWithWhereUniqueWithoutCheckInput[]
  createMany?: Prisma.ProductionCheckTickCreateManyCheckInputEnvelope
  set?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  disconnect?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  delete?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  connect?: Prisma.ProductionCheckTickWhereUniqueInput | Prisma.ProductionCheckTickWhereUniqueInput[]
  update?: Prisma.ProductionCheckTickUpdateWithWhereUniqueWithoutCheckInput | Prisma.ProductionCheckTickUpdateWithWhereUniqueWithoutCheckInput[]
  updateMany?: Prisma.ProductionCheckTickUpdateManyWithWhereWithoutCheckInput | Prisma.ProductionCheckTickUpdateManyWithWhereWithoutCheckInput[]
  deleteMany?: Prisma.ProductionCheckTickScalarWhereInput | Prisma.ProductionCheckTickScalarWhereInput[]
}

export type ProductionCheckTickCreateWithoutUserInput = {
  id?: string
  via: string
  unexpected?: boolean
  createdAt?: Date | string
  check: Prisma.ProductionCheckCreateNestedOneWithoutTicksInput
  asset: Prisma.AssetCreateNestedOneWithoutCheckTicksInput
}

export type ProductionCheckTickUncheckedCreateWithoutUserInput = {
  id?: string
  checkId: string
  assetId: string
  via: string
  unexpected?: boolean
  createdAt?: Date | string
}

export type ProductionCheckTickCreateOrConnectWithoutUserInput = {
  where: Prisma.ProductionCheckTickWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductionCheckTickCreateWithoutUserInput, Prisma.ProductionCheckTickUncheckedCreateWithoutUserInput>
}

export type ProductionCheckTickCreateManyUserInputEnvelope = {
  data: Prisma.ProductionCheckTickCreateManyUserInput | Prisma.ProductionCheckTickCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ProductionCheckTickUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ProductionCheckTickWhereUniqueInput
  update: Prisma.XOR<Prisma.ProductionCheckTickUpdateWithoutUserInput, Prisma.ProductionCheckTickUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ProductionCheckTickCreateWithoutUserInput, Prisma.ProductionCheckTickUncheckedCreateWithoutUserInput>
}

export type ProductionCheckTickUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ProductionCheckTickWhereUniqueInput
  data: Prisma.XOR<Prisma.ProductionCheckTickUpdateWithoutUserInput, Prisma.ProductionCheckTickUncheckedUpdateWithoutUserInput>
}

export type ProductionCheckTickUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ProductionCheckTickScalarWhereInput
  data: Prisma.XOR<Prisma.ProductionCheckTickUpdateManyMutationInput, Prisma.ProductionCheckTickUncheckedUpdateManyWithoutUserInput>
}

export type ProductionCheckTickScalarWhereInput = {
  AND?: Prisma.ProductionCheckTickScalarWhereInput | Prisma.ProductionCheckTickScalarWhereInput[]
  OR?: Prisma.ProductionCheckTickScalarWhereInput[]
  NOT?: Prisma.ProductionCheckTickScalarWhereInput | Prisma.ProductionCheckTickScalarWhereInput[]
  id?: Prisma.StringFilter<"ProductionCheckTick"> | string
  checkId?: Prisma.StringFilter<"ProductionCheckTick"> | string
  assetId?: Prisma.StringFilter<"ProductionCheckTick"> | string
  userId?: Prisma.StringNullableFilter<"ProductionCheckTick"> | string | null
  via?: Prisma.StringFilter<"ProductionCheckTick"> | string
  unexpected?: Prisma.BoolFilter<"ProductionCheckTick"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ProductionCheckTick"> | Date | string
}

export type ProductionCheckTickCreateWithoutAssetInput = {
  id?: string
  via: string
  unexpected?: boolean
  createdAt?: Date | string
  check: Prisma.ProductionCheckCreateNestedOneWithoutTicksInput
  user?: Prisma.UserCreateNestedOneWithoutCheckTicksInput
}

export type ProductionCheckTickUncheckedCreateWithoutAssetInput = {
  id?: string
  checkId: string
  userId?: string | null
  via: string
  unexpected?: boolean
  createdAt?: Date | string
}

export type ProductionCheckTickCreateOrConnectWithoutAssetInput = {
  where: Prisma.ProductionCheckTickWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductionCheckTickCreateWithoutAssetInput, Prisma.ProductionCheckTickUncheckedCreateWithoutAssetInput>
}

export type ProductionCheckTickCreateManyAssetInputEnvelope = {
  data: Prisma.ProductionCheckTickCreateManyAssetInput | Prisma.ProductionCheckTickCreateManyAssetInput[]
  skipDuplicates?: boolean
}

export type ProductionCheckTickUpsertWithWhereUniqueWithoutAssetInput = {
  where: Prisma.ProductionCheckTickWhereUniqueInput
  update: Prisma.XOR<Prisma.ProductionCheckTickUpdateWithoutAssetInput, Prisma.ProductionCheckTickUncheckedUpdateWithoutAssetInput>
  create: Prisma.XOR<Prisma.ProductionCheckTickCreateWithoutAssetInput, Prisma.ProductionCheckTickUncheckedCreateWithoutAssetInput>
}

export type ProductionCheckTickUpdateWithWhereUniqueWithoutAssetInput = {
  where: Prisma.ProductionCheckTickWhereUniqueInput
  data: Prisma.XOR<Prisma.ProductionCheckTickUpdateWithoutAssetInput, Prisma.ProductionCheckTickUncheckedUpdateWithoutAssetInput>
}

export type ProductionCheckTickUpdateManyWithWhereWithoutAssetInput = {
  where: Prisma.ProductionCheckTickScalarWhereInput
  data: Prisma.XOR<Prisma.ProductionCheckTickUpdateManyMutationInput, Prisma.ProductionCheckTickUncheckedUpdateManyWithoutAssetInput>
}

export type ProductionCheckTickCreateWithoutCheckInput = {
  id?: string
  via: string
  unexpected?: boolean
  createdAt?: Date | string
  asset: Prisma.AssetCreateNestedOneWithoutCheckTicksInput
  user?: Prisma.UserCreateNestedOneWithoutCheckTicksInput
}

export type ProductionCheckTickUncheckedCreateWithoutCheckInput = {
  id?: string
  assetId: string
  userId?: string | null
  via: string
  unexpected?: boolean
  createdAt?: Date | string
}

export type ProductionCheckTickCreateOrConnectWithoutCheckInput = {
  where: Prisma.ProductionCheckTickWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductionCheckTickCreateWithoutCheckInput, Prisma.ProductionCheckTickUncheckedCreateWithoutCheckInput>
}

export type ProductionCheckTickCreateManyCheckInputEnvelope = {
  data: Prisma.ProductionCheckTickCreateManyCheckInput | Prisma.ProductionCheckTickCreateManyCheckInput[]
  skipDuplicates?: boolean
}

export type ProductionCheckTickUpsertWithWhereUniqueWithoutCheckInput = {
  where: Prisma.ProductionCheckTickWhereUniqueInput
  update: Prisma.XOR<Prisma.ProductionCheckTickUpdateWithoutCheckInput, Prisma.ProductionCheckTickUncheckedUpdateWithoutCheckInput>
  create: Prisma.XOR<Prisma.ProductionCheckTickCreateWithoutCheckInput, Prisma.ProductionCheckTickUncheckedCreateWithoutCheckInput>
}

export type ProductionCheckTickUpdateWithWhereUniqueWithoutCheckInput = {
  where: Prisma.ProductionCheckTickWhereUniqueInput
  data: Prisma.XOR<Prisma.ProductionCheckTickUpdateWithoutCheckInput, Prisma.ProductionCheckTickUncheckedUpdateWithoutCheckInput>
}

export type ProductionCheckTickUpdateManyWithWhereWithoutCheckInput = {
  where: Prisma.ProductionCheckTickScalarWhereInput
  data: Prisma.XOR<Prisma.ProductionCheckTickUpdateManyMutationInput, Prisma.ProductionCheckTickUncheckedUpdateManyWithoutCheckInput>
}

export type ProductionCheckTickCreateManyUserInput = {
  id?: string
  checkId: string
  assetId: string
  via: string
  unexpected?: boolean
  createdAt?: Date | string
}

export type ProductionCheckTickUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  via?: Prisma.StringFieldUpdateOperationsInput | string
  unexpected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  check?: Prisma.ProductionCheckUpdateOneRequiredWithoutTicksNestedInput
  asset?: Prisma.AssetUpdateOneRequiredWithoutCheckTicksNestedInput
}

export type ProductionCheckTickUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  checkId?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.StringFieldUpdateOperationsInput | string
  via?: Prisma.StringFieldUpdateOperationsInput | string
  unexpected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductionCheckTickUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  checkId?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.StringFieldUpdateOperationsInput | string
  via?: Prisma.StringFieldUpdateOperationsInput | string
  unexpected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductionCheckTickCreateManyAssetInput = {
  id?: string
  checkId: string
  userId?: string | null
  via: string
  unexpected?: boolean
  createdAt?: Date | string
}

export type ProductionCheckTickUpdateWithoutAssetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  via?: Prisma.StringFieldUpdateOperationsInput | string
  unexpected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  check?: Prisma.ProductionCheckUpdateOneRequiredWithoutTicksNestedInput
  user?: Prisma.UserUpdateOneWithoutCheckTicksNestedInput
}

export type ProductionCheckTickUncheckedUpdateWithoutAssetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  checkId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  via?: Prisma.StringFieldUpdateOperationsInput | string
  unexpected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductionCheckTickUncheckedUpdateManyWithoutAssetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  checkId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  via?: Prisma.StringFieldUpdateOperationsInput | string
  unexpected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductionCheckTickCreateManyCheckInput = {
  id?: string
  assetId: string
  userId?: string | null
  via: string
  unexpected?: boolean
  createdAt?: Date | string
}

export type ProductionCheckTickUpdateWithoutCheckInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  via?: Prisma.StringFieldUpdateOperationsInput | string
  unexpected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  asset?: Prisma.AssetUpdateOneRequiredWithoutCheckTicksNestedInput
  user?: Prisma.UserUpdateOneWithoutCheckTicksNestedInput
}

export type ProductionCheckTickUncheckedUpdateWithoutCheckInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  via?: Prisma.StringFieldUpdateOperationsInput | string
  unexpected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductionCheckTickUncheckedUpdateManyWithoutCheckInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  via?: Prisma.StringFieldUpdateOperationsInput | string
  unexpected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ProductionCheckTickSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  checkId?: boolean
  assetId?: boolean
  userId?: boolean
  via?: boolean
  unexpected?: boolean
  createdAt?: boolean
  check?: boolean | Prisma.ProductionCheckDefaultArgs<ExtArgs>
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
  user?: boolean | Prisma.ProductionCheckTick$userArgs<ExtArgs>
}, ExtArgs["result"]["productionCheckTick"]>

export type ProductionCheckTickSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  checkId?: boolean
  assetId?: boolean
  userId?: boolean
  via?: boolean
  unexpected?: boolean
  createdAt?: boolean
  check?: boolean | Prisma.ProductionCheckDefaultArgs<ExtArgs>
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
  user?: boolean | Prisma.ProductionCheckTick$userArgs<ExtArgs>
}, ExtArgs["result"]["productionCheckTick"]>

export type ProductionCheckTickSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  checkId?: boolean
  assetId?: boolean
  userId?: boolean
  via?: boolean
  unexpected?: boolean
  createdAt?: boolean
  check?: boolean | Prisma.ProductionCheckDefaultArgs<ExtArgs>
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
  user?: boolean | Prisma.ProductionCheckTick$userArgs<ExtArgs>
}, ExtArgs["result"]["productionCheckTick"]>

export type ProductionCheckTickSelectScalar = {
  id?: boolean
  checkId?: boolean
  assetId?: boolean
  userId?: boolean
  via?: boolean
  unexpected?: boolean
  createdAt?: boolean
}

export type ProductionCheckTickOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "checkId" | "assetId" | "userId" | "via" | "unexpected" | "createdAt", ExtArgs["result"]["productionCheckTick"]>
export type ProductionCheckTickInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  check?: boolean | Prisma.ProductionCheckDefaultArgs<ExtArgs>
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
  user?: boolean | Prisma.ProductionCheckTick$userArgs<ExtArgs>
}
export type ProductionCheckTickIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  check?: boolean | Prisma.ProductionCheckDefaultArgs<ExtArgs>
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
  user?: boolean | Prisma.ProductionCheckTick$userArgs<ExtArgs>
}
export type ProductionCheckTickIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  check?: boolean | Prisma.ProductionCheckDefaultArgs<ExtArgs>
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
  user?: boolean | Prisma.ProductionCheckTick$userArgs<ExtArgs>
}

export type $ProductionCheckTickPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProductionCheckTick"
  objects: {
    check: Prisma.$ProductionCheckPayload<ExtArgs>
    asset: Prisma.$AssetPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    checkId: string
    assetId: string
    userId: string | null
    via: string
    unexpected: boolean
    createdAt: Date
  }, ExtArgs["result"]["productionCheckTick"]>
  composites: {}
}

export type ProductionCheckTickGetPayload<S extends boolean | null | undefined | ProductionCheckTickDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProductionCheckTickPayload, S>

export type ProductionCheckTickCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProductionCheckTickFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProductionCheckTickCountAggregateInputType | true
  }

export interface ProductionCheckTickDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProductionCheckTick'], meta: { name: 'ProductionCheckTick' } }
  /**
   * Find zero or one ProductionCheckTick that matches the filter.
   * @param {ProductionCheckTickFindUniqueArgs} args - Arguments to find a ProductionCheckTick
   * @example
   * // Get one ProductionCheckTick
   * const productionCheckTick = await prisma.productionCheckTick.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProductionCheckTickFindUniqueArgs>(args: Prisma.SelectSubset<T, ProductionCheckTickFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProductionCheckTickClient<runtime.Types.Result.GetResult<Prisma.$ProductionCheckTickPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProductionCheckTick that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProductionCheckTickFindUniqueOrThrowArgs} args - Arguments to find a ProductionCheckTick
   * @example
   * // Get one ProductionCheckTick
   * const productionCheckTick = await prisma.productionCheckTick.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProductionCheckTickFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProductionCheckTickFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductionCheckTickClient<runtime.Types.Result.GetResult<Prisma.$ProductionCheckTickPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductionCheckTick that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductionCheckTickFindFirstArgs} args - Arguments to find a ProductionCheckTick
   * @example
   * // Get one ProductionCheckTick
   * const productionCheckTick = await prisma.productionCheckTick.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProductionCheckTickFindFirstArgs>(args?: Prisma.SelectSubset<T, ProductionCheckTickFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProductionCheckTickClient<runtime.Types.Result.GetResult<Prisma.$ProductionCheckTickPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductionCheckTick that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductionCheckTickFindFirstOrThrowArgs} args - Arguments to find a ProductionCheckTick
   * @example
   * // Get one ProductionCheckTick
   * const productionCheckTick = await prisma.productionCheckTick.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProductionCheckTickFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProductionCheckTickFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductionCheckTickClient<runtime.Types.Result.GetResult<Prisma.$ProductionCheckTickPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProductionCheckTicks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductionCheckTickFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProductionCheckTicks
   * const productionCheckTicks = await prisma.productionCheckTick.findMany()
   * 
   * // Get first 10 ProductionCheckTicks
   * const productionCheckTicks = await prisma.productionCheckTick.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const productionCheckTickWithIdOnly = await prisma.productionCheckTick.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProductionCheckTickFindManyArgs>(args?: Prisma.SelectSubset<T, ProductionCheckTickFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductionCheckTickPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProductionCheckTick.
   * @param {ProductionCheckTickCreateArgs} args - Arguments to create a ProductionCheckTick.
   * @example
   * // Create one ProductionCheckTick
   * const ProductionCheckTick = await prisma.productionCheckTick.create({
   *   data: {
   *     // ... data to create a ProductionCheckTick
   *   }
   * })
   * 
   */
  create<T extends ProductionCheckTickCreateArgs>(args: Prisma.SelectSubset<T, ProductionCheckTickCreateArgs<ExtArgs>>): Prisma.Prisma__ProductionCheckTickClient<runtime.Types.Result.GetResult<Prisma.$ProductionCheckTickPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProductionCheckTicks.
   * @param {ProductionCheckTickCreateManyArgs} args - Arguments to create many ProductionCheckTicks.
   * @example
   * // Create many ProductionCheckTicks
   * const productionCheckTick = await prisma.productionCheckTick.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProductionCheckTickCreateManyArgs>(args?: Prisma.SelectSubset<T, ProductionCheckTickCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProductionCheckTicks and returns the data saved in the database.
   * @param {ProductionCheckTickCreateManyAndReturnArgs} args - Arguments to create many ProductionCheckTicks.
   * @example
   * // Create many ProductionCheckTicks
   * const productionCheckTick = await prisma.productionCheckTick.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProductionCheckTicks and only return the `id`
   * const productionCheckTickWithIdOnly = await prisma.productionCheckTick.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProductionCheckTickCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProductionCheckTickCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductionCheckTickPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProductionCheckTick.
   * @param {ProductionCheckTickDeleteArgs} args - Arguments to delete one ProductionCheckTick.
   * @example
   * // Delete one ProductionCheckTick
   * const ProductionCheckTick = await prisma.productionCheckTick.delete({
   *   where: {
   *     // ... filter to delete one ProductionCheckTick
   *   }
   * })
   * 
   */
  delete<T extends ProductionCheckTickDeleteArgs>(args: Prisma.SelectSubset<T, ProductionCheckTickDeleteArgs<ExtArgs>>): Prisma.Prisma__ProductionCheckTickClient<runtime.Types.Result.GetResult<Prisma.$ProductionCheckTickPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProductionCheckTick.
   * @param {ProductionCheckTickUpdateArgs} args - Arguments to update one ProductionCheckTick.
   * @example
   * // Update one ProductionCheckTick
   * const productionCheckTick = await prisma.productionCheckTick.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProductionCheckTickUpdateArgs>(args: Prisma.SelectSubset<T, ProductionCheckTickUpdateArgs<ExtArgs>>): Prisma.Prisma__ProductionCheckTickClient<runtime.Types.Result.GetResult<Prisma.$ProductionCheckTickPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProductionCheckTicks.
   * @param {ProductionCheckTickDeleteManyArgs} args - Arguments to filter ProductionCheckTicks to delete.
   * @example
   * // Delete a few ProductionCheckTicks
   * const { count } = await prisma.productionCheckTick.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProductionCheckTickDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProductionCheckTickDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductionCheckTicks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductionCheckTickUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProductionCheckTicks
   * const productionCheckTick = await prisma.productionCheckTick.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProductionCheckTickUpdateManyArgs>(args: Prisma.SelectSubset<T, ProductionCheckTickUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductionCheckTicks and returns the data updated in the database.
   * @param {ProductionCheckTickUpdateManyAndReturnArgs} args - Arguments to update many ProductionCheckTicks.
   * @example
   * // Update many ProductionCheckTicks
   * const productionCheckTick = await prisma.productionCheckTick.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProductionCheckTicks and only return the `id`
   * const productionCheckTickWithIdOnly = await prisma.productionCheckTick.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProductionCheckTickUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProductionCheckTickUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductionCheckTickPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProductionCheckTick.
   * @param {ProductionCheckTickUpsertArgs} args - Arguments to update or create a ProductionCheckTick.
   * @example
   * // Update or create a ProductionCheckTick
   * const productionCheckTick = await prisma.productionCheckTick.upsert({
   *   create: {
   *     // ... data to create a ProductionCheckTick
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProductionCheckTick we want to update
   *   }
   * })
   */
  upsert<T extends ProductionCheckTickUpsertArgs>(args: Prisma.SelectSubset<T, ProductionCheckTickUpsertArgs<ExtArgs>>): Prisma.Prisma__ProductionCheckTickClient<runtime.Types.Result.GetResult<Prisma.$ProductionCheckTickPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProductionCheckTicks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductionCheckTickCountArgs} args - Arguments to filter ProductionCheckTicks to count.
   * @example
   * // Count the number of ProductionCheckTicks
   * const count = await prisma.productionCheckTick.count({
   *   where: {
   *     // ... the filter for the ProductionCheckTicks we want to count
   *   }
   * })
  **/
  count<T extends ProductionCheckTickCountArgs>(
    args?: Prisma.Subset<T, ProductionCheckTickCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProductionCheckTickCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProductionCheckTick.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductionCheckTickAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProductionCheckTickAggregateArgs>(args: Prisma.Subset<T, ProductionCheckTickAggregateArgs>): Prisma.PrismaPromise<GetProductionCheckTickAggregateType<T>>

  /**
   * Group by ProductionCheckTick.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductionCheckTickGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProductionCheckTickGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProductionCheckTickGroupByArgs['orderBy'] }
      : { orderBy?: ProductionCheckTickGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProductionCheckTickGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProductionCheckTickGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProductionCheckTick model
 */
readonly fields: ProductionCheckTickFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProductionCheckTick.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProductionCheckTickClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  check<T extends Prisma.ProductionCheckDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductionCheckDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductionCheckClient<runtime.Types.Result.GetResult<Prisma.$ProductionCheckPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  asset<T extends Prisma.AssetDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AssetDefaultArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.ProductionCheckTick$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductionCheckTick$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProductionCheckTick model
 */
export interface ProductionCheckTickFieldRefs {
  readonly id: Prisma.FieldRef<"ProductionCheckTick", 'String'>
  readonly checkId: Prisma.FieldRef<"ProductionCheckTick", 'String'>
  readonly assetId: Prisma.FieldRef<"ProductionCheckTick", 'String'>
  readonly userId: Prisma.FieldRef<"ProductionCheckTick", 'String'>
  readonly via: Prisma.FieldRef<"ProductionCheckTick", 'String'>
  readonly unexpected: Prisma.FieldRef<"ProductionCheckTick", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"ProductionCheckTick", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ProductionCheckTick findUnique
 */
export type ProductionCheckTickFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheckTick
   */
  select?: Prisma.ProductionCheckTickSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheckTick
   */
  omit?: Prisma.ProductionCheckTickOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckTickInclude<ExtArgs> | null
  /**
   * Filter, which ProductionCheckTick to fetch.
   */
  where: Prisma.ProductionCheckTickWhereUniqueInput
}

/**
 * ProductionCheckTick findUniqueOrThrow
 */
export type ProductionCheckTickFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheckTick
   */
  select?: Prisma.ProductionCheckTickSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheckTick
   */
  omit?: Prisma.ProductionCheckTickOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckTickInclude<ExtArgs> | null
  /**
   * Filter, which ProductionCheckTick to fetch.
   */
  where: Prisma.ProductionCheckTickWhereUniqueInput
}

/**
 * ProductionCheckTick findFirst
 */
export type ProductionCheckTickFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheckTick
   */
  select?: Prisma.ProductionCheckTickSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheckTick
   */
  omit?: Prisma.ProductionCheckTickOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckTickInclude<ExtArgs> | null
  /**
   * Filter, which ProductionCheckTick to fetch.
   */
  where?: Prisma.ProductionCheckTickWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductionCheckTicks to fetch.
   */
  orderBy?: Prisma.ProductionCheckTickOrderByWithRelationInput | Prisma.ProductionCheckTickOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductionCheckTicks.
   */
  cursor?: Prisma.ProductionCheckTickWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductionCheckTicks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductionCheckTicks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductionCheckTicks.
   */
  distinct?: Prisma.ProductionCheckTickScalarFieldEnum | Prisma.ProductionCheckTickScalarFieldEnum[]
}

/**
 * ProductionCheckTick findFirstOrThrow
 */
export type ProductionCheckTickFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheckTick
   */
  select?: Prisma.ProductionCheckTickSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheckTick
   */
  omit?: Prisma.ProductionCheckTickOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckTickInclude<ExtArgs> | null
  /**
   * Filter, which ProductionCheckTick to fetch.
   */
  where?: Prisma.ProductionCheckTickWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductionCheckTicks to fetch.
   */
  orderBy?: Prisma.ProductionCheckTickOrderByWithRelationInput | Prisma.ProductionCheckTickOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductionCheckTicks.
   */
  cursor?: Prisma.ProductionCheckTickWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductionCheckTicks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductionCheckTicks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductionCheckTicks.
   */
  distinct?: Prisma.ProductionCheckTickScalarFieldEnum | Prisma.ProductionCheckTickScalarFieldEnum[]
}

/**
 * ProductionCheckTick findMany
 */
export type ProductionCheckTickFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheckTick
   */
  select?: Prisma.ProductionCheckTickSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheckTick
   */
  omit?: Prisma.ProductionCheckTickOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckTickInclude<ExtArgs> | null
  /**
   * Filter, which ProductionCheckTicks to fetch.
   */
  where?: Prisma.ProductionCheckTickWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductionCheckTicks to fetch.
   */
  orderBy?: Prisma.ProductionCheckTickOrderByWithRelationInput | Prisma.ProductionCheckTickOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProductionCheckTicks.
   */
  cursor?: Prisma.ProductionCheckTickWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductionCheckTicks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductionCheckTicks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductionCheckTicks.
   */
  distinct?: Prisma.ProductionCheckTickScalarFieldEnum | Prisma.ProductionCheckTickScalarFieldEnum[]
}

/**
 * ProductionCheckTick create
 */
export type ProductionCheckTickCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheckTick
   */
  select?: Prisma.ProductionCheckTickSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheckTick
   */
  omit?: Prisma.ProductionCheckTickOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckTickInclude<ExtArgs> | null
  /**
   * The data needed to create a ProductionCheckTick.
   */
  data: Prisma.XOR<Prisma.ProductionCheckTickCreateInput, Prisma.ProductionCheckTickUncheckedCreateInput>
}

/**
 * ProductionCheckTick createMany
 */
export type ProductionCheckTickCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProductionCheckTicks.
   */
  data: Prisma.ProductionCheckTickCreateManyInput | Prisma.ProductionCheckTickCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProductionCheckTick createManyAndReturn
 */
export type ProductionCheckTickCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheckTick
   */
  select?: Prisma.ProductionCheckTickSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheckTick
   */
  omit?: Prisma.ProductionCheckTickOmit<ExtArgs> | null
  /**
   * The data used to create many ProductionCheckTicks.
   */
  data: Prisma.ProductionCheckTickCreateManyInput | Prisma.ProductionCheckTickCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckTickIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ProductionCheckTick update
 */
export type ProductionCheckTickUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheckTick
   */
  select?: Prisma.ProductionCheckTickSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheckTick
   */
  omit?: Prisma.ProductionCheckTickOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckTickInclude<ExtArgs> | null
  /**
   * The data needed to update a ProductionCheckTick.
   */
  data: Prisma.XOR<Prisma.ProductionCheckTickUpdateInput, Prisma.ProductionCheckTickUncheckedUpdateInput>
  /**
   * Choose, which ProductionCheckTick to update.
   */
  where: Prisma.ProductionCheckTickWhereUniqueInput
}

/**
 * ProductionCheckTick updateMany
 */
export type ProductionCheckTickUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProductionCheckTicks.
   */
  data: Prisma.XOR<Prisma.ProductionCheckTickUpdateManyMutationInput, Prisma.ProductionCheckTickUncheckedUpdateManyInput>
  /**
   * Filter which ProductionCheckTicks to update
   */
  where?: Prisma.ProductionCheckTickWhereInput
  /**
   * Limit how many ProductionCheckTicks to update.
   */
  limit?: number
}

/**
 * ProductionCheckTick updateManyAndReturn
 */
export type ProductionCheckTickUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheckTick
   */
  select?: Prisma.ProductionCheckTickSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheckTick
   */
  omit?: Prisma.ProductionCheckTickOmit<ExtArgs> | null
  /**
   * The data used to update ProductionCheckTicks.
   */
  data: Prisma.XOR<Prisma.ProductionCheckTickUpdateManyMutationInput, Prisma.ProductionCheckTickUncheckedUpdateManyInput>
  /**
   * Filter which ProductionCheckTicks to update
   */
  where?: Prisma.ProductionCheckTickWhereInput
  /**
   * Limit how many ProductionCheckTicks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckTickIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ProductionCheckTick upsert
 */
export type ProductionCheckTickUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheckTick
   */
  select?: Prisma.ProductionCheckTickSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheckTick
   */
  omit?: Prisma.ProductionCheckTickOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckTickInclude<ExtArgs> | null
  /**
   * The filter to search for the ProductionCheckTick to update in case it exists.
   */
  where: Prisma.ProductionCheckTickWhereUniqueInput
  /**
   * In case the ProductionCheckTick found by the `where` argument doesn't exist, create a new ProductionCheckTick with this data.
   */
  create: Prisma.XOR<Prisma.ProductionCheckTickCreateInput, Prisma.ProductionCheckTickUncheckedCreateInput>
  /**
   * In case the ProductionCheckTick was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProductionCheckTickUpdateInput, Prisma.ProductionCheckTickUncheckedUpdateInput>
}

/**
 * ProductionCheckTick delete
 */
export type ProductionCheckTickDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheckTick
   */
  select?: Prisma.ProductionCheckTickSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheckTick
   */
  omit?: Prisma.ProductionCheckTickOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckTickInclude<ExtArgs> | null
  /**
   * Filter which ProductionCheckTick to delete.
   */
  where: Prisma.ProductionCheckTickWhereUniqueInput
}

/**
 * ProductionCheckTick deleteMany
 */
export type ProductionCheckTickDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductionCheckTicks to delete
   */
  where?: Prisma.ProductionCheckTickWhereInput
  /**
   * Limit how many ProductionCheckTicks to delete.
   */
  limit?: number
}

/**
 * ProductionCheckTick.user
 */
export type ProductionCheckTick$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * ProductionCheckTick without action
 */
export type ProductionCheckTickDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheckTick
   */
  select?: Prisma.ProductionCheckTickSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheckTick
   */
  omit?: Prisma.ProductionCheckTickOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckTickInclude<ExtArgs> | null
}
