
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProductionCheck` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model ProductionCheck
 * 
 */
export type ProductionCheckModel = runtime.Types.Result.DefaultSelection<Prisma.$ProductionCheckPayload>

export type AggregateProductionCheck = {
  _count: ProductionCheckCountAggregateOutputType | null
  _min: ProductionCheckMinAggregateOutputType | null
  _max: ProductionCheckMaxAggregateOutputType | null
}

export type ProductionCheckMinAggregateOutputType = {
  id: string | null
  productionId: string | null
  organizationId: string | null
  status: string | null
  createdById: string | null
  closedById: string | null
  closedAt: Date | null
  createdAt: Date | null
}

export type ProductionCheckMaxAggregateOutputType = {
  id: string | null
  productionId: string | null
  organizationId: string | null
  status: string | null
  createdById: string | null
  closedById: string | null
  closedAt: Date | null
  createdAt: Date | null
}

export type ProductionCheckCountAggregateOutputType = {
  id: number
  productionId: number
  organizationId: number
  status: number
  createdById: number
  closedById: number
  closedAt: number
  createdAt: number
  _all: number
}


export type ProductionCheckMinAggregateInputType = {
  id?: true
  productionId?: true
  organizationId?: true
  status?: true
  createdById?: true
  closedById?: true
  closedAt?: true
  createdAt?: true
}

export type ProductionCheckMaxAggregateInputType = {
  id?: true
  productionId?: true
  organizationId?: true
  status?: true
  createdById?: true
  closedById?: true
  closedAt?: true
  createdAt?: true
}

export type ProductionCheckCountAggregateInputType = {
  id?: true
  productionId?: true
  organizationId?: true
  status?: true
  createdById?: true
  closedById?: true
  closedAt?: true
  createdAt?: true
  _all?: true
}

export type ProductionCheckAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductionCheck to aggregate.
   */
  where?: Prisma.ProductionCheckWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductionChecks to fetch.
   */
  orderBy?: Prisma.ProductionCheckOrderByWithRelationInput | Prisma.ProductionCheckOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProductionCheckWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductionChecks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductionChecks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProductionChecks
  **/
  _count?: true | ProductionCheckCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProductionCheckMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProductionCheckMaxAggregateInputType
}

export type GetProductionCheckAggregateType<T extends ProductionCheckAggregateArgs> = {
      [P in keyof T & keyof AggregateProductionCheck]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProductionCheck[P]>
    : Prisma.GetScalarType<T[P], AggregateProductionCheck[P]>
}




export type ProductionCheckGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductionCheckWhereInput
  orderBy?: Prisma.ProductionCheckOrderByWithAggregationInput | Prisma.ProductionCheckOrderByWithAggregationInput[]
  by: Prisma.ProductionCheckScalarFieldEnum[] | Prisma.ProductionCheckScalarFieldEnum
  having?: Prisma.ProductionCheckScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProductionCheckCountAggregateInputType | true
  _min?: ProductionCheckMinAggregateInputType
  _max?: ProductionCheckMaxAggregateInputType
}

export type ProductionCheckGroupByOutputType = {
  id: string
  productionId: string
  organizationId: string
  status: string
  createdById: string | null
  closedById: string | null
  closedAt: Date | null
  createdAt: Date
  _count: ProductionCheckCountAggregateOutputType | null
  _min: ProductionCheckMinAggregateOutputType | null
  _max: ProductionCheckMaxAggregateOutputType | null
}

export type GetProductionCheckGroupByPayload<T extends ProductionCheckGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProductionCheckGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProductionCheckGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProductionCheckGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProductionCheckGroupByOutputType[P]>
      }
    >
  >



export type ProductionCheckWhereInput = {
  AND?: Prisma.ProductionCheckWhereInput | Prisma.ProductionCheckWhereInput[]
  OR?: Prisma.ProductionCheckWhereInput[]
  NOT?: Prisma.ProductionCheckWhereInput | Prisma.ProductionCheckWhereInput[]
  id?: Prisma.StringFilter<"ProductionCheck"> | string
  productionId?: Prisma.StringFilter<"ProductionCheck"> | string
  organizationId?: Prisma.StringFilter<"ProductionCheck"> | string
  status?: Prisma.StringFilter<"ProductionCheck"> | string
  createdById?: Prisma.StringNullableFilter<"ProductionCheck"> | string | null
  closedById?: Prisma.StringNullableFilter<"ProductionCheck"> | string | null
  closedAt?: Prisma.DateTimeNullableFilter<"ProductionCheck"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ProductionCheck"> | Date | string
  production?: Prisma.XOR<Prisma.ProductionScalarRelationFilter, Prisma.ProductionWhereInput>
  organization?: Prisma.XOR<Prisma.OrganizationScalarRelationFilter, Prisma.OrganizationWhereInput>
  createdBy?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  closedBy?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  ticks?: Prisma.ProductionCheckTickListRelationFilter
}

export type ProductionCheckOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  productionId?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdById?: Prisma.SortOrderInput | Prisma.SortOrder
  closedById?: Prisma.SortOrderInput | Prisma.SortOrder
  closedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  production?: Prisma.ProductionOrderByWithRelationInput
  organization?: Prisma.OrganizationOrderByWithRelationInput
  createdBy?: Prisma.UserOrderByWithRelationInput
  closedBy?: Prisma.UserOrderByWithRelationInput
  ticks?: Prisma.ProductionCheckTickOrderByRelationAggregateInput
}

export type ProductionCheckWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ProductionCheckWhereInput | Prisma.ProductionCheckWhereInput[]
  OR?: Prisma.ProductionCheckWhereInput[]
  NOT?: Prisma.ProductionCheckWhereInput | Prisma.ProductionCheckWhereInput[]
  productionId?: Prisma.StringFilter<"ProductionCheck"> | string
  organizationId?: Prisma.StringFilter<"ProductionCheck"> | string
  status?: Prisma.StringFilter<"ProductionCheck"> | string
  createdById?: Prisma.StringNullableFilter<"ProductionCheck"> | string | null
  closedById?: Prisma.StringNullableFilter<"ProductionCheck"> | string | null
  closedAt?: Prisma.DateTimeNullableFilter<"ProductionCheck"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ProductionCheck"> | Date | string
  production?: Prisma.XOR<Prisma.ProductionScalarRelationFilter, Prisma.ProductionWhereInput>
  organization?: Prisma.XOR<Prisma.OrganizationScalarRelationFilter, Prisma.OrganizationWhereInput>
  createdBy?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  closedBy?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  ticks?: Prisma.ProductionCheckTickListRelationFilter
}, "id">

export type ProductionCheckOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  productionId?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdById?: Prisma.SortOrderInput | Prisma.SortOrder
  closedById?: Prisma.SortOrderInput | Prisma.SortOrder
  closedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ProductionCheckCountOrderByAggregateInput
  _max?: Prisma.ProductionCheckMaxOrderByAggregateInput
  _min?: Prisma.ProductionCheckMinOrderByAggregateInput
}

export type ProductionCheckScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProductionCheckScalarWhereWithAggregatesInput | Prisma.ProductionCheckScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProductionCheckScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProductionCheckScalarWhereWithAggregatesInput | Prisma.ProductionCheckScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ProductionCheck"> | string
  productionId?: Prisma.StringWithAggregatesFilter<"ProductionCheck"> | string
  organizationId?: Prisma.StringWithAggregatesFilter<"ProductionCheck"> | string
  status?: Prisma.StringWithAggregatesFilter<"ProductionCheck"> | string
  createdById?: Prisma.StringNullableWithAggregatesFilter<"ProductionCheck"> | string | null
  closedById?: Prisma.StringNullableWithAggregatesFilter<"ProductionCheck"> | string | null
  closedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ProductionCheck"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ProductionCheck"> | Date | string
}

export type ProductionCheckCreateInput = {
  id?: string
  status?: string
  closedAt?: Date | string | null
  createdAt?: Date | string
  production: Prisma.ProductionCreateNestedOneWithoutChecksInput
  organization: Prisma.OrganizationCreateNestedOneWithoutProductionChecksInput
  createdBy?: Prisma.UserCreateNestedOneWithoutChecksStartedInput
  closedBy?: Prisma.UserCreateNestedOneWithoutChecksClosedInput
  ticks?: Prisma.ProductionCheckTickCreateNestedManyWithoutCheckInput
}

export type ProductionCheckUncheckedCreateInput = {
  id?: string
  productionId: string
  organizationId: string
  status?: string
  createdById?: string | null
  closedById?: string | null
  closedAt?: Date | string | null
  createdAt?: Date | string
  ticks?: Prisma.ProductionCheckTickUncheckedCreateNestedManyWithoutCheckInput
}

export type ProductionCheckUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  closedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  production?: Prisma.ProductionUpdateOneRequiredWithoutChecksNestedInput
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutProductionChecksNestedInput
  createdBy?: Prisma.UserUpdateOneWithoutChecksStartedNestedInput
  closedBy?: Prisma.UserUpdateOneWithoutChecksClosedNestedInput
  ticks?: Prisma.ProductionCheckTickUpdateManyWithoutCheckNestedInput
}

export type ProductionCheckUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productionId?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  closedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  closedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ticks?: Prisma.ProductionCheckTickUncheckedUpdateManyWithoutCheckNestedInput
}

export type ProductionCheckCreateManyInput = {
  id?: string
  productionId: string
  organizationId: string
  status?: string
  createdById?: string | null
  closedById?: string | null
  closedAt?: Date | string | null
  createdAt?: Date | string
}

export type ProductionCheckUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  closedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductionCheckUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productionId?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  closedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  closedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductionCheckListRelationFilter = {
  every?: Prisma.ProductionCheckWhereInput
  some?: Prisma.ProductionCheckWhereInput
  none?: Prisma.ProductionCheckWhereInput
}

export type ProductionCheckOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProductionCheckCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productionId?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  closedById?: Prisma.SortOrder
  closedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ProductionCheckMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productionId?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  closedById?: Prisma.SortOrder
  closedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ProductionCheckMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productionId?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  closedById?: Prisma.SortOrder
  closedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ProductionCheckScalarRelationFilter = {
  is?: Prisma.ProductionCheckWhereInput
  isNot?: Prisma.ProductionCheckWhereInput
}

export type ProductionCheckCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckCreateWithoutCreatedByInput, Prisma.ProductionCheckUncheckedCreateWithoutCreatedByInput> | Prisma.ProductionCheckCreateWithoutCreatedByInput[] | Prisma.ProductionCheckUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.ProductionCheckCreateOrConnectWithoutCreatedByInput | Prisma.ProductionCheckCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.ProductionCheckCreateManyCreatedByInputEnvelope
  connect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
}

export type ProductionCheckCreateNestedManyWithoutClosedByInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckCreateWithoutClosedByInput, Prisma.ProductionCheckUncheckedCreateWithoutClosedByInput> | Prisma.ProductionCheckCreateWithoutClosedByInput[] | Prisma.ProductionCheckUncheckedCreateWithoutClosedByInput[]
  connectOrCreate?: Prisma.ProductionCheckCreateOrConnectWithoutClosedByInput | Prisma.ProductionCheckCreateOrConnectWithoutClosedByInput[]
  createMany?: Prisma.ProductionCheckCreateManyClosedByInputEnvelope
  connect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
}

export type ProductionCheckUncheckedCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckCreateWithoutCreatedByInput, Prisma.ProductionCheckUncheckedCreateWithoutCreatedByInput> | Prisma.ProductionCheckCreateWithoutCreatedByInput[] | Prisma.ProductionCheckUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.ProductionCheckCreateOrConnectWithoutCreatedByInput | Prisma.ProductionCheckCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.ProductionCheckCreateManyCreatedByInputEnvelope
  connect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
}

export type ProductionCheckUncheckedCreateNestedManyWithoutClosedByInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckCreateWithoutClosedByInput, Prisma.ProductionCheckUncheckedCreateWithoutClosedByInput> | Prisma.ProductionCheckCreateWithoutClosedByInput[] | Prisma.ProductionCheckUncheckedCreateWithoutClosedByInput[]
  connectOrCreate?: Prisma.ProductionCheckCreateOrConnectWithoutClosedByInput | Prisma.ProductionCheckCreateOrConnectWithoutClosedByInput[]
  createMany?: Prisma.ProductionCheckCreateManyClosedByInputEnvelope
  connect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
}

export type ProductionCheckUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckCreateWithoutCreatedByInput, Prisma.ProductionCheckUncheckedCreateWithoutCreatedByInput> | Prisma.ProductionCheckCreateWithoutCreatedByInput[] | Prisma.ProductionCheckUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.ProductionCheckCreateOrConnectWithoutCreatedByInput | Prisma.ProductionCheckCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.ProductionCheckUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.ProductionCheckUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.ProductionCheckCreateManyCreatedByInputEnvelope
  set?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  disconnect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  delete?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  connect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  update?: Prisma.ProductionCheckUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.ProductionCheckUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.ProductionCheckUpdateManyWithWhereWithoutCreatedByInput | Prisma.ProductionCheckUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.ProductionCheckScalarWhereInput | Prisma.ProductionCheckScalarWhereInput[]
}

export type ProductionCheckUpdateManyWithoutClosedByNestedInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckCreateWithoutClosedByInput, Prisma.ProductionCheckUncheckedCreateWithoutClosedByInput> | Prisma.ProductionCheckCreateWithoutClosedByInput[] | Prisma.ProductionCheckUncheckedCreateWithoutClosedByInput[]
  connectOrCreate?: Prisma.ProductionCheckCreateOrConnectWithoutClosedByInput | Prisma.ProductionCheckCreateOrConnectWithoutClosedByInput[]
  upsert?: Prisma.ProductionCheckUpsertWithWhereUniqueWithoutClosedByInput | Prisma.ProductionCheckUpsertWithWhereUniqueWithoutClosedByInput[]
  createMany?: Prisma.ProductionCheckCreateManyClosedByInputEnvelope
  set?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  disconnect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  delete?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  connect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  update?: Prisma.ProductionCheckUpdateWithWhereUniqueWithoutClosedByInput | Prisma.ProductionCheckUpdateWithWhereUniqueWithoutClosedByInput[]
  updateMany?: Prisma.ProductionCheckUpdateManyWithWhereWithoutClosedByInput | Prisma.ProductionCheckUpdateManyWithWhereWithoutClosedByInput[]
  deleteMany?: Prisma.ProductionCheckScalarWhereInput | Prisma.ProductionCheckScalarWhereInput[]
}

export type ProductionCheckUncheckedUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckCreateWithoutCreatedByInput, Prisma.ProductionCheckUncheckedCreateWithoutCreatedByInput> | Prisma.ProductionCheckCreateWithoutCreatedByInput[] | Prisma.ProductionCheckUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.ProductionCheckCreateOrConnectWithoutCreatedByInput | Prisma.ProductionCheckCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.ProductionCheckUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.ProductionCheckUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.ProductionCheckCreateManyCreatedByInputEnvelope
  set?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  disconnect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  delete?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  connect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  update?: Prisma.ProductionCheckUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.ProductionCheckUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.ProductionCheckUpdateManyWithWhereWithoutCreatedByInput | Prisma.ProductionCheckUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.ProductionCheckScalarWhereInput | Prisma.ProductionCheckScalarWhereInput[]
}

export type ProductionCheckUncheckedUpdateManyWithoutClosedByNestedInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckCreateWithoutClosedByInput, Prisma.ProductionCheckUncheckedCreateWithoutClosedByInput> | Prisma.ProductionCheckCreateWithoutClosedByInput[] | Prisma.ProductionCheckUncheckedCreateWithoutClosedByInput[]
  connectOrCreate?: Prisma.ProductionCheckCreateOrConnectWithoutClosedByInput | Prisma.ProductionCheckCreateOrConnectWithoutClosedByInput[]
  upsert?: Prisma.ProductionCheckUpsertWithWhereUniqueWithoutClosedByInput | Prisma.ProductionCheckUpsertWithWhereUniqueWithoutClosedByInput[]
  createMany?: Prisma.ProductionCheckCreateManyClosedByInputEnvelope
  set?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  disconnect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  delete?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  connect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  update?: Prisma.ProductionCheckUpdateWithWhereUniqueWithoutClosedByInput | Prisma.ProductionCheckUpdateWithWhereUniqueWithoutClosedByInput[]
  updateMany?: Prisma.ProductionCheckUpdateManyWithWhereWithoutClosedByInput | Prisma.ProductionCheckUpdateManyWithWhereWithoutClosedByInput[]
  deleteMany?: Prisma.ProductionCheckScalarWhereInput | Prisma.ProductionCheckScalarWhereInput[]
}

export type ProductionCheckCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckCreateWithoutOrganizationInput, Prisma.ProductionCheckUncheckedCreateWithoutOrganizationInput> | Prisma.ProductionCheckCreateWithoutOrganizationInput[] | Prisma.ProductionCheckUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.ProductionCheckCreateOrConnectWithoutOrganizationInput | Prisma.ProductionCheckCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.ProductionCheckCreateManyOrganizationInputEnvelope
  connect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
}

export type ProductionCheckUncheckedCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckCreateWithoutOrganizationInput, Prisma.ProductionCheckUncheckedCreateWithoutOrganizationInput> | Prisma.ProductionCheckCreateWithoutOrganizationInput[] | Prisma.ProductionCheckUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.ProductionCheckCreateOrConnectWithoutOrganizationInput | Prisma.ProductionCheckCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.ProductionCheckCreateManyOrganizationInputEnvelope
  connect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
}

export type ProductionCheckUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckCreateWithoutOrganizationInput, Prisma.ProductionCheckUncheckedCreateWithoutOrganizationInput> | Prisma.ProductionCheckCreateWithoutOrganizationInput[] | Prisma.ProductionCheckUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.ProductionCheckCreateOrConnectWithoutOrganizationInput | Prisma.ProductionCheckCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.ProductionCheckUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.ProductionCheckUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.ProductionCheckCreateManyOrganizationInputEnvelope
  set?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  disconnect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  delete?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  connect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  update?: Prisma.ProductionCheckUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.ProductionCheckUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.ProductionCheckUpdateManyWithWhereWithoutOrganizationInput | Prisma.ProductionCheckUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.ProductionCheckScalarWhereInput | Prisma.ProductionCheckScalarWhereInput[]
}

export type ProductionCheckUncheckedUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckCreateWithoutOrganizationInput, Prisma.ProductionCheckUncheckedCreateWithoutOrganizationInput> | Prisma.ProductionCheckCreateWithoutOrganizationInput[] | Prisma.ProductionCheckUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.ProductionCheckCreateOrConnectWithoutOrganizationInput | Prisma.ProductionCheckCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.ProductionCheckUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.ProductionCheckUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.ProductionCheckCreateManyOrganizationInputEnvelope
  set?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  disconnect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  delete?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  connect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  update?: Prisma.ProductionCheckUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.ProductionCheckUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.ProductionCheckUpdateManyWithWhereWithoutOrganizationInput | Prisma.ProductionCheckUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.ProductionCheckScalarWhereInput | Prisma.ProductionCheckScalarWhereInput[]
}

export type ProductionCheckCreateNestedManyWithoutProductionInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckCreateWithoutProductionInput, Prisma.ProductionCheckUncheckedCreateWithoutProductionInput> | Prisma.ProductionCheckCreateWithoutProductionInput[] | Prisma.ProductionCheckUncheckedCreateWithoutProductionInput[]
  connectOrCreate?: Prisma.ProductionCheckCreateOrConnectWithoutProductionInput | Prisma.ProductionCheckCreateOrConnectWithoutProductionInput[]
  createMany?: Prisma.ProductionCheckCreateManyProductionInputEnvelope
  connect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
}

export type ProductionCheckUncheckedCreateNestedManyWithoutProductionInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckCreateWithoutProductionInput, Prisma.ProductionCheckUncheckedCreateWithoutProductionInput> | Prisma.ProductionCheckCreateWithoutProductionInput[] | Prisma.ProductionCheckUncheckedCreateWithoutProductionInput[]
  connectOrCreate?: Prisma.ProductionCheckCreateOrConnectWithoutProductionInput | Prisma.ProductionCheckCreateOrConnectWithoutProductionInput[]
  createMany?: Prisma.ProductionCheckCreateManyProductionInputEnvelope
  connect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
}

export type ProductionCheckUpdateManyWithoutProductionNestedInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckCreateWithoutProductionInput, Prisma.ProductionCheckUncheckedCreateWithoutProductionInput> | Prisma.ProductionCheckCreateWithoutProductionInput[] | Prisma.ProductionCheckUncheckedCreateWithoutProductionInput[]
  connectOrCreate?: Prisma.ProductionCheckCreateOrConnectWithoutProductionInput | Prisma.ProductionCheckCreateOrConnectWithoutProductionInput[]
  upsert?: Prisma.ProductionCheckUpsertWithWhereUniqueWithoutProductionInput | Prisma.ProductionCheckUpsertWithWhereUniqueWithoutProductionInput[]
  createMany?: Prisma.ProductionCheckCreateManyProductionInputEnvelope
  set?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  disconnect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  delete?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  connect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  update?: Prisma.ProductionCheckUpdateWithWhereUniqueWithoutProductionInput | Prisma.ProductionCheckUpdateWithWhereUniqueWithoutProductionInput[]
  updateMany?: Prisma.ProductionCheckUpdateManyWithWhereWithoutProductionInput | Prisma.ProductionCheckUpdateManyWithWhereWithoutProductionInput[]
  deleteMany?: Prisma.ProductionCheckScalarWhereInput | Prisma.ProductionCheckScalarWhereInput[]
}

export type ProductionCheckUncheckedUpdateManyWithoutProductionNestedInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckCreateWithoutProductionInput, Prisma.ProductionCheckUncheckedCreateWithoutProductionInput> | Prisma.ProductionCheckCreateWithoutProductionInput[] | Prisma.ProductionCheckUncheckedCreateWithoutProductionInput[]
  connectOrCreate?: Prisma.ProductionCheckCreateOrConnectWithoutProductionInput | Prisma.ProductionCheckCreateOrConnectWithoutProductionInput[]
  upsert?: Prisma.ProductionCheckUpsertWithWhereUniqueWithoutProductionInput | Prisma.ProductionCheckUpsertWithWhereUniqueWithoutProductionInput[]
  createMany?: Prisma.ProductionCheckCreateManyProductionInputEnvelope
  set?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  disconnect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  delete?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  connect?: Prisma.ProductionCheckWhereUniqueInput | Prisma.ProductionCheckWhereUniqueInput[]
  update?: Prisma.ProductionCheckUpdateWithWhereUniqueWithoutProductionInput | Prisma.ProductionCheckUpdateWithWhereUniqueWithoutProductionInput[]
  updateMany?: Prisma.ProductionCheckUpdateManyWithWhereWithoutProductionInput | Prisma.ProductionCheckUpdateManyWithWhereWithoutProductionInput[]
  deleteMany?: Prisma.ProductionCheckScalarWhereInput | Prisma.ProductionCheckScalarWhereInput[]
}

export type ProductionCheckCreateNestedOneWithoutTicksInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckCreateWithoutTicksInput, Prisma.ProductionCheckUncheckedCreateWithoutTicksInput>
  connectOrCreate?: Prisma.ProductionCheckCreateOrConnectWithoutTicksInput
  connect?: Prisma.ProductionCheckWhereUniqueInput
}

export type ProductionCheckUpdateOneRequiredWithoutTicksNestedInput = {
  create?: Prisma.XOR<Prisma.ProductionCheckCreateWithoutTicksInput, Prisma.ProductionCheckUncheckedCreateWithoutTicksInput>
  connectOrCreate?: Prisma.ProductionCheckCreateOrConnectWithoutTicksInput
  upsert?: Prisma.ProductionCheckUpsertWithoutTicksInput
  connect?: Prisma.ProductionCheckWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProductionCheckUpdateToOneWithWhereWithoutTicksInput, Prisma.ProductionCheckUpdateWithoutTicksInput>, Prisma.ProductionCheckUncheckedUpdateWithoutTicksInput>
}

export type ProductionCheckCreateWithoutCreatedByInput = {
  id?: string
  status?: string
  closedAt?: Date | string | null
  createdAt?: Date | string
  production: Prisma.ProductionCreateNestedOneWithoutChecksInput
  organization: Prisma.OrganizationCreateNestedOneWithoutProductionChecksInput
  closedBy?: Prisma.UserCreateNestedOneWithoutChecksClosedInput
  ticks?: Prisma.ProductionCheckTickCreateNestedManyWithoutCheckInput
}

export type ProductionCheckUncheckedCreateWithoutCreatedByInput = {
  id?: string
  productionId: string
  organizationId: string
  status?: string
  closedById?: string | null
  closedAt?: Date | string | null
  createdAt?: Date | string
  ticks?: Prisma.ProductionCheckTickUncheckedCreateNestedManyWithoutCheckInput
}

export type ProductionCheckCreateOrConnectWithoutCreatedByInput = {
  where: Prisma.ProductionCheckWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductionCheckCreateWithoutCreatedByInput, Prisma.ProductionCheckUncheckedCreateWithoutCreatedByInput>
}

export type ProductionCheckCreateManyCreatedByInputEnvelope = {
  data: Prisma.ProductionCheckCreateManyCreatedByInput | Prisma.ProductionCheckCreateManyCreatedByInput[]
  skipDuplicates?: boolean
}

export type ProductionCheckCreateWithoutClosedByInput = {
  id?: string
  status?: string
  closedAt?: Date | string | null
  createdAt?: Date | string
  production: Prisma.ProductionCreateNestedOneWithoutChecksInput
  organization: Prisma.OrganizationCreateNestedOneWithoutProductionChecksInput
  createdBy?: Prisma.UserCreateNestedOneWithoutChecksStartedInput
  ticks?: Prisma.ProductionCheckTickCreateNestedManyWithoutCheckInput
}

export type ProductionCheckUncheckedCreateWithoutClosedByInput = {
  id?: string
  productionId: string
  organizationId: string
  status?: string
  createdById?: string | null
  closedAt?: Date | string | null
  createdAt?: Date | string
  ticks?: Prisma.ProductionCheckTickUncheckedCreateNestedManyWithoutCheckInput
}

export type ProductionCheckCreateOrConnectWithoutClosedByInput = {
  where: Prisma.ProductionCheckWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductionCheckCreateWithoutClosedByInput, Prisma.ProductionCheckUncheckedCreateWithoutClosedByInput>
}

export type ProductionCheckCreateManyClosedByInputEnvelope = {
  data: Prisma.ProductionCheckCreateManyClosedByInput | Prisma.ProductionCheckCreateManyClosedByInput[]
  skipDuplicates?: boolean
}

export type ProductionCheckUpsertWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.ProductionCheckWhereUniqueInput
  update: Prisma.XOR<Prisma.ProductionCheckUpdateWithoutCreatedByInput, Prisma.ProductionCheckUncheckedUpdateWithoutCreatedByInput>
  create: Prisma.XOR<Prisma.ProductionCheckCreateWithoutCreatedByInput, Prisma.ProductionCheckUncheckedCreateWithoutCreatedByInput>
}

export type ProductionCheckUpdateWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.ProductionCheckWhereUniqueInput
  data: Prisma.XOR<Prisma.ProductionCheckUpdateWithoutCreatedByInput, Prisma.ProductionCheckUncheckedUpdateWithoutCreatedByInput>
}

export type ProductionCheckUpdateManyWithWhereWithoutCreatedByInput = {
  where: Prisma.ProductionCheckScalarWhereInput
  data: Prisma.XOR<Prisma.ProductionCheckUpdateManyMutationInput, Prisma.ProductionCheckUncheckedUpdateManyWithoutCreatedByInput>
}

export type ProductionCheckScalarWhereInput = {
  AND?: Prisma.ProductionCheckScalarWhereInput | Prisma.ProductionCheckScalarWhereInput[]
  OR?: Prisma.ProductionCheckScalarWhereInput[]
  NOT?: Prisma.ProductionCheckScalarWhereInput | Prisma.ProductionCheckScalarWhereInput[]
  id?: Prisma.StringFilter<"ProductionCheck"> | string
  productionId?: Prisma.StringFilter<"ProductionCheck"> | string
  organizationId?: Prisma.StringFilter<"ProductionCheck"> | string
  status?: Prisma.StringFilter<"ProductionCheck"> | string
  createdById?: Prisma.StringNullableFilter<"ProductionCheck"> | string | null
  closedById?: Prisma.StringNullableFilter<"ProductionCheck"> | string | null
  closedAt?: Prisma.DateTimeNullableFilter<"ProductionCheck"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ProductionCheck"> | Date | string
}

export type ProductionCheckUpsertWithWhereUniqueWithoutClosedByInput = {
  where: Prisma.ProductionCheckWhereUniqueInput
  update: Prisma.XOR<Prisma.ProductionCheckUpdateWithoutClosedByInput, Prisma.ProductionCheckUncheckedUpdateWithoutClosedByInput>
  create: Prisma.XOR<Prisma.ProductionCheckCreateWithoutClosedByInput, Prisma.ProductionCheckUncheckedCreateWithoutClosedByInput>
}

export type ProductionCheckUpdateWithWhereUniqueWithoutClosedByInput = {
  where: Prisma.ProductionCheckWhereUniqueInput
  data: Prisma.XOR<Prisma.ProductionCheckUpdateWithoutClosedByInput, Prisma.ProductionCheckUncheckedUpdateWithoutClosedByInput>
}

export type ProductionCheckUpdateManyWithWhereWithoutClosedByInput = {
  where: Prisma.ProductionCheckScalarWhereInput
  data: Prisma.XOR<Prisma.ProductionCheckUpdateManyMutationInput, Prisma.ProductionCheckUncheckedUpdateManyWithoutClosedByInput>
}

export type ProductionCheckCreateWithoutOrganizationInput = {
  id?: string
  status?: string
  closedAt?: Date | string | null
  createdAt?: Date | string
  production: Prisma.ProductionCreateNestedOneWithoutChecksInput
  createdBy?: Prisma.UserCreateNestedOneWithoutChecksStartedInput
  closedBy?: Prisma.UserCreateNestedOneWithoutChecksClosedInput
  ticks?: Prisma.ProductionCheckTickCreateNestedManyWithoutCheckInput
}

export type ProductionCheckUncheckedCreateWithoutOrganizationInput = {
  id?: string
  productionId: string
  status?: string
  createdById?: string | null
  closedById?: string | null
  closedAt?: Date | string | null
  createdAt?: Date | string
  ticks?: Prisma.ProductionCheckTickUncheckedCreateNestedManyWithoutCheckInput
}

export type ProductionCheckCreateOrConnectWithoutOrganizationInput = {
  where: Prisma.ProductionCheckWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductionCheckCreateWithoutOrganizationInput, Prisma.ProductionCheckUncheckedCreateWithoutOrganizationInput>
}

export type ProductionCheckCreateManyOrganizationInputEnvelope = {
  data: Prisma.ProductionCheckCreateManyOrganizationInput | Prisma.ProductionCheckCreateManyOrganizationInput[]
  skipDuplicates?: boolean
}

export type ProductionCheckUpsertWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.ProductionCheckWhereUniqueInput
  update: Prisma.XOR<Prisma.ProductionCheckUpdateWithoutOrganizationInput, Prisma.ProductionCheckUncheckedUpdateWithoutOrganizationInput>
  create: Prisma.XOR<Prisma.ProductionCheckCreateWithoutOrganizationInput, Prisma.ProductionCheckUncheckedCreateWithoutOrganizationInput>
}

export type ProductionCheckUpdateWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.ProductionCheckWhereUniqueInput
  data: Prisma.XOR<Prisma.ProductionCheckUpdateWithoutOrganizationInput, Prisma.ProductionCheckUncheckedUpdateWithoutOrganizationInput>
}

export type ProductionCheckUpdateManyWithWhereWithoutOrganizationInput = {
  where: Prisma.ProductionCheckScalarWhereInput
  data: Prisma.XOR<Prisma.ProductionCheckUpdateManyMutationInput, Prisma.ProductionCheckUncheckedUpdateManyWithoutOrganizationInput>
}

export type ProductionCheckCreateWithoutProductionInput = {
  id?: string
  status?: string
  closedAt?: Date | string | null
  createdAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutProductionChecksInput
  createdBy?: Prisma.UserCreateNestedOneWithoutChecksStartedInput
  closedBy?: Prisma.UserCreateNestedOneWithoutChecksClosedInput
  ticks?: Prisma.ProductionCheckTickCreateNestedManyWithoutCheckInput
}

export type ProductionCheckUncheckedCreateWithoutProductionInput = {
  id?: string
  organizationId: string
  status?: string
  createdById?: string | null
  closedById?: string | null
  closedAt?: Date | string | null
  createdAt?: Date | string
  ticks?: Prisma.ProductionCheckTickUncheckedCreateNestedManyWithoutCheckInput
}

export type ProductionCheckCreateOrConnectWithoutProductionInput = {
  where: Prisma.ProductionCheckWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductionCheckCreateWithoutProductionInput, Prisma.ProductionCheckUncheckedCreateWithoutProductionInput>
}

export type ProductionCheckCreateManyProductionInputEnvelope = {
  data: Prisma.ProductionCheckCreateManyProductionInput | Prisma.ProductionCheckCreateManyProductionInput[]
  skipDuplicates?: boolean
}

export type ProductionCheckUpsertWithWhereUniqueWithoutProductionInput = {
  where: Prisma.ProductionCheckWhereUniqueInput
  update: Prisma.XOR<Prisma.ProductionCheckUpdateWithoutProductionInput, Prisma.ProductionCheckUncheckedUpdateWithoutProductionInput>
  create: Prisma.XOR<Prisma.ProductionCheckCreateWithoutProductionInput, Prisma.ProductionCheckUncheckedCreateWithoutProductionInput>
}

export type ProductionCheckUpdateWithWhereUniqueWithoutProductionInput = {
  where: Prisma.ProductionCheckWhereUniqueInput
  data: Prisma.XOR<Prisma.ProductionCheckUpdateWithoutProductionInput, Prisma.ProductionCheckUncheckedUpdateWithoutProductionInput>
}

export type ProductionCheckUpdateManyWithWhereWithoutProductionInput = {
  where: Prisma.ProductionCheckScalarWhereInput
  data: Prisma.XOR<Prisma.ProductionCheckUpdateManyMutationInput, Prisma.ProductionCheckUncheckedUpdateManyWithoutProductionInput>
}

export type ProductionCheckCreateWithoutTicksInput = {
  id?: string
  status?: string
  closedAt?: Date | string | null
  createdAt?: Date | string
  production: Prisma.ProductionCreateNestedOneWithoutChecksInput
  organization: Prisma.OrganizationCreateNestedOneWithoutProductionChecksInput
  createdBy?: Prisma.UserCreateNestedOneWithoutChecksStartedInput
  closedBy?: Prisma.UserCreateNestedOneWithoutChecksClosedInput
}

export type ProductionCheckUncheckedCreateWithoutTicksInput = {
  id?: string
  productionId: string
  organizationId: string
  status?: string
  createdById?: string | null
  closedById?: string | null
  closedAt?: Date | string | null
  createdAt?: Date | string
}

export type ProductionCheckCreateOrConnectWithoutTicksInput = {
  where: Prisma.ProductionCheckWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductionCheckCreateWithoutTicksInput, Prisma.ProductionCheckUncheckedCreateWithoutTicksInput>
}

export type ProductionCheckUpsertWithoutTicksInput = {
  update: Prisma.XOR<Prisma.ProductionCheckUpdateWithoutTicksInput, Prisma.ProductionCheckUncheckedUpdateWithoutTicksInput>
  create: Prisma.XOR<Prisma.ProductionCheckCreateWithoutTicksInput, Prisma.ProductionCheckUncheckedCreateWithoutTicksInput>
  where?: Prisma.ProductionCheckWhereInput
}

export type ProductionCheckUpdateToOneWithWhereWithoutTicksInput = {
  where?: Prisma.ProductionCheckWhereInput
  data: Prisma.XOR<Prisma.ProductionCheckUpdateWithoutTicksInput, Prisma.ProductionCheckUncheckedUpdateWithoutTicksInput>
}

export type ProductionCheckUpdateWithoutTicksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  closedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  production?: Prisma.ProductionUpdateOneRequiredWithoutChecksNestedInput
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutProductionChecksNestedInput
  createdBy?: Prisma.UserUpdateOneWithoutChecksStartedNestedInput
  closedBy?: Prisma.UserUpdateOneWithoutChecksClosedNestedInput
}

export type ProductionCheckUncheckedUpdateWithoutTicksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productionId?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  closedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  closedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductionCheckCreateManyCreatedByInput = {
  id?: string
  productionId: string
  organizationId: string
  status?: string
  closedById?: string | null
  closedAt?: Date | string | null
  createdAt?: Date | string
}

export type ProductionCheckCreateManyClosedByInput = {
  id?: string
  productionId: string
  organizationId: string
  status?: string
  createdById?: string | null
  closedAt?: Date | string | null
  createdAt?: Date | string
}

export type ProductionCheckUpdateWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  closedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  production?: Prisma.ProductionUpdateOneRequiredWithoutChecksNestedInput
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutProductionChecksNestedInput
  closedBy?: Prisma.UserUpdateOneWithoutChecksClosedNestedInput
  ticks?: Prisma.ProductionCheckTickUpdateManyWithoutCheckNestedInput
}

export type ProductionCheckUncheckedUpdateWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productionId?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  closedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  closedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ticks?: Prisma.ProductionCheckTickUncheckedUpdateManyWithoutCheckNestedInput
}

export type ProductionCheckUncheckedUpdateManyWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productionId?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  closedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  closedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductionCheckUpdateWithoutClosedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  closedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  production?: Prisma.ProductionUpdateOneRequiredWithoutChecksNestedInput
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutProductionChecksNestedInput
  createdBy?: Prisma.UserUpdateOneWithoutChecksStartedNestedInput
  ticks?: Prisma.ProductionCheckTickUpdateManyWithoutCheckNestedInput
}

export type ProductionCheckUncheckedUpdateWithoutClosedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productionId?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  closedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ticks?: Prisma.ProductionCheckTickUncheckedUpdateManyWithoutCheckNestedInput
}

export type ProductionCheckUncheckedUpdateManyWithoutClosedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productionId?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  closedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductionCheckCreateManyOrganizationInput = {
  id?: string
  productionId: string
  status?: string
  createdById?: string | null
  closedById?: string | null
  closedAt?: Date | string | null
  createdAt?: Date | string
}

export type ProductionCheckUpdateWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  closedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  production?: Prisma.ProductionUpdateOneRequiredWithoutChecksNestedInput
  createdBy?: Prisma.UserUpdateOneWithoutChecksStartedNestedInput
  closedBy?: Prisma.UserUpdateOneWithoutChecksClosedNestedInput
  ticks?: Prisma.ProductionCheckTickUpdateManyWithoutCheckNestedInput
}

export type ProductionCheckUncheckedUpdateWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productionId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  closedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  closedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ticks?: Prisma.ProductionCheckTickUncheckedUpdateManyWithoutCheckNestedInput
}

export type ProductionCheckUncheckedUpdateManyWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productionId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  closedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  closedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductionCheckCreateManyProductionInput = {
  id?: string
  organizationId: string
  status?: string
  createdById?: string | null
  closedById?: string | null
  closedAt?: Date | string | null
  createdAt?: Date | string
}

export type ProductionCheckUpdateWithoutProductionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  closedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutProductionChecksNestedInput
  createdBy?: Prisma.UserUpdateOneWithoutChecksStartedNestedInput
  closedBy?: Prisma.UserUpdateOneWithoutChecksClosedNestedInput
  ticks?: Prisma.ProductionCheckTickUpdateManyWithoutCheckNestedInput
}

export type ProductionCheckUncheckedUpdateWithoutProductionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  closedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  closedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ticks?: Prisma.ProductionCheckTickUncheckedUpdateManyWithoutCheckNestedInput
}

export type ProductionCheckUncheckedUpdateManyWithoutProductionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  closedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  closedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ProductionCheckCountOutputType
 */

export type ProductionCheckCountOutputType = {
  ticks: number
}

export type ProductionCheckCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ticks?: boolean | ProductionCheckCountOutputTypeCountTicksArgs
}

/**
 * ProductionCheckCountOutputType without action
 */
export type ProductionCheckCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheckCountOutputType
   */
  select?: Prisma.ProductionCheckCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProductionCheckCountOutputType without action
 */
export type ProductionCheckCountOutputTypeCountTicksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductionCheckTickWhereInput
}


export type ProductionCheckSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productionId?: boolean
  organizationId?: boolean
  status?: boolean
  createdById?: boolean
  closedById?: boolean
  closedAt?: boolean
  createdAt?: boolean
  production?: boolean | Prisma.ProductionDefaultArgs<ExtArgs>
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.ProductionCheck$createdByArgs<ExtArgs>
  closedBy?: boolean | Prisma.ProductionCheck$closedByArgs<ExtArgs>
  ticks?: boolean | Prisma.ProductionCheck$ticksArgs<ExtArgs>
  _count?: boolean | Prisma.ProductionCheckCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productionCheck"]>

export type ProductionCheckSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productionId?: boolean
  organizationId?: boolean
  status?: boolean
  createdById?: boolean
  closedById?: boolean
  closedAt?: boolean
  createdAt?: boolean
  production?: boolean | Prisma.ProductionDefaultArgs<ExtArgs>
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.ProductionCheck$createdByArgs<ExtArgs>
  closedBy?: boolean | Prisma.ProductionCheck$closedByArgs<ExtArgs>
}, ExtArgs["result"]["productionCheck"]>

export type ProductionCheckSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productionId?: boolean
  organizationId?: boolean
  status?: boolean
  createdById?: boolean
  closedById?: boolean
  closedAt?: boolean
  createdAt?: boolean
  production?: boolean | Prisma.ProductionDefaultArgs<ExtArgs>
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.ProductionCheck$createdByArgs<ExtArgs>
  closedBy?: boolean | Prisma.ProductionCheck$closedByArgs<ExtArgs>
}, ExtArgs["result"]["productionCheck"]>

export type ProductionCheckSelectScalar = {
  id?: boolean
  productionId?: boolean
  organizationId?: boolean
  status?: boolean
  createdById?: boolean
  closedById?: boolean
  closedAt?: boolean
  createdAt?: boolean
}

export type ProductionCheckOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "productionId" | "organizationId" | "status" | "createdById" | "closedById" | "closedAt" | "createdAt", ExtArgs["result"]["productionCheck"]>
export type ProductionCheckInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  production?: boolean | Prisma.ProductionDefaultArgs<ExtArgs>
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.ProductionCheck$createdByArgs<ExtArgs>
  closedBy?: boolean | Prisma.ProductionCheck$closedByArgs<ExtArgs>
  ticks?: boolean | Prisma.ProductionCheck$ticksArgs<ExtArgs>
  _count?: boolean | Prisma.ProductionCheckCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProductionCheckIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  production?: boolean | Prisma.ProductionDefaultArgs<ExtArgs>
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.ProductionCheck$createdByArgs<ExtArgs>
  closedBy?: boolean | Prisma.ProductionCheck$closedByArgs<ExtArgs>
}
export type ProductionCheckIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  production?: boolean | Prisma.ProductionDefaultArgs<ExtArgs>
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.ProductionCheck$createdByArgs<ExtArgs>
  closedBy?: boolean | Prisma.ProductionCheck$closedByArgs<ExtArgs>
}

export type $ProductionCheckPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProductionCheck"
  objects: {
    production: Prisma.$ProductionPayload<ExtArgs>
    organization: Prisma.$OrganizationPayload<ExtArgs>
    createdBy: Prisma.$UserPayload<ExtArgs> | null
    closedBy: Prisma.$UserPayload<ExtArgs> | null
    ticks: Prisma.$ProductionCheckTickPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    productionId: string
    organizationId: string
    status: string
    createdById: string | null
    closedById: string | null
    closedAt: Date | null
    createdAt: Date
  }, ExtArgs["result"]["productionCheck"]>
  composites: {}
}

export type ProductionCheckGetPayload<S extends boolean | null | undefined | ProductionCheckDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProductionCheckPayload, S>

export type ProductionCheckCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProductionCheckFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProductionCheckCountAggregateInputType | true
  }

export interface ProductionCheckDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProductionCheck'], meta: { name: 'ProductionCheck' } }
  /**
   * Find zero or one ProductionCheck that matches the filter.
   * @param {ProductionCheckFindUniqueArgs} args - Arguments to find a ProductionCheck
   * @example
   * // Get one ProductionCheck
   * const productionCheck = await prisma.productionCheck.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProductionCheckFindUniqueArgs>(args: Prisma.SelectSubset<T, ProductionCheckFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProductionCheckClient<runtime.Types.Result.GetResult<Prisma.$ProductionCheckPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProductionCheck that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProductionCheckFindUniqueOrThrowArgs} args - Arguments to find a ProductionCheck
   * @example
   * // Get one ProductionCheck
   * const productionCheck = await prisma.productionCheck.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProductionCheckFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProductionCheckFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductionCheckClient<runtime.Types.Result.GetResult<Prisma.$ProductionCheckPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductionCheck that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductionCheckFindFirstArgs} args - Arguments to find a ProductionCheck
   * @example
   * // Get one ProductionCheck
   * const productionCheck = await prisma.productionCheck.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProductionCheckFindFirstArgs>(args?: Prisma.SelectSubset<T, ProductionCheckFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProductionCheckClient<runtime.Types.Result.GetResult<Prisma.$ProductionCheckPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductionCheck that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductionCheckFindFirstOrThrowArgs} args - Arguments to find a ProductionCheck
   * @example
   * // Get one ProductionCheck
   * const productionCheck = await prisma.productionCheck.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProductionCheckFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProductionCheckFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductionCheckClient<runtime.Types.Result.GetResult<Prisma.$ProductionCheckPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProductionChecks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductionCheckFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProductionChecks
   * const productionChecks = await prisma.productionCheck.findMany()
   * 
   * // Get first 10 ProductionChecks
   * const productionChecks = await prisma.productionCheck.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const productionCheckWithIdOnly = await prisma.productionCheck.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProductionCheckFindManyArgs>(args?: Prisma.SelectSubset<T, ProductionCheckFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductionCheckPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProductionCheck.
   * @param {ProductionCheckCreateArgs} args - Arguments to create a ProductionCheck.
   * @example
   * // Create one ProductionCheck
   * const ProductionCheck = await prisma.productionCheck.create({
   *   data: {
   *     // ... data to create a ProductionCheck
   *   }
   * })
   * 
   */
  create<T extends ProductionCheckCreateArgs>(args: Prisma.SelectSubset<T, ProductionCheckCreateArgs<ExtArgs>>): Prisma.Prisma__ProductionCheckClient<runtime.Types.Result.GetResult<Prisma.$ProductionCheckPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProductionChecks.
   * @param {ProductionCheckCreateManyArgs} args - Arguments to create many ProductionChecks.
   * @example
   * // Create many ProductionChecks
   * const productionCheck = await prisma.productionCheck.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProductionCheckCreateManyArgs>(args?: Prisma.SelectSubset<T, ProductionCheckCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProductionChecks and returns the data saved in the database.
   * @param {ProductionCheckCreateManyAndReturnArgs} args - Arguments to create many ProductionChecks.
   * @example
   * // Create many ProductionChecks
   * const productionCheck = await prisma.productionCheck.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProductionChecks and only return the `id`
   * const productionCheckWithIdOnly = await prisma.productionCheck.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProductionCheckCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProductionCheckCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductionCheckPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProductionCheck.
   * @param {ProductionCheckDeleteArgs} args - Arguments to delete one ProductionCheck.
   * @example
   * // Delete one ProductionCheck
   * const ProductionCheck = await prisma.productionCheck.delete({
   *   where: {
   *     // ... filter to delete one ProductionCheck
   *   }
   * })
   * 
   */
  delete<T extends ProductionCheckDeleteArgs>(args: Prisma.SelectSubset<T, ProductionCheckDeleteArgs<ExtArgs>>): Prisma.Prisma__ProductionCheckClient<runtime.Types.Result.GetResult<Prisma.$ProductionCheckPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProductionCheck.
   * @param {ProductionCheckUpdateArgs} args - Arguments to update one ProductionCheck.
   * @example
   * // Update one ProductionCheck
   * const productionCheck = await prisma.productionCheck.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProductionCheckUpdateArgs>(args: Prisma.SelectSubset<T, ProductionCheckUpdateArgs<ExtArgs>>): Prisma.Prisma__ProductionCheckClient<runtime.Types.Result.GetResult<Prisma.$ProductionCheckPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProductionChecks.
   * @param {ProductionCheckDeleteManyArgs} args - Arguments to filter ProductionChecks to delete.
   * @example
   * // Delete a few ProductionChecks
   * const { count } = await prisma.productionCheck.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProductionCheckDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProductionCheckDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductionChecks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductionCheckUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProductionChecks
   * const productionCheck = await prisma.productionCheck.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProductionCheckUpdateManyArgs>(args: Prisma.SelectSubset<T, ProductionCheckUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductionChecks and returns the data updated in the database.
   * @param {ProductionCheckUpdateManyAndReturnArgs} args - Arguments to update many ProductionChecks.
   * @example
   * // Update many ProductionChecks
   * const productionCheck = await prisma.productionCheck.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProductionChecks and only return the `id`
   * const productionCheckWithIdOnly = await prisma.productionCheck.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProductionCheckUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProductionCheckUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductionCheckPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProductionCheck.
   * @param {ProductionCheckUpsertArgs} args - Arguments to update or create a ProductionCheck.
   * @example
   * // Update or create a ProductionCheck
   * const productionCheck = await prisma.productionCheck.upsert({
   *   create: {
   *     // ... data to create a ProductionCheck
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProductionCheck we want to update
   *   }
   * })
   */
  upsert<T extends ProductionCheckUpsertArgs>(args: Prisma.SelectSubset<T, ProductionCheckUpsertArgs<ExtArgs>>): Prisma.Prisma__ProductionCheckClient<runtime.Types.Result.GetResult<Prisma.$ProductionCheckPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProductionChecks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductionCheckCountArgs} args - Arguments to filter ProductionChecks to count.
   * @example
   * // Count the number of ProductionChecks
   * const count = await prisma.productionCheck.count({
   *   where: {
   *     // ... the filter for the ProductionChecks we want to count
   *   }
   * })
  **/
  count<T extends ProductionCheckCountArgs>(
    args?: Prisma.Subset<T, ProductionCheckCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProductionCheckCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProductionCheck.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductionCheckAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProductionCheckAggregateArgs>(args: Prisma.Subset<T, ProductionCheckAggregateArgs>): Prisma.PrismaPromise<GetProductionCheckAggregateType<T>>

  /**
   * Group by ProductionCheck.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductionCheckGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProductionCheckGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProductionCheckGroupByArgs['orderBy'] }
      : { orderBy?: ProductionCheckGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProductionCheckGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProductionCheckGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProductionCheck model
 */
readonly fields: ProductionCheckFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProductionCheck.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProductionCheckClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  production<T extends Prisma.ProductionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductionDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductionClient<runtime.Types.Result.GetResult<Prisma.$ProductionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  organization<T extends Prisma.OrganizationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrganizationDefaultArgs<ExtArgs>>): Prisma.Prisma__OrganizationClient<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  createdBy<T extends Prisma.ProductionCheck$createdByArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductionCheck$createdByArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  closedBy<T extends Prisma.ProductionCheck$closedByArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductionCheck$closedByArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  ticks<T extends Prisma.ProductionCheck$ticksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductionCheck$ticksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductionCheckTickPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProductionCheck model
 */
export interface ProductionCheckFieldRefs {
  readonly id: Prisma.FieldRef<"ProductionCheck", 'String'>
  readonly productionId: Prisma.FieldRef<"ProductionCheck", 'String'>
  readonly organizationId: Prisma.FieldRef<"ProductionCheck", 'String'>
  readonly status: Prisma.FieldRef<"ProductionCheck", 'String'>
  readonly createdById: Prisma.FieldRef<"ProductionCheck", 'String'>
  readonly closedById: Prisma.FieldRef<"ProductionCheck", 'String'>
  readonly closedAt: Prisma.FieldRef<"ProductionCheck", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"ProductionCheck", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ProductionCheck findUnique
 */
export type ProductionCheckFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheck
   */
  select?: Prisma.ProductionCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheck
   */
  omit?: Prisma.ProductionCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckInclude<ExtArgs> | null
  /**
   * Filter, which ProductionCheck to fetch.
   */
  where: Prisma.ProductionCheckWhereUniqueInput
}

/**
 * ProductionCheck findUniqueOrThrow
 */
export type ProductionCheckFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheck
   */
  select?: Prisma.ProductionCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheck
   */
  omit?: Prisma.ProductionCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckInclude<ExtArgs> | null
  /**
   * Filter, which ProductionCheck to fetch.
   */
  where: Prisma.ProductionCheckWhereUniqueInput
}

/**
 * ProductionCheck findFirst
 */
export type ProductionCheckFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheck
   */
  select?: Prisma.ProductionCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheck
   */
  omit?: Prisma.ProductionCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckInclude<ExtArgs> | null
  /**
   * Filter, which ProductionCheck to fetch.
   */
  where?: Prisma.ProductionCheckWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductionChecks to fetch.
   */
  orderBy?: Prisma.ProductionCheckOrderByWithRelationInput | Prisma.ProductionCheckOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductionChecks.
   */
  cursor?: Prisma.ProductionCheckWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductionChecks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductionChecks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductionChecks.
   */
  distinct?: Prisma.ProductionCheckScalarFieldEnum | Prisma.ProductionCheckScalarFieldEnum[]
}

/**
 * ProductionCheck findFirstOrThrow
 */
export type ProductionCheckFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheck
   */
  select?: Prisma.ProductionCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheck
   */
  omit?: Prisma.ProductionCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckInclude<ExtArgs> | null
  /**
   * Filter, which ProductionCheck to fetch.
   */
  where?: Prisma.ProductionCheckWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductionChecks to fetch.
   */
  orderBy?: Prisma.ProductionCheckOrderByWithRelationInput | Prisma.ProductionCheckOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductionChecks.
   */
  cursor?: Prisma.ProductionCheckWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductionChecks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductionChecks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductionChecks.
   */
  distinct?: Prisma.ProductionCheckScalarFieldEnum | Prisma.ProductionCheckScalarFieldEnum[]
}

/**
 * ProductionCheck findMany
 */
export type ProductionCheckFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheck
   */
  select?: Prisma.ProductionCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheck
   */
  omit?: Prisma.ProductionCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckInclude<ExtArgs> | null
  /**
   * Filter, which ProductionChecks to fetch.
   */
  where?: Prisma.ProductionCheckWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductionChecks to fetch.
   */
  orderBy?: Prisma.ProductionCheckOrderByWithRelationInput | Prisma.ProductionCheckOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProductionChecks.
   */
  cursor?: Prisma.ProductionCheckWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductionChecks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductionChecks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductionChecks.
   */
  distinct?: Prisma.ProductionCheckScalarFieldEnum | Prisma.ProductionCheckScalarFieldEnum[]
}

/**
 * ProductionCheck create
 */
export type ProductionCheckCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheck
   */
  select?: Prisma.ProductionCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheck
   */
  omit?: Prisma.ProductionCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckInclude<ExtArgs> | null
  /**
   * The data needed to create a ProductionCheck.
   */
  data: Prisma.XOR<Prisma.ProductionCheckCreateInput, Prisma.ProductionCheckUncheckedCreateInput>
}

/**
 * ProductionCheck createMany
 */
export type ProductionCheckCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProductionChecks.
   */
  data: Prisma.ProductionCheckCreateManyInput | Prisma.ProductionCheckCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProductionCheck createManyAndReturn
 */
export type ProductionCheckCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheck
   */
  select?: Prisma.ProductionCheckSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheck
   */
  omit?: Prisma.ProductionCheckOmit<ExtArgs> | null
  /**
   * The data used to create many ProductionChecks.
   */
  data: Prisma.ProductionCheckCreateManyInput | Prisma.ProductionCheckCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ProductionCheck update
 */
export type ProductionCheckUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheck
   */
  select?: Prisma.ProductionCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheck
   */
  omit?: Prisma.ProductionCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckInclude<ExtArgs> | null
  /**
   * The data needed to update a ProductionCheck.
   */
  data: Prisma.XOR<Prisma.ProductionCheckUpdateInput, Prisma.ProductionCheckUncheckedUpdateInput>
  /**
   * Choose, which ProductionCheck to update.
   */
  where: Prisma.ProductionCheckWhereUniqueInput
}

/**
 * ProductionCheck updateMany
 */
export type ProductionCheckUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProductionChecks.
   */
  data: Prisma.XOR<Prisma.ProductionCheckUpdateManyMutationInput, Prisma.ProductionCheckUncheckedUpdateManyInput>
  /**
   * Filter which ProductionChecks to update
   */
  where?: Prisma.ProductionCheckWhereInput
  /**
   * Limit how many ProductionChecks to update.
   */
  limit?: number
}

/**
 * ProductionCheck updateManyAndReturn
 */
export type ProductionCheckUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheck
   */
  select?: Prisma.ProductionCheckSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheck
   */
  omit?: Prisma.ProductionCheckOmit<ExtArgs> | null
  /**
   * The data used to update ProductionChecks.
   */
  data: Prisma.XOR<Prisma.ProductionCheckUpdateManyMutationInput, Prisma.ProductionCheckUncheckedUpdateManyInput>
  /**
   * Filter which ProductionChecks to update
   */
  where?: Prisma.ProductionCheckWhereInput
  /**
   * Limit how many ProductionChecks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ProductionCheck upsert
 */
export type ProductionCheckUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheck
   */
  select?: Prisma.ProductionCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheck
   */
  omit?: Prisma.ProductionCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckInclude<ExtArgs> | null
  /**
   * The filter to search for the ProductionCheck to update in case it exists.
   */
  where: Prisma.ProductionCheckWhereUniqueInput
  /**
   * In case the ProductionCheck found by the `where` argument doesn't exist, create a new ProductionCheck with this data.
   */
  create: Prisma.XOR<Prisma.ProductionCheckCreateInput, Prisma.ProductionCheckUncheckedCreateInput>
  /**
   * In case the ProductionCheck was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProductionCheckUpdateInput, Prisma.ProductionCheckUncheckedUpdateInput>
}

/**
 * ProductionCheck delete
 */
export type ProductionCheckDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheck
   */
  select?: Prisma.ProductionCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheck
   */
  omit?: Prisma.ProductionCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckInclude<ExtArgs> | null
  /**
   * Filter which ProductionCheck to delete.
   */
  where: Prisma.ProductionCheckWhereUniqueInput
}

/**
 * ProductionCheck deleteMany
 */
export type ProductionCheckDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductionChecks to delete
   */
  where?: Prisma.ProductionCheckWhereInput
  /**
   * Limit how many ProductionChecks to delete.
   */
  limit?: number
}

/**
 * ProductionCheck.createdBy
 */
export type ProductionCheck$createdByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * ProductionCheck.closedBy
 */
export type ProductionCheck$closedByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * ProductionCheck.ticks
 */
export type ProductionCheck$ticksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheckTick
   */
  select?: Prisma.ProductionCheckTickSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheckTick
   */
  omit?: Prisma.ProductionCheckTickOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckTickInclude<ExtArgs> | null
  where?: Prisma.ProductionCheckTickWhereInput
  orderBy?: Prisma.ProductionCheckTickOrderByWithRelationInput | Prisma.ProductionCheckTickOrderByWithRelationInput[]
  cursor?: Prisma.ProductionCheckTickWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProductionCheckTickScalarFieldEnum | Prisma.ProductionCheckTickScalarFieldEnum[]
}

/**
 * ProductionCheck without action
 */
export type ProductionCheckDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionCheck
   */
  select?: Prisma.ProductionCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionCheck
   */
  omit?: Prisma.ProductionCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionCheckInclude<ExtArgs> | null
}
