import 'dart:async';
import 'dart:io';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

/// What a scan sounds like, so the answer arrives without looking at the
/// screen — the PDA is on a belt and the eyes are on the shelf. Used by every
/// screen that scans, with the same meaning everywhere.
/// The tones themselves are generated by tool/scan_tones.py.
enum ScanTone {
  /// Counted, carry on: one short bright tone.
  ok('sounds/ok.wav', [0, 40]),

  /// This one was counted already: two short lower tones.
  already('sounds/already.wav', [0, 30, 90, 30]),

  /// Look at the screen, something needs you — an unexpected unit, a kit or
  /// accessories to confirm: three rising tones.
  attention('sounds/attention.wav', [0, 60, 80, 60, 80, 60]),

  /// That did not work — an unknown tag, a unit that cannot be booked, no
  /// connection: two falling, rougher tones.
  error('sounds/error.wav', [0, 160, 100, 160]);

  const ScanTone(this.asset, this.buzz);
  final String asset;

  /// The same answer as a vibration, shaped like the tone: off and on times in
  /// milliseconds, starting with off.
  final List<int> buzz;
}

/// Vibrates a [ScanTone]'s pattern. Always, whatever the tone setting says —
/// a phone in a pocket on a loud stage is felt, not heard.
///
/// On Android through MainActivity's own `vibrate`: Flutter's HapticFeedback
/// is a keyboard tick there, which the system drops whenever "vibrate on
/// touch" is off — on most phones, so a scan used to answer with nothing at
/// all. iOS has no such setting to trip over, so it gets the haptics it has.
class ScanBuzz {
  static const _channel = MethodChannel('technikpool/scanner');

  static void play(ScanTone tone) {
    unawaited(_play(tone));
  }

  static Future<void> _play(ScanTone tone) async {
    try {
      if (!kIsWeb && Platform.isAndroid) {
        await _channel.invokeMethod<void>('vibrate', {'pattern': tone.buzz});
        return;
      }
      await switch (tone) {
        ScanTone.ok || ScanTone.already => HapticFeedback.lightImpact(),
        ScanTone.attention => HapticFeedback.mediumImpact(),
        ScanTone.error => HapticFeedback.heavyImpact(),
      };
    } catch (_) {
      // No vibrator, no platform (a test): the scan still counts.
    }
  }
}

/// Plays [ScanTone]s. One small pool per tone, loaded on first use, so a scan
/// that follows the last one closely still gets its sound.
///
/// Never throws: a device that cannot play audio — or a test, where there is
/// no platform at all — still counts, it just does so quietly.
class ScanTones {
  final _pools = <ScanTone, Future<AudioPool?>>{};

  // Short cues that mix with whatever else is playing instead of taking audio
  // focus. On Android they play at media volume: respecting silence there
  // means the ringer volume, and a phone set to vibrate in the warehouse then
  // scanned without a sound. iOS's silent switch still mutes them, which is
  // what an iPhone's owner expects of it.
  static final _context = AudioContextConfig(
    focus: AudioContextConfigFocus.mixWithOthers,
    respectSilence: !kIsWeb && Platform.isIOS,
  ).build();

  void play(ScanTone tone) {
    unawaited(_play(tone));
  }

  Future<void> _play(ScanTone tone) async {
    try {
      final pool = await (_pools[tone] ??= _load(tone));
      await pool?.start();
    } catch (_) {
      // See the class comment.
    }
  }

  Future<AudioPool?> _load(ScanTone tone) async {
    try {
      return await AudioPool.create(
        source: AssetSource(tone.asset),
        maxPlayers: 2,
        audioContext: _context,
        playerMode: PlayerMode.lowLatency,
      );
    } catch (_) {
      return null;
    }
  }
}
