import 'dart:async';

import 'package:audioplayers/audioplayers.dart';

/// What a scan sounds like, so the answer arrives without looking at the
/// screen — the PDA is on a belt and the eyes are on the shelf. Used by every
/// screen that scans, with the same meaning everywhere.
/// The tones themselves are generated by tool/scan_tones.py.
enum ScanTone {
  /// Counted, carry on: one short bright tone.
  ok('sounds/ok.wav'),

  /// This one was counted already: two short lower tones.
  already('sounds/already.wav'),

  /// Look at the screen, something needs you — an unexpected unit, a kit or
  /// accessories to confirm: three rising tones.
  attention('sounds/attention.wav'),

  /// That did not work — an unknown tag, a unit that cannot be booked, no
  /// connection: two falling, rougher tones.
  error('sounds/error.wav');

  const ScanTone(this.asset);
  final String asset;
}

/// Plays [ScanTone]s. One small pool per tone, loaded on first use, so a scan
/// that follows the last one closely still gets its sound.
///
/// Never throws: a device that cannot play audio — or a test, where there is
/// no platform at all — still counts, it just does so quietly.
class ScanTones {
  final _pools = <ScanTone, Future<AudioPool?>>{};

  // Short cues, not media: they mix with whatever else is playing instead of
  // taking audio focus, and iOS's silent switch mutes them.
  static final _context = AudioContextConfig(
    focus: AudioContextConfigFocus.mixWithOthers,
    respectSilence: true,
  ).build();

  void play(ScanTone tone) {
    unawaited(_play(tone));
  }

  Future<void> _play(ScanTone tone) async {
    try {
      final pool = await (_pools[tone] ??= _load(tone));
      await pool?.start();
    } catch (_) {
      // See the class comment.
    }
  }

  Future<AudioPool?> _load(ScanTone tone) async {
    try {
      return await AudioPool.create(
        source: AssetSource(tone.asset),
        maxPlayers: 2,
        audioContext: _context,
        playerMode: PlayerMode.lowLatency,
      );
    } catch (_) {
      return null;
    }
  }
}
