
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AssetBundle` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model AssetBundle
 * 
 */
export type AssetBundleModel = runtime.Types.Result.DefaultSelection<Prisma.$AssetBundlePayload>

export type AggregateAssetBundle = {
  _count: AssetBundleCountAggregateOutputType | null
  _min: AssetBundleMinAggregateOutputType | null
  _max: AssetBundleMaxAggregateOutputType | null
}

export type AssetBundleMinAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  organizationId: string | null
  categoryId: string | null
  locationId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AssetBundleMaxAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  organizationId: string | null
  categoryId: string | null
  locationId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AssetBundleCountAggregateOutputType = {
  id: number
  name: number
  description: number
  organizationId: number
  categoryId: number
  locationId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AssetBundleMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  organizationId?: true
  categoryId?: true
  locationId?: true
  createdAt?: true
  updatedAt?: true
}

export type AssetBundleMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  organizationId?: true
  categoryId?: true
  locationId?: true
  createdAt?: true
  updatedAt?: true
}

export type AssetBundleCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  organizationId?: true
  categoryId?: true
  locationId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AssetBundleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AssetBundle to aggregate.
   */
  where?: Prisma.AssetBundleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssetBundles to fetch.
   */
  orderBy?: Prisma.AssetBundleOrderByWithRelationInput | Prisma.AssetBundleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AssetBundleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssetBundles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssetBundles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AssetBundles
  **/
  _count?: true | AssetBundleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AssetBundleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AssetBundleMaxAggregateInputType
}

export type GetAssetBundleAggregateType<T extends AssetBundleAggregateArgs> = {
      [P in keyof T & keyof AggregateAssetBundle]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAssetBundle[P]>
    : Prisma.GetScalarType<T[P], AggregateAssetBundle[P]>
}




export type AssetBundleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AssetBundleWhereInput
  orderBy?: Prisma.AssetBundleOrderByWithAggregationInput | Prisma.AssetBundleOrderByWithAggregationInput[]
  by: Prisma.AssetBundleScalarFieldEnum[] | Prisma.AssetBundleScalarFieldEnum
  having?: Prisma.AssetBundleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AssetBundleCountAggregateInputType | true
  _min?: AssetBundleMinAggregateInputType
  _max?: AssetBundleMaxAggregateInputType
}

export type AssetBundleGroupByOutputType = {
  id: string
  name: string
  description: string | null
  organizationId: string
  categoryId: string
  locationId: string | null
  createdAt: Date
  updatedAt: Date
  _count: AssetBundleCountAggregateOutputType | null
  _min: AssetBundleMinAggregateOutputType | null
  _max: AssetBundleMaxAggregateOutputType | null
}

export type GetAssetBundleGroupByPayload<T extends AssetBundleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AssetBundleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AssetBundleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AssetBundleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AssetBundleGroupByOutputType[P]>
      }
    >
  >



export type AssetBundleWhereInput = {
  AND?: Prisma.AssetBundleWhereInput | Prisma.AssetBundleWhereInput[]
  OR?: Prisma.AssetBundleWhereInput[]
  NOT?: Prisma.AssetBundleWhereInput | Prisma.AssetBundleWhereInput[]
  id?: Prisma.StringFilter<"AssetBundle"> | string
  name?: Prisma.StringFilter<"AssetBundle"> | string
  description?: Prisma.StringNullableFilter<"AssetBundle"> | string | null
  organizationId?: Prisma.StringFilter<"AssetBundle"> | string
  categoryId?: Prisma.StringFilter<"AssetBundle"> | string
  locationId?: Prisma.StringNullableFilter<"AssetBundle"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AssetBundle"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AssetBundle"> | Date | string
  organization?: Prisma.XOR<Prisma.OrganizationScalarRelationFilter, Prisma.OrganizationWhereInput>
  category?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.CategoryWhereInput>
  location?: Prisma.XOR<Prisma.LocationNullableScalarRelationFilter, Prisma.LocationWhereInput> | null
  assets?: Prisma.AssetListRelationFilter
  productionItems?: Prisma.ProductionItemListRelationFilter
}

export type AssetBundleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  locationId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  organization?: Prisma.OrganizationOrderByWithRelationInput
  category?: Prisma.CategoryOrderByWithRelationInput
  location?: Prisma.LocationOrderByWithRelationInput
  assets?: Prisma.AssetOrderByRelationAggregateInput
  productionItems?: Prisma.ProductionItemOrderByRelationAggregateInput
}

export type AssetBundleWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AssetBundleWhereInput | Prisma.AssetBundleWhereInput[]
  OR?: Prisma.AssetBundleWhereInput[]
  NOT?: Prisma.AssetBundleWhereInput | Prisma.AssetBundleWhereInput[]
  name?: Prisma.StringFilter<"AssetBundle"> | string
  description?: Prisma.StringNullableFilter<"AssetBundle"> | string | null
  organizationId?: Prisma.StringFilter<"AssetBundle"> | string
  categoryId?: Prisma.StringFilter<"AssetBundle"> | string
  locationId?: Prisma.StringNullableFilter<"AssetBundle"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AssetBundle"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AssetBundle"> | Date | string
  organization?: Prisma.XOR<Prisma.OrganizationScalarRelationFilter, Prisma.OrganizationWhereInput>
  category?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.CategoryWhereInput>
  location?: Prisma.XOR<Prisma.LocationNullableScalarRelationFilter, Prisma.LocationWhereInput> | null
  assets?: Prisma.AssetListRelationFilter
  productionItems?: Prisma.ProductionItemListRelationFilter
}, "id">

export type AssetBundleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  locationId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AssetBundleCountOrderByAggregateInput
  _max?: Prisma.AssetBundleMaxOrderByAggregateInput
  _min?: Prisma.AssetBundleMinOrderByAggregateInput
}

export type AssetBundleScalarWhereWithAggregatesInput = {
  AND?: Prisma.AssetBundleScalarWhereWithAggregatesInput | Prisma.AssetBundleScalarWhereWithAggregatesInput[]
  OR?: Prisma.AssetBundleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AssetBundleScalarWhereWithAggregatesInput | Prisma.AssetBundleScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AssetBundle"> | string
  name?: Prisma.StringWithAggregatesFilter<"AssetBundle"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"AssetBundle"> | string | null
  organizationId?: Prisma.StringWithAggregatesFilter<"AssetBundle"> | string
  categoryId?: Prisma.StringWithAggregatesFilter<"AssetBundle"> | string
  locationId?: Prisma.StringNullableWithAggregatesFilter<"AssetBundle"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AssetBundle"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AssetBundle"> | Date | string
}

export type AssetBundleCreateInput = {
  id?: string
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutBundlesInput
  category: Prisma.CategoryCreateNestedOneWithoutBundlesInput
  location?: Prisma.LocationCreateNestedOneWithoutAssetBundlesInput
  assets?: Prisma.AssetCreateNestedManyWithoutBundleInput
  productionItems?: Prisma.ProductionItemCreateNestedManyWithoutSourceBundleInput
}

export type AssetBundleUncheckedCreateInput = {
  id?: string
  name: string
  description?: string | null
  organizationId: string
  categoryId: string
  locationId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  assets?: Prisma.AssetUncheckedCreateNestedManyWithoutBundleInput
  productionItems?: Prisma.ProductionItemUncheckedCreateNestedManyWithoutSourceBundleInput
}

export type AssetBundleUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutBundlesNestedInput
  category?: Prisma.CategoryUpdateOneRequiredWithoutBundlesNestedInput
  location?: Prisma.LocationUpdateOneWithoutAssetBundlesNestedInput
  assets?: Prisma.AssetUpdateManyWithoutBundleNestedInput
  productionItems?: Prisma.ProductionItemUpdateManyWithoutSourceBundleNestedInput
}

export type AssetBundleUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  locationId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assets?: Prisma.AssetUncheckedUpdateManyWithoutBundleNestedInput
  productionItems?: Prisma.ProductionItemUncheckedUpdateManyWithoutSourceBundleNestedInput
}

export type AssetBundleCreateManyInput = {
  id?: string
  name: string
  description?: string | null
  organizationId: string
  categoryId: string
  locationId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AssetBundleUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssetBundleUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  locationId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssetBundleListRelationFilter = {
  every?: Prisma.AssetBundleWhereInput
  some?: Prisma.AssetBundleWhereInput
  none?: Prisma.AssetBundleWhereInput
}

export type AssetBundleOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AssetBundleNullableScalarRelationFilter = {
  is?: Prisma.AssetBundleWhereInput | null
  isNot?: Prisma.AssetBundleWhereInput | null
}

export type AssetBundleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  locationId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AssetBundleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  locationId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AssetBundleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  locationId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AssetBundleCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.AssetBundleCreateWithoutOrganizationInput, Prisma.AssetBundleUncheckedCreateWithoutOrganizationInput> | Prisma.AssetBundleCreateWithoutOrganizationInput[] | Prisma.AssetBundleUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.AssetBundleCreateOrConnectWithoutOrganizationInput | Prisma.AssetBundleCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.AssetBundleCreateManyOrganizationInputEnvelope
  connect?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
}

export type AssetBundleUncheckedCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.AssetBundleCreateWithoutOrganizationInput, Prisma.AssetBundleUncheckedCreateWithoutOrganizationInput> | Prisma.AssetBundleCreateWithoutOrganizationInput[] | Prisma.AssetBundleUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.AssetBundleCreateOrConnectWithoutOrganizationInput | Prisma.AssetBundleCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.AssetBundleCreateManyOrganizationInputEnvelope
  connect?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
}

export type AssetBundleUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.AssetBundleCreateWithoutOrganizationInput, Prisma.AssetBundleUncheckedCreateWithoutOrganizationInput> | Prisma.AssetBundleCreateWithoutOrganizationInput[] | Prisma.AssetBundleUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.AssetBundleCreateOrConnectWithoutOrganizationInput | Prisma.AssetBundleCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.AssetBundleUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.AssetBundleUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.AssetBundleCreateManyOrganizationInputEnvelope
  set?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  disconnect?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  delete?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  connect?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  update?: Prisma.AssetBundleUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.AssetBundleUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.AssetBundleUpdateManyWithWhereWithoutOrganizationInput | Prisma.AssetBundleUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.AssetBundleScalarWhereInput | Prisma.AssetBundleScalarWhereInput[]
}

export type AssetBundleUncheckedUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.AssetBundleCreateWithoutOrganizationInput, Prisma.AssetBundleUncheckedCreateWithoutOrganizationInput> | Prisma.AssetBundleCreateWithoutOrganizationInput[] | Prisma.AssetBundleUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.AssetBundleCreateOrConnectWithoutOrganizationInput | Prisma.AssetBundleCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.AssetBundleUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.AssetBundleUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.AssetBundleCreateManyOrganizationInputEnvelope
  set?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  disconnect?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  delete?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  connect?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  update?: Prisma.AssetBundleUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.AssetBundleUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.AssetBundleUpdateManyWithWhereWithoutOrganizationInput | Prisma.AssetBundleUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.AssetBundleScalarWhereInput | Prisma.AssetBundleScalarWhereInput[]
}

export type AssetBundleCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.AssetBundleCreateWithoutCategoryInput, Prisma.AssetBundleUncheckedCreateWithoutCategoryInput> | Prisma.AssetBundleCreateWithoutCategoryInput[] | Prisma.AssetBundleUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.AssetBundleCreateOrConnectWithoutCategoryInput | Prisma.AssetBundleCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.AssetBundleCreateManyCategoryInputEnvelope
  connect?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
}

export type AssetBundleUncheckedCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.AssetBundleCreateWithoutCategoryInput, Prisma.AssetBundleUncheckedCreateWithoutCategoryInput> | Prisma.AssetBundleCreateWithoutCategoryInput[] | Prisma.AssetBundleUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.AssetBundleCreateOrConnectWithoutCategoryInput | Prisma.AssetBundleCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.AssetBundleCreateManyCategoryInputEnvelope
  connect?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
}

export type AssetBundleUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.AssetBundleCreateWithoutCategoryInput, Prisma.AssetBundleUncheckedCreateWithoutCategoryInput> | Prisma.AssetBundleCreateWithoutCategoryInput[] | Prisma.AssetBundleUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.AssetBundleCreateOrConnectWithoutCategoryInput | Prisma.AssetBundleCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.AssetBundleUpsertWithWhereUniqueWithoutCategoryInput | Prisma.AssetBundleUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.AssetBundleCreateManyCategoryInputEnvelope
  set?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  disconnect?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  delete?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  connect?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  update?: Prisma.AssetBundleUpdateWithWhereUniqueWithoutCategoryInput | Prisma.AssetBundleUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.AssetBundleUpdateManyWithWhereWithoutCategoryInput | Prisma.AssetBundleUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.AssetBundleScalarWhereInput | Prisma.AssetBundleScalarWhereInput[]
}

export type AssetBundleUncheckedUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.AssetBundleCreateWithoutCategoryInput, Prisma.AssetBundleUncheckedCreateWithoutCategoryInput> | Prisma.AssetBundleCreateWithoutCategoryInput[] | Prisma.AssetBundleUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.AssetBundleCreateOrConnectWithoutCategoryInput | Prisma.AssetBundleCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.AssetBundleUpsertWithWhereUniqueWithoutCategoryInput | Prisma.AssetBundleUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.AssetBundleCreateManyCategoryInputEnvelope
  set?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  disconnect?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  delete?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  connect?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  update?: Prisma.AssetBundleUpdateWithWhereUniqueWithoutCategoryInput | Prisma.AssetBundleUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.AssetBundleUpdateManyWithWhereWithoutCategoryInput | Prisma.AssetBundleUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.AssetBundleScalarWhereInput | Prisma.AssetBundleScalarWhereInput[]
}

export type AssetBundleCreateNestedManyWithoutLocationInput = {
  create?: Prisma.XOR<Prisma.AssetBundleCreateWithoutLocationInput, Prisma.AssetBundleUncheckedCreateWithoutLocationInput> | Prisma.AssetBundleCreateWithoutLocationInput[] | Prisma.AssetBundleUncheckedCreateWithoutLocationInput[]
  connectOrCreate?: Prisma.AssetBundleCreateOrConnectWithoutLocationInput | Prisma.AssetBundleCreateOrConnectWithoutLocationInput[]
  createMany?: Prisma.AssetBundleCreateManyLocationInputEnvelope
  connect?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
}

export type AssetBundleUncheckedCreateNestedManyWithoutLocationInput = {
  create?: Prisma.XOR<Prisma.AssetBundleCreateWithoutLocationInput, Prisma.AssetBundleUncheckedCreateWithoutLocationInput> | Prisma.AssetBundleCreateWithoutLocationInput[] | Prisma.AssetBundleUncheckedCreateWithoutLocationInput[]
  connectOrCreate?: Prisma.AssetBundleCreateOrConnectWithoutLocationInput | Prisma.AssetBundleCreateOrConnectWithoutLocationInput[]
  createMany?: Prisma.AssetBundleCreateManyLocationInputEnvelope
  connect?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
}

export type AssetBundleUpdateManyWithoutLocationNestedInput = {
  create?: Prisma.XOR<Prisma.AssetBundleCreateWithoutLocationInput, Prisma.AssetBundleUncheckedCreateWithoutLocationInput> | Prisma.AssetBundleCreateWithoutLocationInput[] | Prisma.AssetBundleUncheckedCreateWithoutLocationInput[]
  connectOrCreate?: Prisma.AssetBundleCreateOrConnectWithoutLocationInput | Prisma.AssetBundleCreateOrConnectWithoutLocationInput[]
  upsert?: Prisma.AssetBundleUpsertWithWhereUniqueWithoutLocationInput | Prisma.AssetBundleUpsertWithWhereUniqueWithoutLocationInput[]
  createMany?: Prisma.AssetBundleCreateManyLocationInputEnvelope
  set?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  disconnect?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  delete?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  connect?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  update?: Prisma.AssetBundleUpdateWithWhereUniqueWithoutLocationInput | Prisma.AssetBundleUpdateWithWhereUniqueWithoutLocationInput[]
  updateMany?: Prisma.AssetBundleUpdateManyWithWhereWithoutLocationInput | Prisma.AssetBundleUpdateManyWithWhereWithoutLocationInput[]
  deleteMany?: Prisma.AssetBundleScalarWhereInput | Prisma.AssetBundleScalarWhereInput[]
}

export type AssetBundleUncheckedUpdateManyWithoutLocationNestedInput = {
  create?: Prisma.XOR<Prisma.AssetBundleCreateWithoutLocationInput, Prisma.AssetBundleUncheckedCreateWithoutLocationInput> | Prisma.AssetBundleCreateWithoutLocationInput[] | Prisma.AssetBundleUncheckedCreateWithoutLocationInput[]
  connectOrCreate?: Prisma.AssetBundleCreateOrConnectWithoutLocationInput | Prisma.AssetBundleCreateOrConnectWithoutLocationInput[]
  upsert?: Prisma.AssetBundleUpsertWithWhereUniqueWithoutLocationInput | Prisma.AssetBundleUpsertWithWhereUniqueWithoutLocationInput[]
  createMany?: Prisma.AssetBundleCreateManyLocationInputEnvelope
  set?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  disconnect?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  delete?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  connect?: Prisma.AssetBundleWhereUniqueInput | Prisma.AssetBundleWhereUniqueInput[]
  update?: Prisma.AssetBundleUpdateWithWhereUniqueWithoutLocationInput | Prisma.AssetBundleUpdateWithWhereUniqueWithoutLocationInput[]
  updateMany?: Prisma.AssetBundleUpdateManyWithWhereWithoutLocationInput | Prisma.AssetBundleUpdateManyWithWhereWithoutLocationInput[]
  deleteMany?: Prisma.AssetBundleScalarWhereInput | Prisma.AssetBundleScalarWhereInput[]
}

export type AssetBundleCreateNestedOneWithoutAssetsInput = {
  create?: Prisma.XOR<Prisma.AssetBundleCreateWithoutAssetsInput, Prisma.AssetBundleUncheckedCreateWithoutAssetsInput>
  connectOrCreate?: Prisma.AssetBundleCreateOrConnectWithoutAssetsInput
  connect?: Prisma.AssetBundleWhereUniqueInput
}

export type AssetBundleUpdateOneWithoutAssetsNestedInput = {
  create?: Prisma.XOR<Prisma.AssetBundleCreateWithoutAssetsInput, Prisma.AssetBundleUncheckedCreateWithoutAssetsInput>
  connectOrCreate?: Prisma.AssetBundleCreateOrConnectWithoutAssetsInput
  upsert?: Prisma.AssetBundleUpsertWithoutAssetsInput
  disconnect?: Prisma.AssetBundleWhereInput | boolean
  delete?: Prisma.AssetBundleWhereInput | boolean
  connect?: Prisma.AssetBundleWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AssetBundleUpdateToOneWithWhereWithoutAssetsInput, Prisma.AssetBundleUpdateWithoutAssetsInput>, Prisma.AssetBundleUncheckedUpdateWithoutAssetsInput>
}

export type AssetBundleCreateNestedOneWithoutProductionItemsInput = {
  create?: Prisma.XOR<Prisma.AssetBundleCreateWithoutProductionItemsInput, Prisma.AssetBundleUncheckedCreateWithoutProductionItemsInput>
  connectOrCreate?: Prisma.AssetBundleCreateOrConnectWithoutProductionItemsInput
  connect?: Prisma.AssetBundleWhereUniqueInput
}

export type AssetBundleUpdateOneWithoutProductionItemsNestedInput = {
  create?: Prisma.XOR<Prisma.AssetBundleCreateWithoutProductionItemsInput, Prisma.AssetBundleUncheckedCreateWithoutProductionItemsInput>
  connectOrCreate?: Prisma.AssetBundleCreateOrConnectWithoutProductionItemsInput
  upsert?: Prisma.AssetBundleUpsertWithoutProductionItemsInput
  disconnect?: Prisma.AssetBundleWhereInput | boolean
  delete?: Prisma.AssetBundleWhereInput | boolean
  connect?: Prisma.AssetBundleWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AssetBundleUpdateToOneWithWhereWithoutProductionItemsInput, Prisma.AssetBundleUpdateWithoutProductionItemsInput>, Prisma.AssetBundleUncheckedUpdateWithoutProductionItemsInput>
}

export type AssetBundleCreateWithoutOrganizationInput = {
  id?: string
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  category: Prisma.CategoryCreateNestedOneWithoutBundlesInput
  location?: Prisma.LocationCreateNestedOneWithoutAssetBundlesInput
  assets?: Prisma.AssetCreateNestedManyWithoutBundleInput
  productionItems?: Prisma.ProductionItemCreateNestedManyWithoutSourceBundleInput
}

export type AssetBundleUncheckedCreateWithoutOrganizationInput = {
  id?: string
  name: string
  description?: string | null
  categoryId: string
  locationId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  assets?: Prisma.AssetUncheckedCreateNestedManyWithoutBundleInput
  productionItems?: Prisma.ProductionItemUncheckedCreateNestedManyWithoutSourceBundleInput
}

export type AssetBundleCreateOrConnectWithoutOrganizationInput = {
  where: Prisma.AssetBundleWhereUniqueInput
  create: Prisma.XOR<Prisma.AssetBundleCreateWithoutOrganizationInput, Prisma.AssetBundleUncheckedCreateWithoutOrganizationInput>
}

export type AssetBundleCreateManyOrganizationInputEnvelope = {
  data: Prisma.AssetBundleCreateManyOrganizationInput | Prisma.AssetBundleCreateManyOrganizationInput[]
  skipDuplicates?: boolean
}

export type AssetBundleUpsertWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.AssetBundleWhereUniqueInput
  update: Prisma.XOR<Prisma.AssetBundleUpdateWithoutOrganizationInput, Prisma.AssetBundleUncheckedUpdateWithoutOrganizationInput>
  create: Prisma.XOR<Prisma.AssetBundleCreateWithoutOrganizationInput, Prisma.AssetBundleUncheckedCreateWithoutOrganizationInput>
}

export type AssetBundleUpdateWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.AssetBundleWhereUniqueInput
  data: Prisma.XOR<Prisma.AssetBundleUpdateWithoutOrganizationInput, Prisma.AssetBundleUncheckedUpdateWithoutOrganizationInput>
}

export type AssetBundleUpdateManyWithWhereWithoutOrganizationInput = {
  where: Prisma.AssetBundleScalarWhereInput
  data: Prisma.XOR<Prisma.AssetBundleUpdateManyMutationInput, Prisma.AssetBundleUncheckedUpdateManyWithoutOrganizationInput>
}

export type AssetBundleScalarWhereInput = {
  AND?: Prisma.AssetBundleScalarWhereInput | Prisma.AssetBundleScalarWhereInput[]
  OR?: Prisma.AssetBundleScalarWhereInput[]
  NOT?: Prisma.AssetBundleScalarWhereInput | Prisma.AssetBundleScalarWhereInput[]
  id?: Prisma.StringFilter<"AssetBundle"> | string
  name?: Prisma.StringFilter<"AssetBundle"> | string
  description?: Prisma.StringNullableFilter<"AssetBundle"> | string | null
  organizationId?: Prisma.StringFilter<"AssetBundle"> | string
  categoryId?: Prisma.StringFilter<"AssetBundle"> | string
  locationId?: Prisma.StringNullableFilter<"AssetBundle"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AssetBundle"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AssetBundle"> | Date | string
}

export type AssetBundleCreateWithoutCategoryInput = {
  id?: string
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutBundlesInput
  location?: Prisma.LocationCreateNestedOneWithoutAssetBundlesInput
  assets?: Prisma.AssetCreateNestedManyWithoutBundleInput
  productionItems?: Prisma.ProductionItemCreateNestedManyWithoutSourceBundleInput
}

export type AssetBundleUncheckedCreateWithoutCategoryInput = {
  id?: string
  name: string
  description?: string | null
  organizationId: string
  locationId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  assets?: Prisma.AssetUncheckedCreateNestedManyWithoutBundleInput
  productionItems?: Prisma.ProductionItemUncheckedCreateNestedManyWithoutSourceBundleInput
}

export type AssetBundleCreateOrConnectWithoutCategoryInput = {
  where: Prisma.AssetBundleWhereUniqueInput
  create: Prisma.XOR<Prisma.AssetBundleCreateWithoutCategoryInput, Prisma.AssetBundleUncheckedCreateWithoutCategoryInput>
}

export type AssetBundleCreateManyCategoryInputEnvelope = {
  data: Prisma.AssetBundleCreateManyCategoryInput | Prisma.AssetBundleCreateManyCategoryInput[]
  skipDuplicates?: boolean
}

export type AssetBundleUpsertWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.AssetBundleWhereUniqueInput
  update: Prisma.XOR<Prisma.AssetBundleUpdateWithoutCategoryInput, Prisma.AssetBundleUncheckedUpdateWithoutCategoryInput>
  create: Prisma.XOR<Prisma.AssetBundleCreateWithoutCategoryInput, Prisma.AssetBundleUncheckedCreateWithoutCategoryInput>
}

export type AssetBundleUpdateWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.AssetBundleWhereUniqueInput
  data: Prisma.XOR<Prisma.AssetBundleUpdateWithoutCategoryInput, Prisma.AssetBundleUncheckedUpdateWithoutCategoryInput>
}

export type AssetBundleUpdateManyWithWhereWithoutCategoryInput = {
  where: Prisma.AssetBundleScalarWhereInput
  data: Prisma.XOR<Prisma.AssetBundleUpdateManyMutationInput, Prisma.AssetBundleUncheckedUpdateManyWithoutCategoryInput>
}

export type AssetBundleCreateWithoutLocationInput = {
  id?: string
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutBundlesInput
  category: Prisma.CategoryCreateNestedOneWithoutBundlesInput
  assets?: Prisma.AssetCreateNestedManyWithoutBundleInput
  productionItems?: Prisma.ProductionItemCreateNestedManyWithoutSourceBundleInput
}

export type AssetBundleUncheckedCreateWithoutLocationInput = {
  id?: string
  name: string
  description?: string | null
  organizationId: string
  categoryId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  assets?: Prisma.AssetUncheckedCreateNestedManyWithoutBundleInput
  productionItems?: Prisma.ProductionItemUncheckedCreateNestedManyWithoutSourceBundleInput
}

export type AssetBundleCreateOrConnectWithoutLocationInput = {
  where: Prisma.AssetBundleWhereUniqueInput
  create: Prisma.XOR<Prisma.AssetBundleCreateWithoutLocationInput, Prisma.AssetBundleUncheckedCreateWithoutLocationInput>
}

export type AssetBundleCreateManyLocationInputEnvelope = {
  data: Prisma.AssetBundleCreateManyLocationInput | Prisma.AssetBundleCreateManyLocationInput[]
  skipDuplicates?: boolean
}

export type AssetBundleUpsertWithWhereUniqueWithoutLocationInput = {
  where: Prisma.AssetBundleWhereUniqueInput
  update: Prisma.XOR<Prisma.AssetBundleUpdateWithoutLocationInput, Prisma.AssetBundleUncheckedUpdateWithoutLocationInput>
  create: Prisma.XOR<Prisma.AssetBundleCreateWithoutLocationInput, Prisma.AssetBundleUncheckedCreateWithoutLocationInput>
}

export type AssetBundleUpdateWithWhereUniqueWithoutLocationInput = {
  where: Prisma.AssetBundleWhereUniqueInput
  data: Prisma.XOR<Prisma.AssetBundleUpdateWithoutLocationInput, Prisma.AssetBundleUncheckedUpdateWithoutLocationInput>
}

export type AssetBundleUpdateManyWithWhereWithoutLocationInput = {
  where: Prisma.AssetBundleScalarWhereInput
  data: Prisma.XOR<Prisma.AssetBundleUpdateManyMutationInput, Prisma.AssetBundleUncheckedUpdateManyWithoutLocationInput>
}

export type AssetBundleCreateWithoutAssetsInput = {
  id?: string
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutBundlesInput
  category: Prisma.CategoryCreateNestedOneWithoutBundlesInput
  location?: Prisma.LocationCreateNestedOneWithoutAssetBundlesInput
  productionItems?: Prisma.ProductionItemCreateNestedManyWithoutSourceBundleInput
}

export type AssetBundleUncheckedCreateWithoutAssetsInput = {
  id?: string
  name: string
  description?: string | null
  organizationId: string
  categoryId: string
  locationId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  productionItems?: Prisma.ProductionItemUncheckedCreateNestedManyWithoutSourceBundleInput
}

export type AssetBundleCreateOrConnectWithoutAssetsInput = {
  where: Prisma.AssetBundleWhereUniqueInput
  create: Prisma.XOR<Prisma.AssetBundleCreateWithoutAssetsInput, Prisma.AssetBundleUncheckedCreateWithoutAssetsInput>
}

export type AssetBundleUpsertWithoutAssetsInput = {
  update: Prisma.XOR<Prisma.AssetBundleUpdateWithoutAssetsInput, Prisma.AssetBundleUncheckedUpdateWithoutAssetsInput>
  create: Prisma.XOR<Prisma.AssetBundleCreateWithoutAssetsInput, Prisma.AssetBundleUncheckedCreateWithoutAssetsInput>
  where?: Prisma.AssetBundleWhereInput
}

export type AssetBundleUpdateToOneWithWhereWithoutAssetsInput = {
  where?: Prisma.AssetBundleWhereInput
  data: Prisma.XOR<Prisma.AssetBundleUpdateWithoutAssetsInput, Prisma.AssetBundleUncheckedUpdateWithoutAssetsInput>
}

export type AssetBundleUpdateWithoutAssetsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutBundlesNestedInput
  category?: Prisma.CategoryUpdateOneRequiredWithoutBundlesNestedInput
  location?: Prisma.LocationUpdateOneWithoutAssetBundlesNestedInput
  productionItems?: Prisma.ProductionItemUpdateManyWithoutSourceBundleNestedInput
}

export type AssetBundleUncheckedUpdateWithoutAssetsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  locationId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  productionItems?: Prisma.ProductionItemUncheckedUpdateManyWithoutSourceBundleNestedInput
}

export type AssetBundleCreateWithoutProductionItemsInput = {
  id?: string
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutBundlesInput
  category: Prisma.CategoryCreateNestedOneWithoutBundlesInput
  location?: Prisma.LocationCreateNestedOneWithoutAssetBundlesInput
  assets?: Prisma.AssetCreateNestedManyWithoutBundleInput
}

export type AssetBundleUncheckedCreateWithoutProductionItemsInput = {
  id?: string
  name: string
  description?: string | null
  organizationId: string
  categoryId: string
  locationId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  assets?: Prisma.AssetUncheckedCreateNestedManyWithoutBundleInput
}

export type AssetBundleCreateOrConnectWithoutProductionItemsInput = {
  where: Prisma.AssetBundleWhereUniqueInput
  create: Prisma.XOR<Prisma.AssetBundleCreateWithoutProductionItemsInput, Prisma.AssetBundleUncheckedCreateWithoutProductionItemsInput>
}

export type AssetBundleUpsertWithoutProductionItemsInput = {
  update: Prisma.XOR<Prisma.AssetBundleUpdateWithoutProductionItemsInput, Prisma.AssetBundleUncheckedUpdateWithoutProductionItemsInput>
  create: Prisma.XOR<Prisma.AssetBundleCreateWithoutProductionItemsInput, Prisma.AssetBundleUncheckedCreateWithoutProductionItemsInput>
  where?: Prisma.AssetBundleWhereInput
}

export type AssetBundleUpdateToOneWithWhereWithoutProductionItemsInput = {
  where?: Prisma.AssetBundleWhereInput
  data: Prisma.XOR<Prisma.AssetBundleUpdateWithoutProductionItemsInput, Prisma.AssetBundleUncheckedUpdateWithoutProductionItemsInput>
}

export type AssetBundleUpdateWithoutProductionItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutBundlesNestedInput
  category?: Prisma.CategoryUpdateOneRequiredWithoutBundlesNestedInput
  location?: Prisma.LocationUpdateOneWithoutAssetBundlesNestedInput
  assets?: Prisma.AssetUpdateManyWithoutBundleNestedInput
}

export type AssetBundleUncheckedUpdateWithoutProductionItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  locationId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assets?: Prisma.AssetUncheckedUpdateManyWithoutBundleNestedInput
}

export type AssetBundleCreateManyOrganizationInput = {
  id?: string
  name: string
  description?: string | null
  categoryId: string
  locationId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AssetBundleUpdateWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.CategoryUpdateOneRequiredWithoutBundlesNestedInput
  location?: Prisma.LocationUpdateOneWithoutAssetBundlesNestedInput
  assets?: Prisma.AssetUpdateManyWithoutBundleNestedInput
  productionItems?: Prisma.ProductionItemUpdateManyWithoutSourceBundleNestedInput
}

export type AssetBundleUncheckedUpdateWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  locationId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assets?: Prisma.AssetUncheckedUpdateManyWithoutBundleNestedInput
  productionItems?: Prisma.ProductionItemUncheckedUpdateManyWithoutSourceBundleNestedInput
}

export type AssetBundleUncheckedUpdateManyWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  locationId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssetBundleCreateManyCategoryInput = {
  id?: string
  name: string
  description?: string | null
  organizationId: string
  locationId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AssetBundleUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutBundlesNestedInput
  location?: Prisma.LocationUpdateOneWithoutAssetBundlesNestedInput
  assets?: Prisma.AssetUpdateManyWithoutBundleNestedInput
  productionItems?: Prisma.ProductionItemUpdateManyWithoutSourceBundleNestedInput
}

export type AssetBundleUncheckedUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  locationId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assets?: Prisma.AssetUncheckedUpdateManyWithoutBundleNestedInput
  productionItems?: Prisma.ProductionItemUncheckedUpdateManyWithoutSourceBundleNestedInput
}

export type AssetBundleUncheckedUpdateManyWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  locationId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssetBundleCreateManyLocationInput = {
  id?: string
  name: string
  description?: string | null
  organizationId: string
  categoryId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AssetBundleUpdateWithoutLocationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutBundlesNestedInput
  category?: Prisma.CategoryUpdateOneRequiredWithoutBundlesNestedInput
  assets?: Prisma.AssetUpdateManyWithoutBundleNestedInput
  productionItems?: Prisma.ProductionItemUpdateManyWithoutSourceBundleNestedInput
}

export type AssetBundleUncheckedUpdateWithoutLocationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assets?: Prisma.AssetUncheckedUpdateManyWithoutBundleNestedInput
  productionItems?: Prisma.ProductionItemUncheckedUpdateManyWithoutSourceBundleNestedInput
}

export type AssetBundleUncheckedUpdateManyWithoutLocationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type AssetBundleCountOutputType
 */

export type AssetBundleCountOutputType = {
  assets: number
  productionItems: number
}

export type AssetBundleCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  assets?: boolean | AssetBundleCountOutputTypeCountAssetsArgs
  productionItems?: boolean | AssetBundleCountOutputTypeCountProductionItemsArgs
}

/**
 * AssetBundleCountOutputType without action
 */
export type AssetBundleCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetBundleCountOutputType
   */
  select?: Prisma.AssetBundleCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AssetBundleCountOutputType without action
 */
export type AssetBundleCountOutputTypeCountAssetsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AssetWhereInput
}

/**
 * AssetBundleCountOutputType without action
 */
export type AssetBundleCountOutputTypeCountProductionItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductionItemWhereInput
}


export type AssetBundleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  organizationId?: boolean
  categoryId?: boolean
  locationId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
  location?: boolean | Prisma.AssetBundle$locationArgs<ExtArgs>
  assets?: boolean | Prisma.AssetBundle$assetsArgs<ExtArgs>
  productionItems?: boolean | Prisma.AssetBundle$productionItemsArgs<ExtArgs>
  _count?: boolean | Prisma.AssetBundleCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assetBundle"]>

export type AssetBundleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  organizationId?: boolean
  categoryId?: boolean
  locationId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
  location?: boolean | Prisma.AssetBundle$locationArgs<ExtArgs>
}, ExtArgs["result"]["assetBundle"]>

export type AssetBundleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  organizationId?: boolean
  categoryId?: boolean
  locationId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
  location?: boolean | Prisma.AssetBundle$locationArgs<ExtArgs>
}, ExtArgs["result"]["assetBundle"]>

export type AssetBundleSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  organizationId?: boolean
  categoryId?: boolean
  locationId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AssetBundleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "organizationId" | "categoryId" | "locationId" | "createdAt" | "updatedAt", ExtArgs["result"]["assetBundle"]>
export type AssetBundleInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
  location?: boolean | Prisma.AssetBundle$locationArgs<ExtArgs>
  assets?: boolean | Prisma.AssetBundle$assetsArgs<ExtArgs>
  productionItems?: boolean | Prisma.AssetBundle$productionItemsArgs<ExtArgs>
  _count?: boolean | Prisma.AssetBundleCountOutputTypeDefaultArgs<ExtArgs>
}
export type AssetBundleIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
  location?: boolean | Prisma.AssetBundle$locationArgs<ExtArgs>
}
export type AssetBundleIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
  location?: boolean | Prisma.AssetBundle$locationArgs<ExtArgs>
}

export type $AssetBundlePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AssetBundle"
  objects: {
    organization: Prisma.$OrganizationPayload<ExtArgs>
    category: Prisma.$CategoryPayload<ExtArgs>
    location: Prisma.$LocationPayload<ExtArgs> | null
    assets: Prisma.$AssetPayload<ExtArgs>[]
    productionItems: Prisma.$ProductionItemPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    description: string | null
    organizationId: string
    categoryId: string
    locationId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["assetBundle"]>
  composites: {}
}

export type AssetBundleGetPayload<S extends boolean | null | undefined | AssetBundleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AssetBundlePayload, S>

export type AssetBundleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AssetBundleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AssetBundleCountAggregateInputType | true
  }

export interface AssetBundleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AssetBundle'], meta: { name: 'AssetBundle' } }
  /**
   * Find zero or one AssetBundle that matches the filter.
   * @param {AssetBundleFindUniqueArgs} args - Arguments to find a AssetBundle
   * @example
   * // Get one AssetBundle
   * const assetBundle = await prisma.assetBundle.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AssetBundleFindUniqueArgs>(args: Prisma.SelectSubset<T, AssetBundleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AssetBundleClient<runtime.Types.Result.GetResult<Prisma.$AssetBundlePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AssetBundle that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AssetBundleFindUniqueOrThrowArgs} args - Arguments to find a AssetBundle
   * @example
   * // Get one AssetBundle
   * const assetBundle = await prisma.assetBundle.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AssetBundleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AssetBundleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssetBundleClient<runtime.Types.Result.GetResult<Prisma.$AssetBundlePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AssetBundle that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetBundleFindFirstArgs} args - Arguments to find a AssetBundle
   * @example
   * // Get one AssetBundle
   * const assetBundle = await prisma.assetBundle.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AssetBundleFindFirstArgs>(args?: Prisma.SelectSubset<T, AssetBundleFindFirstArgs<ExtArgs>>): Prisma.Prisma__AssetBundleClient<runtime.Types.Result.GetResult<Prisma.$AssetBundlePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AssetBundle that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetBundleFindFirstOrThrowArgs} args - Arguments to find a AssetBundle
   * @example
   * // Get one AssetBundle
   * const assetBundle = await prisma.assetBundle.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AssetBundleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AssetBundleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssetBundleClient<runtime.Types.Result.GetResult<Prisma.$AssetBundlePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AssetBundles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetBundleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AssetBundles
   * const assetBundles = await prisma.assetBundle.findMany()
   * 
   * // Get first 10 AssetBundles
   * const assetBundles = await prisma.assetBundle.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const assetBundleWithIdOnly = await prisma.assetBundle.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AssetBundleFindManyArgs>(args?: Prisma.SelectSubset<T, AssetBundleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetBundlePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AssetBundle.
   * @param {AssetBundleCreateArgs} args - Arguments to create a AssetBundle.
   * @example
   * // Create one AssetBundle
   * const AssetBundle = await prisma.assetBundle.create({
   *   data: {
   *     // ... data to create a AssetBundle
   *   }
   * })
   * 
   */
  create<T extends AssetBundleCreateArgs>(args: Prisma.SelectSubset<T, AssetBundleCreateArgs<ExtArgs>>): Prisma.Prisma__AssetBundleClient<runtime.Types.Result.GetResult<Prisma.$AssetBundlePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AssetBundles.
   * @param {AssetBundleCreateManyArgs} args - Arguments to create many AssetBundles.
   * @example
   * // Create many AssetBundles
   * const assetBundle = await prisma.assetBundle.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AssetBundleCreateManyArgs>(args?: Prisma.SelectSubset<T, AssetBundleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AssetBundles and returns the data saved in the database.
   * @param {AssetBundleCreateManyAndReturnArgs} args - Arguments to create many AssetBundles.
   * @example
   * // Create many AssetBundles
   * const assetBundle = await prisma.assetBundle.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AssetBundles and only return the `id`
   * const assetBundleWithIdOnly = await prisma.assetBundle.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AssetBundleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AssetBundleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetBundlePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AssetBundle.
   * @param {AssetBundleDeleteArgs} args - Arguments to delete one AssetBundle.
   * @example
   * // Delete one AssetBundle
   * const AssetBundle = await prisma.assetBundle.delete({
   *   where: {
   *     // ... filter to delete one AssetBundle
   *   }
   * })
   * 
   */
  delete<T extends AssetBundleDeleteArgs>(args: Prisma.SelectSubset<T, AssetBundleDeleteArgs<ExtArgs>>): Prisma.Prisma__AssetBundleClient<runtime.Types.Result.GetResult<Prisma.$AssetBundlePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AssetBundle.
   * @param {AssetBundleUpdateArgs} args - Arguments to update one AssetBundle.
   * @example
   * // Update one AssetBundle
   * const assetBundle = await prisma.assetBundle.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AssetBundleUpdateArgs>(args: Prisma.SelectSubset<T, AssetBundleUpdateArgs<ExtArgs>>): Prisma.Prisma__AssetBundleClient<runtime.Types.Result.GetResult<Prisma.$AssetBundlePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AssetBundles.
   * @param {AssetBundleDeleteManyArgs} args - Arguments to filter AssetBundles to delete.
   * @example
   * // Delete a few AssetBundles
   * const { count } = await prisma.assetBundle.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AssetBundleDeleteManyArgs>(args?: Prisma.SelectSubset<T, AssetBundleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AssetBundles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetBundleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AssetBundles
   * const assetBundle = await prisma.assetBundle.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AssetBundleUpdateManyArgs>(args: Prisma.SelectSubset<T, AssetBundleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AssetBundles and returns the data updated in the database.
   * @param {AssetBundleUpdateManyAndReturnArgs} args - Arguments to update many AssetBundles.
   * @example
   * // Update many AssetBundles
   * const assetBundle = await prisma.assetBundle.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AssetBundles and only return the `id`
   * const assetBundleWithIdOnly = await prisma.assetBundle.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AssetBundleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AssetBundleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetBundlePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AssetBundle.
   * @param {AssetBundleUpsertArgs} args - Arguments to update or create a AssetBundle.
   * @example
   * // Update or create a AssetBundle
   * const assetBundle = await prisma.assetBundle.upsert({
   *   create: {
   *     // ... data to create a AssetBundle
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AssetBundle we want to update
   *   }
   * })
   */
  upsert<T extends AssetBundleUpsertArgs>(args: Prisma.SelectSubset<T, AssetBundleUpsertArgs<ExtArgs>>): Prisma.Prisma__AssetBundleClient<runtime.Types.Result.GetResult<Prisma.$AssetBundlePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AssetBundles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetBundleCountArgs} args - Arguments to filter AssetBundles to count.
   * @example
   * // Count the number of AssetBundles
   * const count = await prisma.assetBundle.count({
   *   where: {
   *     // ... the filter for the AssetBundles we want to count
   *   }
   * })
  **/
  count<T extends AssetBundleCountArgs>(
    args?: Prisma.Subset<T, AssetBundleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AssetBundleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AssetBundle.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetBundleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AssetBundleAggregateArgs>(args: Prisma.Subset<T, AssetBundleAggregateArgs>): Prisma.PrismaPromise<GetAssetBundleAggregateType<T>>

  /**
   * Group by AssetBundle.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetBundleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AssetBundleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AssetBundleGroupByArgs['orderBy'] }
      : { orderBy?: AssetBundleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AssetBundleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAssetBundleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AssetBundle model
 */
readonly fields: AssetBundleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AssetBundle.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AssetBundleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  organization<T extends Prisma.OrganizationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrganizationDefaultArgs<ExtArgs>>): Prisma.Prisma__OrganizationClient<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  category<T extends Prisma.CategoryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CategoryDefaultArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  location<T extends Prisma.AssetBundle$locationArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AssetBundle$locationArgs<ExtArgs>>): Prisma.Prisma__LocationClient<runtime.Types.Result.GetResult<Prisma.$LocationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  assets<T extends Prisma.AssetBundle$assetsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AssetBundle$assetsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  productionItems<T extends Prisma.AssetBundle$productionItemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AssetBundle$productionItemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductionItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AssetBundle model
 */
export interface AssetBundleFieldRefs {
  readonly id: Prisma.FieldRef<"AssetBundle", 'String'>
  readonly name: Prisma.FieldRef<"AssetBundle", 'String'>
  readonly description: Prisma.FieldRef<"AssetBundle", 'String'>
  readonly organizationId: Prisma.FieldRef<"AssetBundle", 'String'>
  readonly categoryId: Prisma.FieldRef<"AssetBundle", 'String'>
  readonly locationId: Prisma.FieldRef<"AssetBundle", 'String'>
  readonly createdAt: Prisma.FieldRef<"AssetBundle", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AssetBundle", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AssetBundle findUnique
 */
export type AssetBundleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetBundle
   */
  select?: Prisma.AssetBundleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetBundle
   */
  omit?: Prisma.AssetBundleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetBundleInclude<ExtArgs> | null
  /**
   * Filter, which AssetBundle to fetch.
   */
  where: Prisma.AssetBundleWhereUniqueInput
}

/**
 * AssetBundle findUniqueOrThrow
 */
export type AssetBundleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetBundle
   */
  select?: Prisma.AssetBundleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetBundle
   */
  omit?: Prisma.AssetBundleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetBundleInclude<ExtArgs> | null
  /**
   * Filter, which AssetBundle to fetch.
   */
  where: Prisma.AssetBundleWhereUniqueInput
}

/**
 * AssetBundle findFirst
 */
export type AssetBundleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetBundle
   */
  select?: Prisma.AssetBundleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetBundle
   */
  omit?: Prisma.AssetBundleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetBundleInclude<ExtArgs> | null
  /**
   * Filter, which AssetBundle to fetch.
   */
  where?: Prisma.AssetBundleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssetBundles to fetch.
   */
  orderBy?: Prisma.AssetBundleOrderByWithRelationInput | Prisma.AssetBundleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AssetBundles.
   */
  cursor?: Prisma.AssetBundleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssetBundles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssetBundles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AssetBundles.
   */
  distinct?: Prisma.AssetBundleScalarFieldEnum | Prisma.AssetBundleScalarFieldEnum[]
}

/**
 * AssetBundle findFirstOrThrow
 */
export type AssetBundleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetBundle
   */
  select?: Prisma.AssetBundleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetBundle
   */
  omit?: Prisma.AssetBundleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetBundleInclude<ExtArgs> | null
  /**
   * Filter, which AssetBundle to fetch.
   */
  where?: Prisma.AssetBundleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssetBundles to fetch.
   */
  orderBy?: Prisma.AssetBundleOrderByWithRelationInput | Prisma.AssetBundleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AssetBundles.
   */
  cursor?: Prisma.AssetBundleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssetBundles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssetBundles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AssetBundles.
   */
  distinct?: Prisma.AssetBundleScalarFieldEnum | Prisma.AssetBundleScalarFieldEnum[]
}

/**
 * AssetBundle findMany
 */
export type AssetBundleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetBundle
   */
  select?: Prisma.AssetBundleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetBundle
   */
  omit?: Prisma.AssetBundleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetBundleInclude<ExtArgs> | null
  /**
   * Filter, which AssetBundles to fetch.
   */
  where?: Prisma.AssetBundleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssetBundles to fetch.
   */
  orderBy?: Prisma.AssetBundleOrderByWithRelationInput | Prisma.AssetBundleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AssetBundles.
   */
  cursor?: Prisma.AssetBundleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssetBundles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssetBundles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AssetBundles.
   */
  distinct?: Prisma.AssetBundleScalarFieldEnum | Prisma.AssetBundleScalarFieldEnum[]
}

/**
 * AssetBundle create
 */
export type AssetBundleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetBundle
   */
  select?: Prisma.AssetBundleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetBundle
   */
  omit?: Prisma.AssetBundleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetBundleInclude<ExtArgs> | null
  /**
   * The data needed to create a AssetBundle.
   */
  data: Prisma.XOR<Prisma.AssetBundleCreateInput, Prisma.AssetBundleUncheckedCreateInput>
}

/**
 * AssetBundle createMany
 */
export type AssetBundleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AssetBundles.
   */
  data: Prisma.AssetBundleCreateManyInput | Prisma.AssetBundleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AssetBundle createManyAndReturn
 */
export type AssetBundleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetBundle
   */
  select?: Prisma.AssetBundleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AssetBundle
   */
  omit?: Prisma.AssetBundleOmit<ExtArgs> | null
  /**
   * The data used to create many AssetBundles.
   */
  data: Prisma.AssetBundleCreateManyInput | Prisma.AssetBundleCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetBundleIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AssetBundle update
 */
export type AssetBundleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetBundle
   */
  select?: Prisma.AssetBundleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetBundle
   */
  omit?: Prisma.AssetBundleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetBundleInclude<ExtArgs> | null
  /**
   * The data needed to update a AssetBundle.
   */
  data: Prisma.XOR<Prisma.AssetBundleUpdateInput, Prisma.AssetBundleUncheckedUpdateInput>
  /**
   * Choose, which AssetBundle to update.
   */
  where: Prisma.AssetBundleWhereUniqueInput
}

/**
 * AssetBundle updateMany
 */
export type AssetBundleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AssetBundles.
   */
  data: Prisma.XOR<Prisma.AssetBundleUpdateManyMutationInput, Prisma.AssetBundleUncheckedUpdateManyInput>
  /**
   * Filter which AssetBundles to update
   */
  where?: Prisma.AssetBundleWhereInput
  /**
   * Limit how many AssetBundles to update.
   */
  limit?: number
}

/**
 * AssetBundle updateManyAndReturn
 */
export type AssetBundleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetBundle
   */
  select?: Prisma.AssetBundleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AssetBundle
   */
  omit?: Prisma.AssetBundleOmit<ExtArgs> | null
  /**
   * The data used to update AssetBundles.
   */
  data: Prisma.XOR<Prisma.AssetBundleUpdateManyMutationInput, Prisma.AssetBundleUncheckedUpdateManyInput>
  /**
   * Filter which AssetBundles to update
   */
  where?: Prisma.AssetBundleWhereInput
  /**
   * Limit how many AssetBundles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetBundleIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AssetBundle upsert
 */
export type AssetBundleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetBundle
   */
  select?: Prisma.AssetBundleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetBundle
   */
  omit?: Prisma.AssetBundleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetBundleInclude<ExtArgs> | null
  /**
   * The filter to search for the AssetBundle to update in case it exists.
   */
  where: Prisma.AssetBundleWhereUniqueInput
  /**
   * In case the AssetBundle found by the `where` argument doesn't exist, create a new AssetBundle with this data.
   */
  create: Prisma.XOR<Prisma.AssetBundleCreateInput, Prisma.AssetBundleUncheckedCreateInput>
  /**
   * In case the AssetBundle was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AssetBundleUpdateInput, Prisma.AssetBundleUncheckedUpdateInput>
}

/**
 * AssetBundle delete
 */
export type AssetBundleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetBundle
   */
  select?: Prisma.AssetBundleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetBundle
   */
  omit?: Prisma.AssetBundleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetBundleInclude<ExtArgs> | null
  /**
   * Filter which AssetBundle to delete.
   */
  where: Prisma.AssetBundleWhereUniqueInput
}

/**
 * AssetBundle deleteMany
 */
export type AssetBundleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AssetBundles to delete
   */
  where?: Prisma.AssetBundleWhereInput
  /**
   * Limit how many AssetBundles to delete.
   */
  limit?: number
}

/**
 * AssetBundle.location
 */
export type AssetBundle$locationArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Location
   */
  select?: Prisma.LocationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Location
   */
  omit?: Prisma.LocationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocationInclude<ExtArgs> | null
  where?: Prisma.LocationWhereInput
}

/**
 * AssetBundle.assets
 */
export type AssetBundle$assetsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  where?: Prisma.AssetWhereInput
  orderBy?: Prisma.AssetOrderByWithRelationInput | Prisma.AssetOrderByWithRelationInput[]
  cursor?: Prisma.AssetWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AssetScalarFieldEnum | Prisma.AssetScalarFieldEnum[]
}

/**
 * AssetBundle.productionItems
 */
export type AssetBundle$productionItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductionItem
   */
  select?: Prisma.ProductionItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductionItem
   */
  omit?: Prisma.ProductionItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductionItemInclude<ExtArgs> | null
  where?: Prisma.ProductionItemWhereInput
  orderBy?: Prisma.ProductionItemOrderByWithRelationInput | Prisma.ProductionItemOrderByWithRelationInput[]
  cursor?: Prisma.ProductionItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProductionItemScalarFieldEnum | Prisma.ProductionItemScalarFieldEnum[]
}

/**
 * AssetBundle without action
 */
export type AssetBundleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetBundle
   */
  select?: Prisma.AssetBundleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetBundle
   */
  omit?: Prisma.AssetBundleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetBundleInclude<ExtArgs> | null
}
